### ISSUE TITLE
FEAT: Hyperboards with financial contributors should display placeholder for all unclaimed fractions of the sponsor hypercerts

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1000]

**Comment by benedictvscriticus** [comment]
@holkeb what do you want to display in the placeholder?

**Comment by holkeb** [comment]
the minter/owner can just decide what they want to display, hence we don't need an additional feature, but the image they use defines it

**Comment by holkeb** [comment]
The owner of a hypercerts defines separately from any data of the hypercert, what image they want to display on the hyperboard. So, this image can also be used for the placeholder.

If a "future owner" is supposed to be displayed in a placeholder and doesn't have an image associated with the eth address or email, then the admin of the board can define the image displayed

**Comment by benedictvscriticus** [comment]
So the default flow is that the hyperboard owner defines (a) default image(s), which later may get substituted by the hypercert owners' choice of images. Thus, the flow both for hypercert display customisation and 'placeholders' is conceptually identical. Is this correct?

**Comment by holkeb** [comment]
Yes, I that should be correct. I think I want to visually show the flows to make this a bit more tangible and complete.

**Comment by benedictvscriticus** [comment]
@eirena did you see this? Just confirming that the white spaces below actually are just that - blueprints.


<img width="829" alt="Screenshot 2023-10-20 at 12 23 20 AM" src="https://github.com/hypercerts-org/hypercerts/assets/104435781/0ac3fc4a-9de8-4d39-ad7f-ba8f663eefa7">
