### ISSUE TITLE
FEAT: Sponsoring a fraction of a hypercert representing organizers (future) work, returns the funder with a Hypercert for their sponsorship.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1001]
An organizer can mint hypercerts and define their prices and a minimum contribution (e.g. 10% of the hypercert)

**Comment by benedictvscriticus** [comment]
@bitbeckers said on August 15: @benedictvscriticus what does this mean exactly? For context in the current FE we have 10000 units in a claim which maps to 100.00.

**Comment by bitbeckers** [comment]
@benedictvscriticus similar to: #996 and #998 

I think all three of these issues are this one user story:

As a funder, I want to receive a hypercert fraction for my donation, so that I can 'see' the impact of my gift

@Jipperism what do you think? Should we do this in one go?

**Comment by benedictvscriticus** [comment]
This ticket is the condensed version of https://github.com/hypercerts-org/hypercerts/issues/998 and https://github.com/hypercerts-org/hypercerts/issues/996

**Comment by holkeb** [comment]
FYI let's keep on using 10,000 units as the standard that is put in place in the frontend for the sponsorship application. On the contract level any number of units is possible.
