### ISSUE TITLE
FEAT: The description of talks should show the speaker name, speaker and talk description.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1024]

**Comment by benedictvscriticus** [comment]
It is assuming that there is some sort of detail page. @holkeb do you wish a detail page for FtC Istanbul? If so, @eirena needs to design one.

**Comment by holkeb** [comment]
As every talk is a hypercert, the hypercert view page is the detail page

**Comment by benedictvscriticus** [comment]
This implies that the hypercerts view page has to be designed by @eirena. Though, I think we are referring to the same feature.

**Comment by holkeb** [comment]
I'm talking about this page for example: https://hypercerts.org/app/view#claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-13588495758253835661482938198572799988072448

**Comment by benedictvscriticus** [comment]
@holkeb, thank you for clarifying. Indeed, I expected something more capsuled within a hyperboard, but what you are referring to could also be something for now to iterating on later.

**Comment by benedictvscriticus** [comment]
<img width="590" alt="Screenshot 2023-10-20 at 12 28 41 AM" src="https://github.com/hypercerts-org/hypercerts/assets/104435781/a1a3a097-8065-410b-99f9-b72a3f512340">
