### ISSUE TITLE
TASK: Implement registry overview and check-out as designed by UI/UX designer

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1037]

**Comment by benedictvscriticus** [comment]
We will not do UI/UX based checkout for FtC.

**Comment by holkeb** [comment]
I would like to explore how buying directly from a hyperboard would look like (with Ira), but I think that's something for after FtC.

For now we can just implement something simple, let me get back to you on this (either using the current design or I adapt it slightly)

**Comment by benedictvscriticus** [comment]
@eirena, as @holkeb stated above the checkout process could become more intertwined with the representation on hyperboards.

**Comment by benedictvscriticus** [comment]
@holkeb should we discard this and create a new ticket for implementation once @eirena has designed the checkout page or continue working here?

**Comment by holkeb** [comment]
sounds good

**Comment by Jipperism** [comment]
Ok, closing.
