### ISSUE TITLE
[Outreach] CRM: Build list of contact information for all projects

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#104]

**Comment by ccerv1** [comment]
@holkeb bumping this so we are ready to pull the trigger on outreach next week

**Comment by holkeb** [comment]
I just extended your test user tracking, which we then can upload to the gmail plug-in: https://docs.google.com/spreadsheets/d/1Ps2eTw-FwJdN1he0OkwKep9AgN2C9J6KrH20rGwFESI/edit?usp=sharing

**Comment by holkeb** [comment]
@ccerv1 
- do you already have additional email addresses?
- can you add the link to the project profile easily?

**Comment by ccerv1** [comment]
Updated with more project info. I don't have email addresses (apart from the ones in the user research notion)

**Comment by holkeb** [comment]
@ccerv1 does it work for you to use the gsheet for tracking?

Question: Can the sheet "TestUsers" be deleted? The same data is in the main sheet

I think we can reach out via twitter with the CTA and ask for an email address if they prefer communication via email.

**Comment by holkeb** [comment]
closing this for now, if this way doesn't work well, let's revisit
