### ISSUE TITLE
Example app TS/JS

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1049]
### Describe the feature you'd like to request

As a developer, I want to be able to inspect and example implementation for JS and TS using the SDK to read and mint hypercerts, so that I can verify my custom implementations.

### Describe the solution you'd like

* repo with example TS app
* repo with example JS app

### Describe alternatives you've considered

.

**Comment by ryscheng** [comment]
CC @hangleang check this out

**Comment by hangleang** [comment]
thank @ryscheng, looking forward for the sample implementation

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/demo-apps
