### ISSUE TITLE
Update the sequence, naming and hyper-referencing of docs

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#105]
https://network-goods.github.io/hypercerts-docs/

**Comment by holkeb** [comment]
https://docs.google.com/document/d/18OV_MrNhPl3q-8fiJArSJ1lxI0uzTezd-9pppvM7Sg4/edit?usp=sharing

**Comment by ccerv1** [comment]
@holkeb Updating this issue to make it clearer what needs to be done.

Basically, the goal is to have a consistent look and feel of this: 


![Image](https://user-images.githubusercontent.com/42869436/217333478-f1a99d40-9a36-49b5-aa55-224a84319609.png)

**Comment by holkeb** [comment]
@ccerv1 

cleaned the structure of the docs a bit: https://docs.google.com/document/d/18OV_MrNhPl3q-8fiJArSJ1lxI0uzTezd-9pppvM7Sg4/edit?usp=sharing

implemented on branch here: https://hypercerts-git-structuring-docs-network-goods.vercel.app/docs

**Comment by holkeb** [comment]
@ccerv1 updated the docs and pushed the new structure. not fully happy yet, but appreciate your thoughts

**Comment by ccerv1** [comment]
Going to work on this now!

**Comment by holkeb** [comment]
note to self: change layout of sidebar, so that the levels are clearly distinguishable

**Comment by holkeb** [comment]
Done for now, I'll do some cosmetic stuff later again
