### ISSUE TITLE
STORY: As a hyperboard owner, I want to be able to control the display size of hypercerts using a predefined set of strategies.

### ISSUE THREAD

**Issue by Jipperism** [hypercerts-org/hypercerts#1072]
- [x] #1099

**Comment by benedictvscriticus** [comment]
@holkeb do you already have an idea of the strategies that should be employed?

**Comment by holkeb** [comment]
For now: The owners just set a relative size for each hypercert. This should be upgradable to any arbitrary function, e.g. depending on evaluations

**Comment by benedictvscriticus** [comment]
No strategies for now because we use flat numbers. It is in the database, but not in the UI yet.

**Comment by Jipperism** [comment]
@holkeb @benedictvscriticus 

Summary of the meeting outcome:
- owner of a collection should be able to set the relative size for each hypercerts, which will translate to the total space on the board used by that hypercert.
- that space will then be divided up over the owners of the fractions inside that hypercert.

An example:
I add 2 hypercerts
- 1 of 1 unit for stage hosting, and the owner is protocol labs, with size value 1
- 1 of 10 units for bar costs, and 10 different people all own 1 unit with size value 1

this would result in a hyperboard divided up in 2 equal parts, one of which is 1 big tile, and the other one is divided up in 10 smaller tiles.

correct?

**Comment by holkeb** [comment]
Yes, this is correct. 

Changing your example:
I add 2 hypercerts
- 1 of 1 unit for stage hosting, and the owner is protocol labs, with size value 1
- 1 of 10 units for bar costs, and 10 different people all own 1 unit with size value 3
this would result in a hyperboard divided up in 2 parts, one covers 25% of the space, the other 75%. The 25% is covered by 1 big tile, and the other 75% is divided up in 10 smaller tiles (each 7.5%).
