### ISSUE TITLE
As a system, I want to use sign-in-with-Ethereum to permission access for users.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1083]
- [ ] FEAT: Sign in with Ethereum

**Comment by Jipperism** [comment]
@holkeb  (and also a bit @bitbeckers). Supabase requires an email for signing up users (which we're using for auth so they cannot edit other people's hyperboards etc). We have several options here, one of which is actually asking them for their email address, or inserting a placeholder. Asking them for email might be useful as we could use that at some later point to send email notifications etc (about the marketplace for example). What do you think?

**Comment by holkeb** [comment]
I'm ok with asking for users' email addresses... the users here are everyone who would be a hyperboard admin, right?

**Comment by benedictvscriticus** [comment]
> I'm ok with asking for users' email addresses... the users here are everyone who would be a hyperboard admin, right?

@holkeb In an ideal world we would use the same authentication method for the administration of hypercerts by their owners and hyperboard admins, but I am open to a tiered approach. Thus, email + eth for hyperboard admins and eth for hypercert owners. What to you think?

**Comment by holkeb** [comment]
Yes, especially in the beginning this is fine as I don't plan to have it open yet, i.e. the Foundation gives access to specific users to build hyperboards.

Do we run into an issue with Optimism multi-sigs for the owners as they don't work as Eth addresses?

**Comment by Jipperism** [comment]
@benedictvscriticus I think it would be easiest to just register the email for everybody. Only alternative is generating a random email for hypercert owners when they try and update their metadata.

The email is actually not used for anything. It's only there because supabase required either an email address or a phone number when creating a new user account. Since @holkeb mentioned notification emails I figured it could be a 2 birds one stone situation.

**Comment by benedictvscriticus** [comment]
Understood @Jipperism, so from what I understand it's a dependency from supabase and how they authenticate users. Let's go for it if it saves time and gets two things done at once.

**Comment by benedictvscriticus** [comment]
We didn't end up implementing it with Sign in with Ethereum.
