### ISSUE TITLE
TASK: Set up a project for Vercel.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1087]

**Comment by holkeb** [comment]
@Jipperism do we need a new Vercel project that I should set up? Or do you have one where you just add me as an owner or so and I add payment details.

**Comment by benedictvscriticus** [comment]
@Jipperism following up on that.

**Comment by Jipperism** [comment]
Yes @holkeb , we definitely need this for deploying the zuzalu retroactive funding form on hyperboards.
