### ISSUE TITLE
FEAT: Sponsorship will be a separate website and separate entity. It will provide a central place where you can do this.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1089]

**Comment by benedictvscriticus** [comment]
@holkeb does that even still apply?

**Comment by holkeb** [comment]
Not a priority for now. We might want to have a simple landing page at some point to explain how people can use this for events. Deprioritized.

**Comment by benedictvscriticus** [comment]
@holkeb understood
