### ISSUE TITLE
STORY: As a seller, I want to be able to make a direct sale offer of hypercerts, so that buyer can directly fund impact.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1109]
- [x] #1153
- [x] #1154
- [x] #1155
- [x] #1156

**Comment by bitbeckers** [comment]
Cleaned up [LooksRare fork](https://github.com/bitbeckers/looksrare-contracts-exchange-v2) and integrating in monorepo during this story.
