### ISSUE TITLE
feat: billboard displays the newest associated image in the space that is allocated to the hypercert owner

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1127]
The billboard displays the newest associated image in the space that is allocated to the hypercert owner

**Comment by benedictvscriticus** [comment]
@holkeb what does 'space' refer to in the description?

**Comment by holkeb** [comment]
It is the space on the billboard. Imagine a normal real-life non-digital billboard. The full billboard is 100%. Now we move to the hyperboard, which for the sake of an example just contains one hypercert. If I own 10% of that hypercert, I can define what image is shown in 10% of the space on the hyperboard.

**Comment by benedictvscriticus** [comment]
Understood @holkeb! I just wanted to ensure we're on the same page. The way you described it makes sense. Thank you!

**Comment by Jipperism** [comment]
Completed.
