### ISSUE TITLE
task: Create a form to allow hypercert owners to add an entry to the database linking new images to their address for specific hypercerts

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1130]
Create a form to allow hypercert owners to add an entry to the database linking a new images to their address for specific hypercerts

**Comment by Jipperism** [comment]
New solution TBD.

**Comment by bitbeckers** [comment]
@Jipperism if it's TBD we need an item on the roadmap or board. Otherwise it'll get forgotten/lost
