### ISSUE TITLE
[Docs] Search function in documentation

### ISSUE THREAD

**Issue by ChialiT** [hypercerts-org/hypercerts#1143]
### Describe the feature you'd like to request

Aa a newbie to hypercerts, I'd like to learn quickly by searching specific features.

### Describe the solution you'd like

docusaurus offers search function, see: https://docusaurus.io/docs/searcha 

### Describe alternatives you've considered

No alternative in mind.

**Comment by bitbeckers** [comment]
Requested access to https://docsearch.algolia.com/

**Comment by bitbeckers** [comment]
Approved, waiting for the setup instructions

**Comment by bitbeckers** [comment]
Search is live: https://hypercerts.org/docs/

Not all files appear to be indexed. I'll check in again on Monday to give the servers some time to index and will follow up if needed
