### ISSUE TITLE
Retiring hypercerts: Burn or transfer restriction

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#117]
The whitepaper currently says: 
> Technically retiring hypercerts means that they are sent to a specific null address, which ensures that the retired hypercerts are recorded and traceable.

And @ryscheng put forth two options:
> Option 1: just burn it (how its described). The indexer knows who was the last holder but we can save gas in the actual contract
> 
> Option 2: Leave it in the smart contract, but just turn on transfer restrictions so its basically frozen. 
> 
> I think burning seems reasonable if we don't think "tom-bradying" is a real operation (aka jump out of retirement over and over again)

Questions:
1. Retiring is currently implemented as burning, correct?
2. Is there an advantage of option 2 for the user experience, i.e. it is easier to have the hypercerts in my wallet with transfer restrictions? Or does that not matter because we can just display in our interface, which hypercerts I burned?

**Comment by bitbeckers** [comment]
Technically option 1 and 2 overlap. The token always remains in the contract, the question is who has control over it. That's why burning is moving the token to the 0-address, because nobody controls that wallet and the chanse they will is very low.

Question 2: Transfer restrictions or burning both require a transaction, we can always surface who burned what, so if you want to retire or burn move to 0-address

**Comment by holkeb** [comment]
ok, I'm hearing it is irrelevant :D that works for me. I assumed it might be a difference on other platforms, e.g. with a transfer restriction I might still see it on opensea as mine, but a burned one I don't see in my wallet.

(your understanding that retiring implies never using it again is correct and it means credibly not be able to)

**Comment by bitbeckers** [comment]
1) "I assumed it might be a difference on other platforms, e.g. with a transfer restriction I might still see it on opensea as mine, but a burned one I don't see in my wallet." - I think that's true.

2) Moved the linked issue to TODO because we haven't focussed on burn and testing it @ryscheng .

**Comment by ryscheng** [comment]
Yes that's right, I think Holke's point about it showing up in your wallet is the primary distinction here.

I think we are talking about 2 different things:
1. Can I burn my token (send to address 0)
2. Can I later change my transfer restriction to something else? (including disallow transfers). 

We can add 2 later, but for now let's just do 1?

**Comment by holkeb** [comment]
Yes, sounds good. Point 1 is sufficient for now.

Point 2 is somewhat problematic, but as we aren't doing this now, we don't need to distract us with that discussion

**Comment by holkeb** [comment]
@ryscheng @bitbeckers question: Is the burn functionality influenced by the transfer restriction or is there an exception, e.g. as an owner of a fraction – without being the minter – I can not transfer my fraction except to the null address?

**Comment by ryscheng** [comment]
Good question, I just carved out an exception here
https://github.com/hypercerts-org/hypercerts/pull/289

So that transfer restrictions *do not* apply to mints or burns. It was causing a bug with allowlist minting.

**Comment by holkeb** [comment]
Great.

Just to double check: If I claim a fraction as a funder from the allowlist, I will NOT be treated as the original minter, right?

**Comment by ryscheng** [comment]
that's right.
