### ISSUE TITLE
Client is read only despite necessary parameters

### ISSUE THREAD

**Issue by polus-arcticus** [hypercerts-org/hypercerts#1187]
### To Reproduce

git clone, npm install, and add a nftstorage token in the App.tsx file.  Use an injected wallet on optimism network
https://github.com/polus-arcticus/hypercerts-bug

### Describe the Bug

attempts to create a writable hypercert client seems to fail despite the appropriate config being provided.  It is in read only mode despite the addition of a publicClient, walletClient, chain: { id: 10}  and nftStorageToken

### Expected Behavior

should provide a client that can call mint
![Screenshot from 2023-11-22 12-14-10](https://github.com/hypercerts-org/hypercerts/assets/122753557/7f151798-e891-48e9-a8cd-add3124a5249)

**Comment by bitbeckers** [comment]
The logs show that you're missing the Web3Storage key, have you provided that?

**Comment by polus-arcticus** [comment]
> The logs show that you're missing the Web3Storage key, have you provided that?

Hi @bitbeckers thanks for your attention.  Thank you, i misread the docs and thought i only needed to provide one or the other, this will likely fix it
