### ISSUE TITLE
[EVM] Marketplace finalisation

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1194]
- [x] #1198
- [x] #1195
- [x] Update error handling code
- [x] Update NatSpec annotations
- [x] Polish

**Comment by benedictvscriticus** [comment]
This issue is duplicated here https://github.com/hypercerts-org/hypercerts/issues/1162

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/hypercerts/pull/1213
