### ISSUE TITLE
Minting Authorization from contributors list 

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#120]
From Davidad:
My hope is that hypercert minting will be authenticated so that contributors are cryptographically verified to have consented to a hypercert's minting before it enters the ledger. I am not sure if this is still in the implementation plan, and I also haven't seen it (yet?) in this whitepaper, but I think it should be in both.

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/9
