### ISSUE TITLE
[FE][UX] - Bug free creation form

### ISSUE THREAD

**Issue by ChialiT** [hypercerts-org/hypercerts#1218]
### Describe the feature you'd like to request

UX improvement:
- when user actually enter more than 50 characters in the name field, the UI show error message about min. 50 characters required, although after few refresh, the error message will be disappeared.
- When user switch network, we shouldn't erase the data they entered from the create hypercert form, its not user friendly.

### Describe the solution you'd like

Expected to have less UI bugs, and much more friendly flow to reduce the frustration.

### Describe alternatives you've considered

none.

**Comment by bitbeckers** [comment]
Cleaning up board. Moving this issue into the refinement for the updated front-end app here: https://github.com/hypercerts-org/HIPs/discussions/5
