### ISSUE TITLE
[SDK] Fully typed Graph types

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1229]
### Describe the feature you'd like to request

Missing tokenID, among others

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by bitbeckers** [comment]
@Jipperism is this in #1301 ? If so, can we close it on merge? If not, I propose we add this when the indexer/API updates are done (this or next week) and close it for not. Feel free to close if it's the latter.

**Comment by Jipperism** [comment]
This is not in #1301 so closing. Let's add it to the indexer/API updates.

**Comment by Jipperism** [comment]
Pinging @bitbeckers
