### ISSUE TITLE
[SDK] Support batch graph queries for all supported chains

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1232]
### Describe the feature you'd like to request

As a user, I want to be able to inspect all hypercerts owned by my address across multiple chains.
As a developer, I want to be able to retrieve either all testnet or production hypercerts, to not confuse users about their ownership
As a developer, I want to prevent users seeing hypercerts assigned to their address but not owner by them, like in a case with a Safe address, to not confuse users about their ownership

### Describe the solution you'd like

Based on chainId, provide all test or production hypercerts for a given address.

### Describe alternatives you've considered

Leaving it to the users of the SDK, but we should facilitate easy development and onboarding into hypercerts tooling

**Comment by bitbeckers** [comment]
@Jipperism is this in #1286 ?

**Comment by Jipperism** [comment]
Closing because https://github.com/hypercerts-org/hypercerts/issues/1286 got merged.
