### ISSUE TITLE
[EVM] Goerli deprecation

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1234]
### Describe the feature you'd like to request

Deprecate Goerli from:

- [x] SDK
- [x] Defender
- [x] Graph
- [x] FE
- [x] Demo apps
- [x] Starter app
- [x] Hyperboards

Steps after deployment:
- [x] Rollout new version of sdk
- [x] Update frontend SDK dependency
- [x] Update demo app SDK dependency
- [x] Update starter app SDK dependency
- [x] Delete remaining defender auto-tasks and monitors
- [ ] Delete goerli graph instance

### Describe the solution you'd like

Goerli is no longer an option to use any of the tools in the list above

### Describe alternatives you've considered

.

**Comment by Jipperism** [comment]
We should announce this today @bitbeckers, and then turn it off on friday the 22nd of december 2023. @bitbeckers

**Comment by holkeb** [comment]
Agreed. Feel free to do so and announce in the telegram channel. I'll update the banner on the website accordingly when I wake up (still on New Zealand time)

**Comment by Jipperism** [comment]
@bitbeckers I don't have push permission to the demo-apps repo, and can't add myself. I did deprecate Goerli there so if you can add me I'll push the branch.

**Comment by bitbeckers** [comment]
All done
