### ISSUE TITLE
[FE] Display hypercerts without being connected to a network

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1247]
### Describe the feature you'd like to request

As a user, I want to be able to inspect hypercerts without needing to connect my wallet or be connected to the correct network

### Describe the solution you'd like

#1235 
#1232

### Describe alternatives you've considered

Requiring users to be connected to the correct chain. I've been getting frequent comments/complaints about this clunky UX

**Comment by Jipperism** [comment]
Blocked by #1235 and #1232

**Comment by bitbeckers** [comment]
@Jipperism is this in #1286 ?

**Comment by Jipperism** [comment]
@bitbeckers wondering whether this can be closed, as we won't update the frontend but the functionality is there now for hyperboards any other app using sdk from 2.0.0 onwards.

**Comment by bitbeckers** [comment]
Yep, agreed, added to the FE refinement [here](https://github.com/hypercerts-org/HIPs/discussions/5)
