### ISSUE TITLE
[FE] Hypercerts should display on which chain they are

### ISSUE THREAD

**Issue by Jipperism** [hypercerts-org/hypercerts#1249]
### Describe the feature you'd like to request

When in the 'claim all fractions' overview, each row should display which chain this claimable fraction lives on, once results from multiple chains are displayed #1247. This should also be done for all tiles that are displayed.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by Vtalike** [comment]
> ### Describe the feature you'd like to request
> 
> When in the 'claim all fractions' overview, each row should display which chain this claimable fraction lives on, once results from multiple chains are displayed #1247. This should also be done for all tiles that are displayed.
> 
> ### Describe the solution you'd like
> 
> -
> 
> ### Describe alternatives you've considered
> 
> -

**Comment by Jipperism** [comment]
Closing as won't do, as SDK supports it but plasmic frontend won't.
