### ISSUE TITLE
[Ops] Create metadata for Gitcoin Climate round bundles

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#126]
Here is a sample bundle: https://grant-explorer.gitcoin.co/#/round/1/0x1b165fe4da6bc58ab8370ddc763d367d29f50ef0/0x42c5410440da06b29d782ee691783aad21d76b0de61c1034432f816af89aa57f-0x1b165fe4da6bc58ab8370ddc763d367d29f50ef0

**Comment by holkeb** [comment]
@ccerv1 what's the current status on how we handle bundles?

**Comment by ccerv1** [comment]
They are treated like any other "project". You can see an example [here](https://hypercerts.vercel.app/hypercerts/create?name=Bundle%3A%20Oceans%20%26%20Forests&description=%20%0A%F0%9F%91%89%20Who%20are%20we%3F%20%0A%20%0AWe%20are%20independent%20teams%20of%20conscious%20humans%2C%20climate%20tech%20entrepreneurs%2C%20computer%20scientists%2C%20and%20environmentalists%2C%20that%20are%20united%20by%20the%20mission%20to%20protect%20and%20restore%20the%20forests%20and%20oceans%20of%20our%20beloved%20planet%20Earth.%20We%20believe%20in%20a%20power%20of%20coordination%20so%20that%20collectively%20we%20can%20tackle%20the%20problem%20of%20biodiversity%20loss.%0A%20%0A%F0%9F%8C%B3%20Gainforest%3A%20A%20decentralized%20fund%20using%20artificial%20intelligence%20to%20measure%20and%20reward%20sustainable%20nature%20stewardship%20%40GainForestNow%3A%20%20GainForest%20is%20a%20non-profit%20developing%20impact%20evaluators%2C%20transparency%20dashboards%20and%20accountability%20protocols%20for%20nature-based%20assets%20using%20DeSci%2C%20artificial%20intelligence%20and%20web3.%20%0A%20%0A%F0%9F%8C%B3%20Vlinder%3A%20Restoration%20of%20degraded%20mangrove%20areas%2C%20%40vlinderclimate%3A%20Vlinder%20develops%20Verra-certified%20mangrove%20restoration%20projects%20to%20provide%20a%20variety%20of%20ecosystem%20services%2C%20climate%20change%20mitigation%2C%20economic%20considerations%2C%20and%20active%20participation%20of%20the%20local%20community%20in%20coastal%20areas.%0A%20%0A%F0%9F%8C%B3%20Salt%20Spring%20Solutions%20%E2%80%93%20Sequestering%20carbon%20via%20forest%20preservation%20%26%20regenerative%20agriculture%20%40SaltSpringSols%3A%20Our%20projects%20are%20systemic%20solutions%20to%20carbon%20sequestration%20on%20Salt%20Spring%20Island%2C%20BC%2C%20including%20managing%20a%20recently-purchased%2075%20acre%20forest%20as%20a%20community%20park%20to%20sequester%20carbon%20in%20perpetuity%2C%20and%20sequestering%20carbon%20through%20regenerative%20agriculture%20that%20also%20improves%20food%20security.%0A%20%0A%F0%9F%8C%B3Bloomeria%2C%20an%20organization%20to%20help%20communities%20safeguard%20green%20areas.%20%40bloomeria_dao%3A%20We%20help%20fund%20reforestation%20and%20conservation%20projects%2C%20we%20connect%20environmental%20organizations%20and%20companies%20willing%20to%20fund%20meaningful%20projects%20and%20we%20help%20companies%20prove%20their%20ESG%20commitments%20through%20a%20simplified%20view%20of%20their%20relevant%20on-chain%20actions%2C%20in%20a%20graphic%20and%20interactive%20way.%0A%20%0A%F0%9F%8C%B3Treegens%3A%20Evolving%20Degens%20into%20Treegens%2C%20%40thetreegens%3A%20We%E2%80%99re%20making%20Degens%20bullish%20on%20trees%20through%20the%20world%E2%80%99s%20most%20transparent%20%26%20rewarding%20tree%20planting.%20PPGL%20tokens%20are%20pegged%20to%20the%20cost%20of%20each%20mangrove%20tree%20we%20plant%20-%20%240.094.%20Our%20machine%20learning%20%2F%20AI%20tree%20counter%20then%20counts%20each%20tree%20from%20video%20footage%2C%20%26%20airdrops%20Non-Fungible%20Updates.%20To%20reward%20holders%2C%20we%E2%80%99re%20also%20tokenizing%20carbon%20forwards%20%26%20airdropping%20a%20portion%20of%20carbon%20forward%20revenue%20to%20the%20holders.%20%0A%20%0A%F0%9F%91%89%20What%20we%20do%3F%20%0A%20%0AOur%20bundle%20mission%20is%20to%20protect%20and%20restore%20forests%20and%20oceans%20with%20the%20support%20of%20science%20and%20technology.%20Received%20funding%20will%20be%20used%20to%3A%0A%0A%F0%9F%8C%B3%20support%20impact%20projects%20of%20our%20members%2C%20%0A%F0%9F%8C%B3%20improve%20collaboration%20between%20our%20teams%20via%20joint%20projects%2C%0A%F0%9F%8C%B3%20facilitate%20dMRV%20and%20verification%20of%20impact%20for%20greater%20accountability.%0A%20%0AOur%20bundle%20is%20organized%20as%20a%20DAO%20with%20a%20Treasury%20Safe%20managed%20by%20the%20simple%20majority%20of%20the%20bundle%20members.%20Projects%20will%20be%20nominated%20by%20the%20bundle%20members%20and%20voted%20on%20by%20the%20DAO.&externalLink=https%3A%2F%2Fvlinder.notion.site%2FOceans-Forests-f3c665c5162547eea874ec031f0cd8fc&logoUrl=ipfs%3A%2F%2Fbafybeibm3xi7hjhbiiw2ek3mq4havabxmuok6wf2eqnefi67mdhq7zxgtu&impactScopes%5B0%5D=all&impactTimeStart=2023-01-12&impactTimeEnd=indefinite&workScopes%5B0%5D=Bundle%3A%20Oceans%20%26%20Forests&workTimeStart=2022-09-22&workTimeEnd=2023-01-12&contributors%5B0%5D=0x48f2696FB6FAB7ac0956175b2E25B456E61B3FCf&allowlistUrl=ipfs%3A%2F%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%2FBundle-%20Oceans%20%26%20Forests.csv&rights%5B0%5D=public%20display&rights%5B1%5D=-transfers&fractions=100000).

**Comment by ccerv1** [comment]
We *could* implement it that way too ... maybe after we get the first projects onboarded, if team is feeling good, then we could try to unbundle the bundles.

**Comment by holkeb** [comment]
@ccerv1 what's the current state on this?

**Comment by ccerv1** [comment]
I have what I need, but this is a fairly high cost activity that I haven't had time for. I will try to get to it at the end of the week, assuming the other issues don't take too long

**Comment by ccerv1** [comment]
The bundles are working now. Here is an [example](https://testnet.hypercerts.org/app/create?name=Khalon%20Bridge&description=Distributed%20Solar%20for%20Web3%20Creators%20in%20Nigeria.%20Providing%20residential%20solar%20to%20emerging%20talent%20in%20the%20region%20to%20advance%20the%20digital%20economy%20in%20Africa.&externalLink=https%3A%2F%2Ftwitter.com%2FKhalonBridge&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreiejljnf6xf6kwcvh3wjef5xa3n7gscdumrmurmt4otkozbx5524r4&bannerUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreifn5av7znw7c6fgwq7g5k4be56tutofdgqiatwm2edekewvdf5xqm&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=Renewable%20Energy%2CEmerging%20Economies&workTimeStart=2022-09-22&workTimeEnd=2023-01-15&rights%5B0%5D=Public%20Display&allowlistUrl=https%3A%2F%2Fbafybeiatu732zyuvc5lyeuq5ncwsqolax7ue4mrsj32xfrpd3twowakj2u.ipfs.w3s.link%2Fallowlists%2FKhalon_Bridge.csv&backgroundColor=green&backgroundVectorArt=circles&metadataProperties=%5B%7B%22trait_type%22%3A%20%22Funding%20Platform%22%2C%20%22value%22%3A%20%22Gitcoin%20Grants%22%7D%2C%20%7B%22trait_type%22%3A%20%22Funding%20Round%22%2C%20%22value%22%3A%20%22Alpha%20Round%22%7D%2C%20%7B%22trait_type%22%3A%20%22Matching%20Pool%22%2C%20%22value%22%3A%20%22Climate%20Solutions%20%28Bundles%29%22%7D%5D&impactTimeStart=2022-09-22)

**Comment by holkeb** [comment]
Nice. Is the behavior such that if I contributed to the bundle, I receive a share of each project's hypercert?

**Comment by holkeb** [comment]
Yes, that is great.

Some people might notice that for other projects $1 resulted in 1 unit of one hypercerts and here $1 results in 1 unit of multiple hypercerts. Since 1 unit of a hypercert shouldn't be associated with $1 (instead the percentage of the hypercert should matter), this is good. And when people notice that, we can explain that this is intended.
