### ISSUE TITLE
[Infra] Upgrade to Defender 2.0

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#1278]
### What is it?

https://docs.openzeppelin.com/defender/v2/migration

The old Defender API is being deprecated on Jun 2024.
I’m hoping the changes don’t require too much work, but it seems like we have to do it…

CC @bitbeckers

**Comment by bitbeckers** [comment]
Thanks! With the indexer and API we're building, I think management of the upgrades in Defender could suffice 🤔

**Comment by bitbeckers** [comment]
Indexer will do full state indexing of allowlists, tokens and claims. The migration will be the upgrade flows of the Safes

**Comment by bitbeckers** [comment]
For reference: https://github.com/hypercerts-org/hypercerts-indexer/milestone/1
