### ISSUE TITLE
[SDK] Multichain support

### ISSUE THREAD

**Issue by Jipperism** [hypercerts-org/hypercerts#1286]
### What is it?

- [x] Deploy new graph instance under hypercerts-org
- [x] Update graph instance with new id format and properties
- [ ] Deploy new supabase staging instance
- [x] Setup plasmic branching (won't do)
- [x] Update SDK
- [x] Update defender scripts
- [x] Create supabase hypercerts update script
- [x] Create supabase hyperboards update script
- [x] Update frontend
- [x]  QA

**Comment by Jipperism** [comment]
Based on https://github.com/hypercerts-org/HIPs/discussions/2

**Comment by Jipperism** [comment]
https://github.com/hypercerts-org/hypercerts/pull/1301

**Comment by Jipperism** [comment]
https://github.com/hypercerts-org/hyperboards/pull/42

**Comment by Jipperism** [comment]
@bitbeckers do you feel multi chain support warrants a 2.0.0 release?

**Comment by bitbeckers** [comment]
Are there breaking changes that are not backwards compatible? @Jipperism ? If so, yes :)

**Comment by Jipperism** [comment]
@bitbeckers this is done.

As discussed, we didn't update the plasmic-based frontend yet. I agree with Holke that rebuilding might not be worth out time and effort.

Because of that, I haven't updated the hypercerts supabase instance yet, as that would break the frontend. I did add a sql scripts that we can run, as soon as we do, that will update all stored claim ids to reflect our new naming scheme.

I think the correct migration strategy would be to wait for our revamped frontend to roll out, and then move all relevant tables from hypercerts supabase over to the hypercerts-staging (the one from the api project). Run the update claim id script there, and then phase out the old hypercerts supabase instance.

We should probably create some tickets for that.

**Comment by Jipperism** [comment]
Done, moved last action point into https://github.com/hypercerts-org/hypercerts/issues/1305
