### ISSUE TITLE
[FE] Split and merge value on a hypercert they own

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#13]
- Each fraction can be splitted again
- Simple merge: All fractions are merged into one
- More complex merge (not necessary, but at some point we want this): Owner can choose which fractions to merge

This is how it looks in the current mock-up:

![Image](https://user-images.githubusercontent.com/103380539/225331942-ca21447b-b759-4613-bb22-7012998e9c8d.png)

**Comment by holkeb** [comment]
Current status: Holke to review frontend design

@ryscheng @bitbeckers is it in your sprint planning to have these features soon?

**Comment by ryscheng** [comment]
Just focusing on the SDK right now, haven't started planning the UX work yet. Do you have thoughts on how to specify the fraction unit values?

**Comment by holkeb** [comment]
I'll update the UI, i.e. adding the additional steps how the whole process would look like

**Comment by bitbeckers** [comment]
The methods for the client to split and merge are in the current SDK PR: #569 

https://github.com/hypercerts-org/hypercerts/blob/feat/sdk_methods_and_docs/sdk/src/client.ts

**Comment by Jipperism** [comment]
@holkeb did you ever get to updating those designs? And if so, where can I find them?

**Comment by bitbeckers** [comment]
Need to add event to split/merge so that the indexer can understand where the fraction have been merged into

**Comment by bitbeckers** [comment]
Updated instances on Goerli and Sepolia. The ABI hasn't changed, there's an additional event in the merge method

**Comment by benedictvscriticus** [comment]
It is used on a contract level for the marketplace. It does work on the for testnet UI, but it needs to be polished for mainnet.

Is at the bottom of a hypercert view on testnet. @holkeb should verify

**Comment by holkeb** [comment]
@Jipperism nothing happens when I click on split or merge for me: https://www.loom.com/share/8e45894fac89466ab70733df79b1b700?sid=1f8e878c-1327-4187-82b8-2126a3b15ce5

**Comment by benedictvscriticus** [comment]
@Jipperism thinks that works, except that the SDK throws an error and it did not integrate correctly. It should now properly propagate to the graph.
