### ISSUE TITLE
Error (5704): Type is not callable

### ISSUE THREAD

**Issue by positonic** [hypercerts-org/hypercerts#1308]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Smart Contracts

### To Reproduce

I am importing HypercertMinter.sol into my Foundry project

`import {HypercertMinter} from "hypercerts-contracts/HypercertMinter.sol";`

and running tests.

### Describe the Bug

When I try to run my tests I get this error:

```
Error: 
Compiler run failed:
Error (5704): Type is not callable
   --> /Users/james/code/hyperstaker-mono/lib/hypercerts/contracts/contracts/SemiFungible1155.sol:241:39:
    |
241 |     _beforeUnitTransfer(_msgSender(), owners(_tokenID), fromIDs, toIDs, values, "");
```

Owners is being called like a function, when it's actually a mapping.

I believe the line should be updated to be:

` _beforeUnitTransfer(_msgSender(), owners[_tokenID], fromIDs, toIDs, values, "");`

### Expected Behavior

The code should run without error

**Comment by bitbeckers** [comment]
I believe you're importing from the wrong dir. In the src dir the contract have the correct brackets: https://github.com/hypercerts-org/hypercerts/blob/7671d06762c929bc2890a31e5dc392f8a30065c6/contracts/src/protocol/SemiFungible1155.sol#L338

Not sure why it's in this that in the `contracts/contracts` file you're referring to but I created a ticket to remove them: #1309

**Comment by positonic** [comment]
It's working with the contracts in `hypercerts/contracts/src/protocol/` 
Thanks!
