### ISSUE TITLE
Hypercerts launch comms prep

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#131]
Spoke to Cortney De La Rosa, she offered to provide marketing support via Spaceport. What we need to give her is
1. Bullet points of what to highlight to a GA
2. a clear call-to-action

by Feb 20th to be included in the Feb 27th newsletter. I imagine this is good timing for when we launch at ETHDenver, we might want to make a wider announcement?

Channels include the Substack, PL social media, Lab Day highlights.

**Comment by holkeb** [comment]
Closing this as it is covered by other tasks
