### ISSUE TITLE
[MARKETPLACE] Investigate weird signing issue

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#1317]
### To Reproduce

Look into siging issue where a 3rd user can execute for user 1's ask, with user 2's bid. 

### Describe the Bug

.

### Expected Behavior

.

**Comment by Jipperism** [comment]
The initial message https://discord.com/channels/1140327804446183444/1163506245668458496/1218217688355180564

**Comment by Jipperism** [comment]
Steps to reproduce:

- Create fraction belonging to address A
- Sign a maker order using address B (expected to succeed, as simply signing the order is not something we are checking in the marketplace SDK. Possibly we can start checking for this, but it would be a UX improvement as we cannot prevent people from writing code that would allow them to sign the order using a different order themselves. The UI has been build to prevent this already)
- Register order with API. (expected to fail: this should not be possible as we don't want invalid orders to be registered with the API, or showing up in the marketplace UI. This ).
- Perform sale by calling contract with invalidly signed maker order (expected to fail, on a contract level).

**Comment by Jipperism** [comment]
@bitbeckers I'm failing to reproduce this.

I've bypassed a number of failsafes by running locally and created a makerorder for a token owned by address A, signed by address B, and registered it with our backend.

Fractional sale: It fails with a `HypercertSplitFractionError` for a fractional sale. [See Tenderly transaction](https://www.tdly.co/shared/simulation/762ea1a1-9dd0-43e0-a755-e690a11be1e9). [Example page with wrongly signed order](https://staging.hyperboards.org/hypercerts/11155111-0xa16dfb32eb140a6f3f2ac68f41dad8c7e83c4941-1020847100762815390390123822295304634368/).

Direct sale, with splitting upon order creation: errors out with `HypercertSplitFractionError` as well, as you can't split a fraction that isn't yours.

Direct sale, bypassing splitting by putting up a fraction directly: It fails in my browser with `ERC1155SafeTransferFromFail`. [See Tenderly simulation](https://dashboard.tenderly.co/jipperism/hypercerts/simulator/4653bd1a-3213-4f69-a5a9-653e2f0a9e08). [Example of wrongly signed order](https://staging.hyperboards.org/hypercerts/11155111-0xa16dfb32eb140a6f3f2ac68f41dad8c7e83c4941-144279723574477908508470833551069721657344/).

[Deployment that allows for creating and registering invalidly signed orders](https://hyperboards-git-bugfix-signing-iss-358171-hypercerts-foundation.vercel.app).

Would you agree we can close this for now, or do you want to investigate further?

**Comment by Jipperism** [comment]
[Diving into this transaction, as it was implied this was faulty](https://sepolia.etherscan.io/tx/0x12daf2eef5521336565bab47905e57fddead453c49a50a4a06265e77566cef55)

**Comment by bitbeckers** [comment]
FIxed and reported in #1320
