### ISSUE TITLE
Monitoring dashboard for on-chain activity

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#141]
We want a dashboard (possible via Dune + the Graph?) to monitor both usage statistics and anomaly detection.

Here are a few things we might want to monitor:
- Number of hypercerts minted (weekly / monthly / totals)
- Number of unique addresses interacting with the contract (weekly / monthly / totals)
- If anyone is calling methods that we don't expect (e.g. split / merge / transfer) - or generally which methods are being called

**Comment by ryscheng** [comment]
Courtesy of @ccerv1 
https://dune.com/queries/2475841/4072899

**Comment by ccerv1** [comment]
Update: moving to blocked while I wait for Dune to decode the contracts

**Comment by ccerv1** [comment]
Dune has finished decoding! Here's a quick demo: https://dune.com/queries/2489328

**Comment by ryscheng** [comment]
This is great, thanks for getting this started!
https://dune.com/hypercerts

Gonna close this out for now until we have specific things we want to add
