### ISSUE TITLE
Allow a user to upload or drag-n-drop an image into the create form

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#158]
Currently only allows a URL input

**Comment by marsrobertson** [comment]
This is a genuinely annoying speed bump.

I've picked up the logo + background from the Twitter profile.

I'm technical so I could always upload the file somewhere.

For a less technical user that could / would / will be a problem.

I've instantly noticed that the file upload feature is missing so definitely +1 to this one.

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
