### ISSUE TITLE
SSG the top N hypercert pages

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#161]
Currently, we have a /view page that will load the hypercert metadata client-side and populate the page.
This is terrible for SEO and user-perceived latencies.

We can fetch the top N hypercerts (e.g. by token price, or by transaction volume etc), and SSG those hypercert pages. 
Probably not that important to work on until after we decide on an explore UX, just noting for now.

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
