### ISSUE TITLE
Improve logging setup

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#186]

**Comment by bitbeckers** [comment]
What logging would this be exactly @ryscheng?

The SDK now uses Winston for logging and it could write files or emit events as well: https://github.com/hypercerts-org/hypercerts/blob/main/sdk/src/utils/logger.ts

Or are you thinking more about Grafana/Elastic search level log management?

**Comment by ryscheng** [comment]
Ya this is a pretty old issue at this point, maybe to update my thinking:
What if we exposed the winston instance from the SDK, so that the frontend can both
1. Use it for its own logging
2. Configure it (e.g. to their own elastic search setup)

In general, I was thinking the frontend needed to do much better logging in general for remote client debugging purposes.

**Comment by ryscheng** [comment]
Close enough
https://github.com/hypercerts-org/hypercerts/pull/750/files

Going to close for now
