### ISSUE TITLE
[docs] update glossary of terms

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#220]
Current (stale) version: https://hypercerts.vercel.app/docs/glossary

Would recommend the following steps:

- [x] @holkeb take a first pass 
- [x] @bitbeckers to take second pass and checks with functions in smart contracts
- [x] @holkeb to incorporate feedback and review with @ryscheng 
- [x] @ccerv1 to act as "fresh set of eyes" at end to confirm it makes sense

**Comment by holkeb** [comment]
@bitbeckers I updated the glossary from my perspective

- Can you check those terms that have relevance from your perspective?
- Can you add additional terms that should be defined there that I missed?

**Comment by bitbeckers** [comment]
In additions to changes in a PR I'll push we should look at this one:

<dt><strong>Hypercerts standard</strong></dt>
  <dd>A token and data standard for hypercerts. The token standard builds on the [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) token. The first 128 bits of the 256-bit token ID identifies the hypercert, the latter 128 bits identifies the specific fraction. The data standard requires that the following fields are defined on the metadata of the token: (1) set of contributors, (2) scope of work, (3) time of work, (4) scope of impact, (5) time of impact, (6) rights.</dd>
 
 
 From my perspective, the Hypercert standard is the declaration of the traits (scopes, contributors, rights, timeframes). On a contract level we try to seperate `Hypercerts` between and interface and our implementation. The standard doesn't build on 1155, but on our specification here: https://github.com/hypercerts-org/hypercerts/blob/main/contracts/src/interfaces/IHypercertToken.sol.
 
 Notions of bit-splitting are a design decision from our side, but if somebody want to mint hypercerts based on 721s that's fine as long as they also use our interface to support the hypercert capabilities like splitting and merging of values.

**Comment by bitbeckers** [comment]
PR with comments/changes: #282

**Comment by holkeb** [comment]
thanks @bitbeckers 

@ccerv1 ready for your fresh eyes

**Comment by ccerv1** [comment]
Looks good! Made some suggested edits in this PR #302 
@holkeb sent to you for review

**Comment by ccerv1** [comment]
@holkeb I merged my changes to the Docs, but please review. There are still placeholders for you under `splitting` and `merging`

**Comment by holkeb** [comment]
fyi we have two glossaries right now: One on the first level and one under "Implementation" I'll merge them and fill the placeholders.

And was the change of layout intentional? i.e. to have the table of content on the right side?

**Comment by holkeb** [comment]
Merged. 

@bitbeckers if it makes sense to add a technical explanation to the term merging and splitting, please add.

**Comment by ccerv1** [comment]
@holkeb re: formatting, I turned the terms into header3s. The previous formatting which used html tags was not rendering links properly. 

I wasn't intended to change the way the ToC shows the headers. This is probably an overall configuration setting, not something specific to the glossary markdown file

**Comment by holkeb** [comment]
ok, the ToC on the right is actually what I like about the new style :)

**Comment by ccerv1** [comment]
Just submitted some light copy-edits. I think this is good to go. Closing out. Team work = dream work!
