### ISSUE TITLE
[bug] mermaid diagram in docs doesn't work with dark theme

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#229]
bug see picture

I already tried to add different themes to the config

```
module.exports = {
  themeConfig: {
    mermaid: {
      theme: {light: 'neutral', dark: 'dark'},
    },
  },
};

```
but it seems as if that is overwritten.

explanation how it should work is here: https://docusaurus.io/docs/next/markdown-features/diagrams

![Image](https://user-images.githubusercontent.com/103380539/218089618-6186a042-788d-4974-9943-55ab2e5a3403.png)

**Comment by holkeb** [comment]
@jmoggr I saw that you had a branch reg cleaning up docusaurus... maybe this fits to what you are changing there?

**Comment by ryscheng** [comment]
Finally got around to fixing this
https://github.com/hypercerts-org/hypercerts/pull/903

Thanks for all the pointers in the description --- it was exactly what I needed to fix this
