### ISSUE TITLE
Docs: create ETH Denver runbook

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#230]
### What is the improvement or update you wish to see?

I would like to see a runbook modeled after the FIL Lisbon one

### Is there any context that might help us understand?

https://docs.google.com/document/d/1B62DszC8i-3VxyzZWUyRV43P5qwCFECaLVarb_nFZQU/edit?usp=sharing

**Comment by ccerv1** [comment]
@holkeb bumping this :)

**Comment by holkeb** [comment]
created here: https://docs.google.com/document/d/1sCM0wsu8pdsRGxLRaepEnILjypuiNmArf87wB6eUD7U/edit?usp=sharing

Can be reviewed and needs edits from NG team
