### ISSUE TITLE
feat: pass round-specific properties in the URL as a hidden properties

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#242]
### Describe the feature you'd like to request

1. The URL should accept an array of round-specific properties
2. These properties should also be captured as ERC1155 `properties` in the hypercert metadata
3. These properties should show up as attributes on OpenSea

### Describe the solution you'd like

ERC1155 Metadata should contain:
```
"properties": [
           {
                "trait_type": "Funding Platform", 
                "value": funding_platform
            },
            {
                "trait_type": "Funding Round", 
                "value": funding_round
            },
            {   
                "trait_type": "Matching Pool", 
                "value": matching_pool
            }
        ]
```

And appear on OpenSea like:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/42869436/218237092-477b8cff-6052-449d-909c-79d004725a85.png">

### Describe alternatives you've considered

Having a database or JSON that maps each project to a set of properties, eg, something like [this JSON blob](https://github.com/Network-Goods/hypercerts/blob/main/utils/canonical_project_list.json)

**Comment by ccerv1** [comment]
@ryscheng asked you to review if this is a good solution for Part 1 of this feature here: https://github.com/Network-Goods/hypercerts/pull/251

**Comment by ryscheng** [comment]
Thanks! I still need to get to this next, so let me test it. It seems reasonable, but wanna test first.

**Comment by ryscheng** [comment]
This should be compatible 
https://github.com/hypercerts-org/hypercerts/pull/270

**Comment by ccerv1** [comment]
This works. I tested it and things displayed properly on OpenSea
