### ISSUE TITLE
Mints don't look right on OpenSea

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#243]
### To Reproduce

https://hypercerts.vercel.app/app/create?name=Giveth&description=We%E2%80%99ve%20been%20making%20HUGE%20progress%21%20Giveth%20is%20Building%20the%20Future%20of%20Giving%20and%20we%20are%20hitting%20our%20milestones.%20We%20launched%20GIVpower%20and%20now%20are%20setting%20our%20eyes%20on%20NFTs%2C%20Quadratic%20Funding%20%26%20DAOifying%20nonprofits.%0A%20%0AGiveth.io%20is%20a%20radically%20open%20source%2C%20user-friendly%20donation%20platform%20that%20allows%20anyone%20to%20open%20crypto%20funding%20portals%20by%20creating%20projects%20for%20positive%20impact%2C%20with%20zero%20added%20fees%20and%20no%20intermediaries.%20Donors%20are%20also%20rewarded%20for%20giving%20to%20a%20wide%20range%20of%20projects%20that%20cover%20the%20field%20of%20for-good%20ventures%20including%20feeding%20the%20homeless%2C%20funding%20community%20currency%20projects%2C%20and%20saving%20the%20environment.%20Want%20to%20support%20public%20goods%3F%20It%27s%20all%20on%20Giveth.io%21%20Projects%20can%20be%20created%20in%20minutes%3B%20donors%20can%20make%20contributions%20in%20seconds.%20Currently%20Giveth.io%20is%20live%20on%20both%20Ethereum%20Mainnet%20and%20Gnosis%20Chain.%0A%0A100%25%20of%20every%20donation%20goes%20directly%20to%20the%20intended%20project%2C%20and%20we%20reward%20donors%20to%20verified%20projects%20with%20GIV.%20Learn%20more%20about%20our%20GIVbacks%20program%20here%3A%20https%3A%2F%2Fmedium.com%2Fgiveth%2Fwhat-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce%0A%0ANow%20at%20the%20start%20of%202023%2C%20we%20are%20delighted%20to%20announce%20some%20significant%20updates%20and%20future%20plans.%0A%0A%0AMAJOR%20UPDATES%20THIS%20QUARTER%0A%0A-%20We%20launched%20GIVpower%3A%20A%20tool%20for%20supporting%20and%20curating%20your%20favorite%20projects%20on%20Giveth.io%20while%20earning%20rewards.%20It%20uses%20web3%20incentives%20to%20rally%20support%20for%2C%20and%20drive%20more%20donations%20to%2C&externalLink=https%3A%2F%2Fgiveth.io%2F&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreiczgblqaa53byteenslgvjskag4cd47kq5bgmepp3uepprnuwsa3i&bannerUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafybeihndmwk6vxjrcxkd5a4dtsvcxauy3yhynji6jmnjh2e5owua5ruce&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=Giveth&workTimeStart=2022-09-22&workTimeEnd=2023-01-16&rights%5B0%5D=Public%20Display&contributors=0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd&allowlistUrl=https%3A%2F%2Fipfs.io%2Fipfs%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%252FGiveth.csv&backgroundColor=blue&backgroundVectorArt=octagonals

### Describe the Bug

https://testnets.opensea.io/assets/goerli/0x94a04ce2e537eaf2bdabd629de503797e7021e87/14632141777600353928925108119566033092608

### Expected Behavior

https://hypercerts.vercel.app/app/view?claimId=0x94a04ce2e537eaf2bdabd629de503797e7021e87-14632141777600353928925108119566033092608

**Comment by ccerv1** [comment]
This new contract is having this issue as well. See here: https://testnets.opensea.io/collection/hypercertminter-1

There is also an issue with the metadata, translation -- which I can fix: https://ipfs.io/ipfs/bafybeifzpeq22jjdiyzrt7zgtqtbkqsqx4tiozlz7ga2gacj7phl7csxdu

**Comment by ccerv1** [comment]
So I've run the following tests:

1. Minted a hypercert that I am on the allowlist for: [Web3Beach](https://hypercerts.pages.dev/app/create?name=Web3beach&workScopes=Web3beach&workTimeStart=2022-09-22&workTimeEnd=2023-01-15&impactScopes%5B0%5D=all&impactTimeStart=2022-09-22&impactTimeEnd=indefinite&contributors=web3beach.eth&rights%5B0%5D=Public%20Display&description=%2A%2A%20Your%20description%20was%20truncated%20because%20it%20exceeded%201000%20chars.%20%2A%2A%0A%2A%2A%20Please%20review%20and%20provide%20a%20new%20description%20for%20your%20hypercert.%20%2A%2A%0A%0AAccelerating%20web3%20education%20and%20adoption%20through%20social%20and%20environmental%20impact.%20%22Impact%20Onboarding%22%20creates%20onramps%20and%20upward%20mobility%20in%20web3%20for%20unbanked%2C%20disenfranchised%2C%20and%20historically%20overlooked%20communities.%20WEB3BEACH%20educates%2C%20coaches%20and%20empowers%20community%20leaders%20from%20diverse%20walks%20of%20life%20to%20use%20web3%20tools%20in%20efforts%20to%20improve%20living%20conditions%20for%20all.%20This%20includes%20environmental%20impact%2C%20health%20services%2C%20education%2C%20recreation%20and%20the%20ability%20to%20carry%20out%20their%20own%20public%20goods%20initiatives%20through%20our%20mini%20grants%20program.%20As%20a%20byproducts%2C%20we%27re%20creating%20circular%20crypto%20economies%20in%20our%20communities.%20%0A%0ASince%20GR15%3A%20We%27ve%20launched%20programs%20in%20five%20communities%20throughout%20Honduras%20and%20will%20continue%20to%20expand%20in%202023.%20We%27re%20also%20advising%20projects%20in%20other%20countries%20so%20they%20can%20adopt%20Impact%20Onboarding%20strategies%20in%20their%20region.%20%0A%0A%0A%F0%9F%94%8DTransparency%20Reports%3A%20We%20include%20expense%20reports%20with%20all%20of%20our%20events%20and%20currently%20working%20towards%20creating%20a%20standardized%20grantee%20reporting%20proc&externalLink=https%3A%2F%2Fweb3beach.io%2F&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreih4es2d5t6twhario7f2xopopz77f3pqpux46so4xgvjzhaos632y&bannerUrl=https%3A%2F%2Fnftstorage.link%2Fipfs%2Fbafybeid5g35scolfpaxznp3o6ysz6e2neirr3t5xw65pw567eptkbo7ijm%2FWeb3beach.png&allowlistUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2Fbafybeigyqkmmmm6o7wjsqxn5mzincl4vb2fm4vctpbgvdmuoced55c4yke%2FWeb3beach.csv&metadataProperties=%5B%7B%22trait_type%22%3A%20%22Funding%20Platform%22%2C%20%22value%22%3A%20%22Gitcoin%20Grants%22%7D%2C%20%7B%22trait_type%22%3A%20%22Funding%20Round%22%2C%20%22value%22%3A%20%22Alpha%20Round%22%7D%2C%20%7B%22trait_type%22%3A%20%22Matching%20Pool%22%2C%20%22value%22%3A%20%22Climate%20Solutions%22%7D%5D&backgroundColor=green&backgroundVectorArt=circles)
2. The mint appeared to. proceed fine. There were no errors. Here is the [Etherscan log](https://goerli.etherscan.io/tx/0x6395764106a52c345b2df30552e8ccb2b79353c296e7a997c1ad9b59545dc194#eventlog). 
3. After switching wallets, the hypercert didn't show up in my dashboard. I couldn't claim it. There was nothing on OpenSea either. 
4. The [metadata](https://ipfs.io/ipfs/bafybeid365kjti6n4o6df3jixbv6xysbnf6m7pb4wkijmywn5ogrgcrwli) appears fine. 
5. I was able to use the same metadata in the [hypercert test minter](https://goerli.etherscan.io/address/0xffb1fbff7a40ea441aeae8036812af116f593995#writeContract) and it proceed to mint and create an ERC1155 [visible on OpenSea](https://testnets.opensea.io/assets/goerli/0xffb1fbff7a40ea441aeae8036812af116f593995/65) with expected behaviors

**Comment by ryscheng** [comment]
Diagnosed.
Our URIs are not URIs, they're just CIDs right now.
We need to make sure we're using URIs everywhere, not CIDs (e.g. `ipfs://CIDCIDCID`)

**Comment by ryscheng** [comment]
Should be fixed here
https://github.com/hypercerts-org/hypercerts/pull/378

Still need to deploy and test

**Comment by ryscheng** [comment]
Ok, that was 1 of 2 bugs, here's the other.
The smart contract only returns a URI if you pass in a claimID.
If you pass in your tokenID (aka FractionID), you get nothing back.

Try it here
https://goerli.etherscan.io/address/0x822f17a9a5eecfd66dbaff7946a8071c265d1d07#readProxyContract

with 6125082604576892342340742933771827806209 (tokenID) and 6125082604576892342340742933771827806208 (claimID)

**Comment by ryscheng** [comment]
Fixed
https://testnets.opensea.io/assets/goerli/0x822f17a9a5eecfd66dbaff7946a8071c265d1d07/6125082604576892342340742933771827806209

**Comment by ryscheng** [comment]
Smart contract fix here
https://github.com/hypercerts-org/hypercerts/pull/386

**Comment by ccerv1** [comment]
Hurray!
