### ISSUE TITLE
Consent of other contributors

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#253]
In the create form we should make explicit that the addresses, names or pseudonyms will be public. Additionally, we might want to make people tick that they have consent from the other contributors

I think it needs to be more visible than just in the tooltip.

Option 1: Add something like "All addresses, names or pseudonyms will be public. Please ask other contributors for their permission before adding their details here." right below the title "list of contributors"

Option 2: Add something like "All addresses, names or pseudonyms will be public." right below the title "list of contributors" and add a checkbox with something like "I confirm that all listed contributors gave their permission to include their work in this hypercert."

@ccerv1 wdyt about these options?

**Comment by ccerv1** [comment]
I think Option 2 is probably the better path for the pilot. I'm moving this to "in review" since the contributors field has several issues we need to discuss today.

**Comment by ccerv1** [comment]
A gitcoin project that I just spoke with (https://spect.network/) also has a cool form UI that is multi-chain and can be used to gather contributor information. Should consider integrating directly or creating a bounty for them to make a PR.

**Comment by ccerv1** [comment]
@holkeb I have updated the language as per your recommendations and created a second checkbox.
@ryscheng can you please review the form logic so that it only creates if both boxes at the end are checked.

**Comment by ryscheng** [comment]
Done
https://github.com/hypercerts-org/hypercerts/pull/286
