### ISSUE TITLE
A hypercert that I create shows up as "claimed" in my dashboard even if I'm not on the allowlist

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#257]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

1. Create a project [[here](https://hypercerts.vercel.app/app/create?impactScopes%5B0%5D=all&impactTimeEnd=2023-02-13&workTimeStart=2023-02-13&workTimeEnd=2023-02-13&rights%5B0%5D=Public%20Display)]
2. Leave the allowlist field empty in the form
3. Mint the hypercert
4. Refresh / check your dashboard. It will appear as claimed.

### Describe the Bug

The hypercert appears to have been claimed by its creator

### Expected Behavior

I was expecting a separate contract interaction to claim the hypercert, even if it is a 1/1 with a default setting that it is only claimable by the creator.

Here's what it looks like for me (the creator):
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/42869436/218485396-325330a0-6a7c-4927-99ee-1946b13a97f6.png">

**Comment by ryscheng** [comment]
@ccerv1 Ya, right now minting without an allowlist just mints the fraction token and gives you 100%. So any hypercert for which you have a FractionToken shows up as claimed.

I'm not sure what the scope of work is here, I can see a couple options:
1. We auto-generate an allowlist for myself the creator, and then I have to go back and claim the 100% fraction in a separate interaction.
2. We have separate create forms for just minting the thing without an allowlist and a separate one for creating an allowlist. That makes it explicit and clear which is which.

I think the second option makes a lot more sense. Option 1 requires extra actions and gas costs for no real purpose.
Let's file an issue with the plan of action? Unless you want me to remove the "Claimed" chip in the UI, I'd propose we close this issue for now.

**Comment by ryscheng** [comment]
Or an option 3, which is adjust the form UX to toggle between
- Create an allowlist
- Transfer 100% to the creator.

In other words, just making it more clear.

**Comment by ccerv1** [comment]
> Or an option 3, which is adjust the form UX to toggle between 
> - Create an allowlist
> - Transfer 100% to the creator.

Ya, I think this is the better route to go. Basically we give creators different options for how they want to distribute hypercerts:
 - Allowlist
 - Create sets supply of fractions and takes 100%
 - Lite allowlist (eg, a split between a small number of people that can be done in browser)
I'll create a feature request for the backlog.
