### ISSUE TITLE
feat: tooltips should be easier for users to discover

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#261]
even if it's not the most beautiful I probably would add a little i-symbol after each heading... ideally not very bold and also in greay

![Image](https://user-images.githubusercontent.com/103380539/218502368-e3436137-5d91-4679-bcac-f1548eacfa40.png)

**Comment by ryscheng** [comment]
Just did this, since I was in the project making some other changes anyway
Published in Plasmic version 10.0.0
