### ISSUE TITLE
feat: time of impact should always be "indefinite" in the pilot

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#262]
projects shouldn't be able to change the end of the impact period

**Comment by holkeb** [comment]
@ccerv1 FYI

**Comment by ccerv1** [comment]
This is actually how it works. I actually think the better fix would be to remove it from the form builder for the pilot. (Or lock it completely)

**Comment by holkeb** [comment]
Currently for me it is the default, but I can change it (or is this not the right link?)

<img width="525" alt="image" src="https://user-images.githubusercontent.com/103380539/218521627-5f2ec755-8cf6-495a-9b6e-a3e0ec6695ef.png">

**Comment by ccerv1** [comment]
Ah, you're right -- just successfully minted one with a definite end date. Anyway, two options for now:
1. Remove from the front-end (better UX for early users)
2. Lock on the front-end (more consistent with future use cases)

**Comment by holkeb** [comment]
My ideal: put Impact Scope and Rights under a dropdown called "Advanced" and when you open it, it says that advanced features aren't available in this pilot

**Comment by ccerv1** [comment]
Flip on the disable property in plasmic

**Comment by ryscheng** [comment]
Adding an accordion which we can use for an "Advanced" collapsible

**Comment by ryscheng** [comment]
Whoops, had to fix a typo
https://github.com/hypercerts-org/hypercerts/pull/279

**Comment by ryscheng** [comment]
So what I ended up doing is hiding the "Impact Scope" section in the Advanced accordion so its not immediately obvious.
But impactTimeEnd is still configurable (not disabled).

What I'm worried about, is if you forget to add the query string parameter as a way to configure it, and then its disabled and I can't fix it without knowing the secret query string magic. 

By hiding it, but leaving it enabled, we leave open the possibility that we can fix it if someone passes a create URL that doesn't set it properly.

**Comment by ryscheng** [comment]
Note that this isnt an issue with the other disabled properties
- for impactTimeStart, that's just synced with workTimeStart, which is configurable
- for impactScopes, that's just hard-coded to be "all" all the time, so that's not an issue.

**Comment by ryscheng** [comment]
Gonna close this for now, but feel free to open if you don't like this solution
