### ISSUE TITLE
bug: logo isn't displayed correctly

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#264]
I used this logo: https://site-assets.plasmic.app/e1dddbd0e6a7104aee374d7b1b47a04a.svg

It looks fine in the create app: 

![Image](https://user-images.githubusercontent.com/103380539/218536812-e7c6993e-c103-4092-98cc-d7b005584d54.png)

But it doesn't show correctly later:
![Image](https://user-images.githubusercontent.com/103380539/218536675-79c96dcf-4008-4402-9e50-850c9d0f79f0.png)

**Comment by ryscheng** [comment]
@holkeb did you try again with a different image type (not SVG) or different image dimensions?

- If this only affects SVGs, I might just forbid SVG images
- If it's something else, I might P2 this unless it affects the generated URLs for the gitcoin round.

**Comment by holkeb** [comment]
@ryscheng SVGs: Yes, I created 3 more with SVG's and I got the bug consistently --> agree to forbid SVGs for now

PNGs and JPGs: The preview also looks different than the result. The preview is centered and scaled, while result is stretched.

**Preview with centered and scaled logo**
<img width="374" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/103380539/219005148-3d9823d4-4e67-4ff1-ae81-23625d217414.png">

**Result with stretched logo**
<img width="366" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/103380539/219005239-75719cab-0e11-4e5e-9e07-8fb18adbe354.png">

**Comment by ccerv1** [comment]
OK, I think I have figured this out.

First, I requested all the Gitcoin banner images and took their dimensions. The dimensions we want for a banner are 312 x 200 and for an icon 30 x 30.

Then, I started running some tests comparing create previews and actual hypercerts. _All_ of the actual hypercerts were compressed, even ones like Jolly Roger that need to be stretched to fill the banner size.

You can see these below:

| Project | Dimensions | Preview | Actual | Issues |
| ------- | ------------ | -------- | ------ | ------ |
| Jolly Roger | 249 x 83 | <img width="200" alt="image" src="https://user-images.githubusercontent.com/42869436/219260565-124ce0c2-6ffd-4409-949c-b5491bb6e062.png"> | <img width="200" alt="image" src="https://user-images.githubusercontent.com/42869436/219260631-12587662-da29-417b-9549-908f5d9dff37.png"> | width is compressed |
| Natives in Tech | 1500 x 500 | <img width="200" alt="image" src="https://user-images.githubusercontent.com/42869436/219261142-3a5422b1-559a-4baf-8459-75606362c4f5.png"> | <img width="200" alt="image" src="https://user-images.githubusercontent.com/42869436/219261394-1524335f-984d-4758-9946-0461c35f566d.png"> | width compressed + doesn't span banner |

Next, I looked through the actual dimensions and saw that all were supposed to have a 3:1 aspect ratio. This is when I realized that Natives in Tech had its width extended with transparent pixels (presumably by the Gitcoin app) to conform to their banner spec. 

To fix this, we will need to process the images as follows:

### Banners

1. Identify images that have transparent padding
2. For those **with** padding:
     - Crop out the transparent padding
     - Shrink/stretch to width of 312 pixels
     - Crop top and bottom to height of 200 pixels
3. For the rest:
     - Shrink/stretch to height of 200 pixels
     - Crop sides to width of 312 pixels

### Icons

1. Find the smaller dimension
2. Shrink/stretch on that dimension to 36 pixels
3. Crop on the other dimension to 36 pixels

**Comment by ccerv1** [comment]
Here is Natives in Tech [create page](https://hypercerts.pages.dev/app/create?name=Natives%20in%20Tech%20%28Cropped%29&description=%20%0A%F0%9D%95%86%F0%9D%95%A6%F0%9D%95%A3%20%F0%9D%95%84%F0%9D%95%9A%F0%9D%95%A4%F0%9D%95%A4%F0%9D%95%9A%F0%9D%95%A0%F0%9D%95%9F%0A%0ATo%20cultivate%20a%20tech%20ecosystem%20of%20Native%20technologists%20crafting%20free%20and%20open%20source%20technology%20for%20Native%20communities%0A%0A%20%0A%20%0A%F0%9D%95%8E%F0%9D%95%99%F0%9D%95%A0%20%F0%9D%95%8E%F0%9D%95%96%20%F0%9D%94%B8%F0%9D%95%A3%F0%9D%95%96%0A%0AA%20community%20of%20Native%2FIndigenous%20peoples%20and%20allies%20working%20to%20build%20open%20source%20projects%2C%20educate%20Native%20technologists%2C%20and%20onboard%20Natives%20into%20Web3%0A%0A%20%0A%20%0A%F0%9D%95%8E%F0%9D%95%99%F0%9D%95%92%F0%9D%95%A5%20%F0%9D%95%A8%F0%9D%95%96%20%F0%9D%95%92%F0%9D%95%A3%F0%9D%95%96%20%F0%9D%95%A8%F0%9D%95%A0%F0%9D%95%A3%F0%9D%95%9C%F0%9D%95%9A%F0%9D%95%9F%F0%9D%95%98%20%F0%9D%95%A0%F0%9D%95%9F%20%F0%9D%95%9A%F0%9D%95%9F%20%F0%9D%9F%9A%F0%9D%9F%98%F0%9D%9F%9A%F0%9D%9F%9B%0A%0A%F0%9F%94%B8%20Lakota%20AI%20Code%20Camp%0A%F0%9F%94%B82023%20Conference%0A%F0%9F%94%B8Native%20Job%20Board%0A%F0%9F%94%B8Organizing%20members%20around%20Regeneration%20projects%0A%F0%9F%94%B8Governance%20models%2C%20signaling%20and%20voting%20on%20proposals%0A%F0%9F%94%B8Crypto%20education%0A%F0%9F%94%B8Web3%20stack%20education%20for%20Web2%20developers%0A%0A%20%0A%20%0A%F0%9D%94%BD%F0%9D%95%A6%F0%9D%95%A5%F0%9D%95%A6%F0%9D%95%A3%F0%9D%95%96%20%E2%84%99%F0%9D%95%A3%F0%9D%95%A0%F0%9D%95%9B%F0%9D%95%96%F0%9D%95%94%F0%9D%95%A5%F0%9D%95%A4%0A%0A%F0%9F%94%B8Upgrade%20our%20open%20source%20project%2C%20%22Native-owned%20Businesses%22%20to%20use%20decentralized%20storage%0A%0A%F0%9F%94%B8Fund%20open%20source%20Web3%20projects%20built%20by%20Native%20technologists%20to%20support%3A%0A%0A%E2%97%BD%F0%9F%94%B9Regenerative%20agroforestry%0A%E2%97%BD%F0%9F%94%B9Media%20%2B%20education%20%28e.g.%20participatory%20media%2C%20nature%20documentaries%2C%20knowledge%20content%2C%20created%20and%20distributed%20by%20local%20communities%29%0A%E2%97%BD%F0%9F%94%B9Local%20natural%20research%20and%20biolearning%0A%E2%97%BD%F0%9F%94%B9Cost-savings%20on%20infrastructure%20like%20solar%20panels%0A%E2%97%BD%F0%9F%94%B9Land%20back%0A%E2%97%BD%F0%9F%94%B9Tribal%20Currencies&externalLink=https%3A%2F%2Fnativesintech.org&logoUrl=https%3A%2F%2Fbafkreiclw3m2rydevrnlrlayqtoyl37yfrtucxo2eq6vbgs6njes535gge.ipfs.nftstorage.link%2F&bannerUrl=https%3A%2F%2Fbafkreibrdgxqrfibicxssqrxvkthr3qsiz5lplteuzd6funbt6635uff5i.ipfs.nftstorage.link%2F&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=Natives%20in%20Tech&workTimeStart=2022-09-22&workTimeEnd=2023-01-10&rights%5B0%5D=Public%20Display&contributors=0x2DeE5D7e77A1212b21139Bc1d98B249DCc52055D&allowlistUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%252FNatives%2520in%2520Tech.csv&backgroundColor=green&backgroundVectorArt=circles&metadataProperties=%5B%7B%22trait_type%22%3A%20%22Funding%20Platform%22%2C%20%22value%22%3A%20%22Gitcoin%20Grants%22%7D%2C%20%7B%22trait_type%22%3A%20%22Funding%20Round%22%2C%20%22value%22%3A%20%22Alpha%20Round%22%7D%2C%20%7B%22trait_type%22%3A%20%22Matching%20Pool%22%2C%20%22value%22%3A%20%22Climate%20Solutions%22%7D%5D) with images cropped per the above methodology.

**Preview**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/42869436/219267603-bc3f67ce-be77-495f-8f03-e93c5ec9e5e1.png">

**Actual**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/42869436/219267731-7332e96e-6a97-49e2-ad2e-52732a119b75.png">

**Comment by ccerv1** [comment]
Update: I've created an image processing script and (temporarily) put new banner images on IPFS.

Will create separate issue for hosting assets on our CDN and updating the .gitignore
