### ISSUE TITLE
bug: contributors list is case sensitive

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#268]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Enter you wallet address in all lower case letters, then mint a hypercert using the same same wallet

### Describe the Bug

<img width="845" alt="image" src="https://user-images.githubusercontent.com/42869436/218801396-ed10e536-f6e0-4c20-9327-53f28bfba0fa.png">

### Expected Behavior

The contributors list should be deduped

**Comment by ryscheng** [comment]
https://github.com/hypercerts-org/hypercerts/pull/278

Fixed here

**Comment by ccerv1** [comment]
Reopening this -- it now appears that it won't match my connected wallet address to certs that I'm eligible to claim. 

Steps to reproduce:
- I just minted a hypercert that I was on the allowlist for (rotki)
- Previously, it would show up as claimable on my dashboard
- Now I'm no longer seeing it as claimable

If we rule-out that this is not a case sensitivity issue (eg, with Supabase) then we can open a separate issue 😭

**Comment by ryscheng** [comment]
sounds unrelated to the scope of this issue. I'll close this out for now and we can open a new one.
