### ISSUE TITLE
Fix encoding of hypercerts dimensions

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#274]
### To Reproduce

Create a hypercert with a contributor that is not specified by their wallet address and they will be omitted from the contributors dimension

### Describe the Bug

The issue is the formatting of contributors, shown here: https://github.com/hypercerts-org/hypercerts/blob/main/frontend/components/hypercert-create.tsx#L435

### Expected Behavior

1. we would allow names and pseudonyms = we don't remove contributors that are not Ethereum addresses
2. as we have the record of who minted the hypercert it would be ok if the minter isn't a contributor, e.g. we could mint a hypercert for other contributors

**Comment by ryscheng** [comment]
https://github.com/hypercerts-org/hypercerts/pull/278
