### ISSUE TITLE
bug: work scope that are comma-delimited should trim whitespace

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#281]
### To Reproduce

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/42869436/218929952-ebd52205-a17c-47f3-94cf-47e75339659e.png">

### Describe the Bug

The work scope tag has padded spaces before the text

### Expected Behavior

The text should have whitespace trimmed on both sides

**Comment by ryscheng** [comment]
This was already addressed in the form creation (e.g. when computing metadata)
but it's a different codepath when generating the image. Thanks for catching.
Fixed in Plasmic version 11.0.1
