### ISSUE TITLE
Docs: FAQs

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#301]
### What is the improvement or update you wish to see?

An FAQs page easily discoverable from the docs

### Is there any context that might help us understand?

Here is the [Notion-based FAQs stub](https://www.notion.so/network-goods/FAQs-2e57ba1b1d8741188e2a28f21a6209d0)

- What token standard do Hypercerts utilize?
    
    [[ERC 1155](https://eips.ethereum.org/EIPS/eip-1155)](https://eips.ethereum.org/EIPS/eip-1155) (a semi-fungible token)
    
- What chain(s) is hypercerts running on?
- Are hypercerts the same as impact evaluations?
- How is a hypercert different than a POAP, Impact NFT, … ?
    - Regular NFT
    - POAP
- What are the required fields to generate a hypercert?
- How is the allowlist generated?
- Why am I not on the allowlist even though I contributed to the project?
- How do I create a hypercert?
- How do I claim a hypercert? Can I claim all of the ones I’m eligible for at once?
- How do I burn a hypercert?
- How much gas will it cost to create or claim a hypercert?
- What if the project is using a multisig?
- What can I do with my hypercert?
- Where can I purchase a hypercert?
- Have the smart contracts been audited?
- Can I split a hypercert?
- Can I merge hypercerts?

**Comment by ccerv1** [comment]
Added a V1, so will close this for now.

The docs aren't visible yet on the site, but you can view the FAQ page directly in the docs directory

**Comment by holkeb** [comment]
@ccerv1 thanks. The sidebar isn't automatic anymore, it's managed in sidebars.js. There are some answers (e.g. it is deployed on Optimism) that aren't true YET. So, I guess we can just add it to the sidebar once those are true.
