### ISSUE TITLE
SDK: mintHypercertToken not using the correct provider from Wagmi

### ISSUE THREAD

**Issue by carlbarrdahl** [hypercerts-org/hypercerts#306]
### To Reproduce

https://github.com/carlbarrdahl/gratitude.party/pull/1

### Describe the Bug

After uploading the metadata and calling the contract, I get this error:
```
Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.7.0)
```

This is because: `ethers.getDefaultProvider()` returns a FallbackProvider:

https://github.com/hypercerts-org/hypercerts/blob/f29438afcb75e9acab20074aa31c3093e6318505/sdk/src/utils/provider.ts#L3-L4

https://github.com/hypercerts-org/hypercerts/blob/f29438afcb75e9acab20074aa31c3093e6318505/sdk/src/minting.ts#L8-L11

It would be great if it was possible to call `mintHypercertToken` with a signer in the parameters:

```tsx
export const useMintHypercert = (
  onSuccess: (data?: ContractTransaction) => void
) => {
  const { data: signer } = useSigner();
  return useMutation(async (claimData: HypercertMetadata) =>
    mintHypercertToken([claimData, 1, transferRestrictions.AllowAll], signer).then(
      onSuccess
    )
  );
};
```

### Expected Behavior

- Connect Wallet with Wagmi (or RainbowKit)
- Call mintHypercertToken
- Metadata validated and uploaded
- ethers Contract called with the correct signer from the connected wallet

**Comment by bitbeckers** [comment]
@ryscheng @ryscheng this should be solved with the client setup in the latest SDK. 

* You can pass in your own signer/provider
* If there's none given, the client will be in readonly mode

When we release 0.1.0 this issue can be kicked to validate the fix.

**Comment by bitbeckers** [comment]
@carlbarrdahl same here. We released and updated SDK and since you are THE early adopter, maybe you want to give it a spin? 

https://www.npmjs.com/package/@hypercerts-org/sdk

**Comment by bitbeckers** [comment]
@ryscheng with https://github.com/hypercerts-org/hypercerts/pull/856 I'm pretty sure we are using it :) Can we close this issue?

**Comment by ryscheng** [comment]
sgtm

**Comment by carlbarrdahl** [comment]
> @carlbarrdahl same here. We released and updated SDK and since you are THE early adopter, maybe you want to give it a spin?
> 
> https://www.npmjs.com/package/@hypercerts-org/sdk

Great work! :+1:
