### ISSUE TITLE
feat: show 3 extra digits only if necessary

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#309]
The three significant figures on the percentage look weird to me.

![Image](https://user-images.githubusercontent.com/103380539/219655118-80630c74-c651-4380-9a19-78d0e365e065.png)

Instead
1. can we generally show only two digits?
2. can we show three significant figures if it is less than 0.01%?

In addition
3. can we get rid of the hypercerts supply on the right?
4. add the supply underneath the percentage

This is how I would like it:

![Image](https://user-images.githubusercontent.com/103380539/219657636-f48c754c-8328-4460-b181-d9d2f7d2d5e0.png)

I know how to implement most of this, but not step 2.

**Comment by holkeb** [comment]
@ccerv1 can you do this?

**Comment by ccerv1** [comment]
I can look into it. Let's discuss on our UI chat today.

**Comment by ccerv1** [comment]
@ryscheng ooooooh I love being able to edit the JavaScript function directly in Plasmic!!!

@holkeb i think it should be fixed

**Comment by ryscheng** [comment]
Thanks for jumping on this!
