### ISSUE TITLE
Selling unclaimed hypercerts from the project after Gitcoin round

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#31]

**Comment by holkeb** [comment]
Technically any funder can claim their fractions at any point in time. So, the unclaimed fractions can not be sold. ( @ryscheng  please correct me, if I'm wrong and reopen the issue)

So, this is really about selling the fractions that the project owns itself, which is captured in https://github.com/hypercerts-org/hypercerts/issues/440

**Comment by ryscheng** [comment]
I think that's right. Thanks for following up!
