### ISSUE TITLE
Cosmetics: Ability to increase the size of the description field

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#310]
In the create field, it would be great if the user could increase the size of the description field, i.e. drag the lower right corner.

This is how it works on OpenSea

![Image](https://user-images.githubusercontent.com/103380539/219659283-f4842db0-1342-42c6-919f-d193b6b1707d.png)

**Comment by ryscheng** [comment]
https://github.com/hypercerts-org/hypercerts/pull/465

This adds new behavior so that the description field can autosize (grow) as you type, and also lets you bound how small/big it can be with new props exposed in Plasmic Studio
