### ISSUE TITLE
[FE][Bug] Jumping to an error message

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#311]
If I make a mistake in the beginning of the form and then click on the "create" button on the bottom, I don't see any error message and it seems like something is broken.

Possible solutions:
- The page jumps up to the error message
- Another message appear right next to the create button "Please see the error messages above."

**Comment by bitbeckers** [comment]
Closing in facor of refactor epic https://github.com/hypercerts-org/HIPs/discussions/5
