### ISSUE TITLE
cosmetics: there is a slight delay after clicking the "create" button

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#312]
After I click "create" on the create form, there is a small delay before anything else happens and I'm not sure if something is happening or if it is broken.

Possible solutions:
- after clicking the button changes
- there is some intermediate waiting symbol that isn't connected to the slower processes

**Comment by ryscheng** [comment]
Oh ya this has been annoying, we don't show the modal until after we generate the image, but that takes time. We should probably just add that as a step in the modal.

**Comment by holkeb** [comment]
closing this as it is a duplicate: see https://github.com/hypercerts-org/hypercerts/issues/393
