### ISSUE TITLE
bug: columns on mobile view become rows

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#328]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Go to Plasmic and view the mobile only layout

<img width="383" alt="image" src="https://user-images.githubusercontent.com/42869436/219979541-f0b77552-8d8a-42e9-b70c-ce6209b04775.png">

### Describe the Bug

The "Usage Rights" column and the Owners' "Shares" column appear as new rows, instead of columns

### Expected Behavior

These fields should remain in columnar format, similar to how it looks on desktop, eg

<img width="421" alt="image" src="https://user-images.githubusercontent.com/42869436/219979687-390c5780-9074-48a4-9528-4a7df3683e26.png">

**Comment by ryscheng** [comment]
Fixed in Plasmic Dapp v12.0.8
