### ISSUE TITLE
feat: Royalty fees from hypercert secondary market trading back to the project

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#33]

**Comment by marsrobertson** [comment]
**QUESTION:** Is there a royalty fee?

Is it desirable?

Is it sustainable?

I think that Hypercerts Foundation can go meta (eat own dogfood) and issue hypercert for the impactful work.

**TBD TBC**

**Comment by bitbeckers** [comment]
Not being worked on, @holkexyz we need to determine how to handle this for voicedeck
