### ISSUE TITLE
Can users delete other user's metadata?

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#344]
### To Reproduce

1. Get the NFT.storage key from the application
2. Call delete using the SDK

### Describe the Bug

Users shouldn't be able to delete arbitrary NFT metadata. Because NFT.storage keys don't specify permissions, they may be able to take any action allowed by the API. And the client-side library does allow for deletes. We should look into how other projects handle this. Maybe we'll need to handle uploads through a proxy that stores the key instead

### Expected Behavior

Users can only upload NFTs, not delete.

**Comment by bitbeckers** [comment]
Currently, we upload all IPFS data via the web3up APIs and only expose a POST endpoint. So closing this issue since it's not an attack vector anymore.

Feel free to open this again if I'm mistaken
