### ISSUE TITLE
Support simple filtering on hypercerts properties in the opening dashboard

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#35]

**Comment by ccerv1** [comment]
A user should be able to filter hypercerts based on some or all of the following parameters:
- Owned
- Claimable
- Work timeframe is past (pure retro), present, or future (pure prospective)
- Properties (eg, Gitcoin, OSS, etc)

Current sketch in Figma

![Image](https://user-images.githubusercontent.com/42869436/215791776-70d70f11-0565-4ad9-86e4-74091ff6e40f.png)

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
