### ISSUE TITLE
Deprecate hypercerts-protocol npm package

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#350]
### What is it?

Can do local import into SDK now

**Comment by ryscheng** [comment]
Depends on https://github.com/hypercerts-org/hypercerts/issues/362

**Comment by bitbeckers** [comment]
Done: 
Protocol: https://www.npmjs.com/package/@hypercerts-org/hypercerts-protocol
SDK: https://www.npmjs.com/package/@hypercerts-org/hypercerts-sdk
