### ISSUE TITLE
[FE]  A user should be able to create a compliant allowlist through our app

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#356]
### Describe the feature you'd like to request

an interface that makes it easy for users to create or upload a compliant allowlist

### Describe the solution you'd like

ideally a pop up or modal directly from the create page, which makes it easy to input wallet addresses and apply global decisions like mint price and number of fractions (but also fine tune these)

### Describe alternatives you've considered

we could create a google sheet that users can copy, edit, download as csv, and upload

**Comment by ccerv1** [comment]
You basically just solved this [here](https://github.com/bitbeckers/hypercert-allowlist-generator)

**Comment by bitbeckers** [comment]
We probably need to work on a few things based on [that codebase](https://github.com/bitbeckers/hypercert-allowlist-generator):
- Handling longer lists (and I don't think a Modal will work with for instance long lists)
- Tiny UI polishing for state
- Besides that we're good to go?

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
