### ISSUE TITLE
[FE] Allow users to switch networks within the Dapp

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#358]
### Describe the feature you'd like to request

Right now any particular build is hardcoded to use a particular network and contract address. That means the only way to support different networks is to deploy to different subdomains.

### Describe the solution you'd like

It would be nice to be able to select the network from within the Dapp, (i.e. as a dropdown).

Might be okay to have 2 deployments
- staging.hypercerts.org lets you pick between different testnets like Goerli)
- hypercerts.org lets you pick between different mainnets (like Optimism)

### Describe alternatives you've considered

Just deploy to different subdomains (e.g. optimism.hypercerts.org, polygon.hypercerts.org, etc)
- This is less than ideal for SEO

**Comment by ryscheng** [comment]
@holkeb This would be nice to have, esp as we start deploying on https://github.com/hypercerts-org/hypercerts/issues/885 and https://github.com/hypercerts-org/hypercerts/issues/682

The current configuration requires that we deploy totally separate Dapps to handle every network, which is bulky and requires wrangling more build systems

**Comment by Jipperism** [comment]
Plan of attack for completing this feature: @bitbeckers 

- Create mechanism to enable/disable features based on active network (for example: marketplace should not be available on mainnet)
- Enable chains in chain selector (prod: optimism, testnet: goerli & sepolia)
- Create singular supabase table for `allowlistCache` and `blueprint` with a column for chainId (number).
- Update supabase query providers in plasmic to use chainId when querying changed tables
- Update defender scripts to write to renamed tables
- Double check if client reinitializes after changing chain id, and uses correct contracts + graph endpoints

**Comment by bitbeckers** [comment]
Related to #477 @Jipperism

**Comment by Jipperism** [comment]
@bitbeckers I think this is as good as done, did some testing and I think we are ready to deploy. Checklist:

- [ ] Optional: some more testing
- [ ] Consider whether we want to expose the config the way i've done it now (I just made it a public property of the client)
- [ ] Configure env vars (remove overrides for chain id, contract address and graph url) in deployments
- [ ] Release new version of sdk and update dependencies in frontend etc
- [ ] Test `TestnetOnly` component in plasmic once deployed to develop/main
- [ ] Publish new plasmic version

**Comment by bitbeckers** [comment]
Cool! @Jipperism let's book a moment to so that we can roll out and verify because it sounds like the deployments could break and we need time to fix that. Some things like removing tables can be done afterwards right?
