### ISSUE TITLE
Create new dashboard copy and potential features

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#374]
New copy and ideas here: https://www.notion.so/hypercerts/Dashboard-copy-f454b5e758e94ddd8634669ae78f0774?pvs=4

**Comment by ccerv1** [comment]
@ryscheng I've implemented the design changes.

 I just need your help with two things:

(1) create a dynamic value for the denominator of the "claimed / allowlisted to claim" stat

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/42869436/222008488-a86ea156-3784-434e-a83c-ffa7ba9cf225.png">

(2) create a dynamic value for the number of hypercerts created stat

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/42869436/222008616-b361d6f5-4c3f-4e69-9a1d-c7d9d1e9a306.png">

**Comment by ryscheng** [comment]
Done in Plasmic Hypercerts Dapp v15.0.0

Waiting to deploy until after we deploy SDK fixes.
