### ISSUE TITLE
I'm not able to claim more than one fraction

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#391]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Smart Contracts, Frontend Dapp

### To Reproduce

Mint a hypercert that you are allowlisted for and have more than 1 unit assigned in the allowlist. 
Then claim it. 
It will only assign 1 token to you, even though you should have a larger fraction. 

### Describe the Bug

[Here](https://hypercerts.pages.dev/app/view?claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-6465364971497830805804117541203596017664) is a hypercert that I own. 

It says I own 1 / 1388 units. 

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/42869436/221155925-552e4b1d-6ece-43c1-b3cd-3c1a4d89da3c.png">

However, one can also see on [the allowlist](https://cloudflare-ipfs.com/ipfs/bafybeigyqkmmmm6o7wjsqxn5mzincl4vb2fm4vctpbgvdmuoced55c4yke/Bloom_Network.csv) that I should have 9 fractions, eg, 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/42869436/221157642-456cf839-5e47-4946-b194-76750249395d.png">

### Expected Behavior

The claim should distribute all tokens that I am allowlisted for, not just one

**Comment by ryscheng** [comment]
Thanks for linking to the hypercert, made it a lot easier to debug.
Looks like it minted the right thing, but it's displaying the wrong thing. Looking into the Plasmic expression now

<img width="537" alt="Screen Shot 2023-02-26 at 03 33 45" src="https://user-images.githubusercontent.com/566890/221408100-abf5b37b-e20b-4cad-a945-edae7695ea0d.png">

**Comment by ryscheng** [comment]
So the problem is that the expression just counts how many FractionTokens you own, not how many total units you have.
This is the original:
```
`${$ctx.hypercertData.claimTokens.filter(t => t.owner === $ctx.DappContext.myAddress.toLowerCase()).length} / ${$ctx.hypercertData.claim.totalUnits} units`
```

This is the fix:
```
`${$ctx.hypercertData.claimTokens.filter(t => t.owner === $ctx.DappContext.myAddress.toLowerCase()).map(t => Math.round(t.units)).reduce((a, c) => a + c,0)} / ${$ctx.hypercertData.claim.totalUnits} units`
```

**Comment by ccerv1** [comment]
Amazing. Great to see this working correctly now!
