### ISSUE TITLE
[Outreach] Prepare comms/copy for Gitcoin projects to create hypercerts

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#40]

**Comment by holkeb** [comment]
just dropping a point here, such that we don't forget: We need to make clear to the projects that the hypercert is retrospective and that this hypercert can't be changed to a time of work in the future. Ideally they would adjust the description and name based on that.

**Comment by ccerv1** [comment]
@holkeb bumping this for you to tackle first thing Monday.

First, have a look:
- [ ] Latest version of the blog plot [here](https://docs.google.com/document/d/12beN219aVaIwmd44UMbR_uYVZjmRDv9MdvkBBrMGsH8/edit?usp=sharing)
- [ ] Latest Gitcoin instructions in the [docs](https://hypercerts.org/docs/minting-guide/gitcoin-round)

Then:
- [ ] Review/update the message we send projects with the custom minting URL
- [ ] Prepare a short blurb for Gitcoin to email projects with the TL;DR version of what they need to do to create a hypercert

**Comment by holkeb** [comment]
Reg the messages we send to the projects. The open tasks are:

- [ ]  update links when they are final
- [ ]  update dates & times for office hours

**Comment by holkeb** [comment]
email from Gitcoin to projects here: https://docs.google.com/document/d/1Bfbl3ZzLfQ9CnDwY7TCGaO5DgYdZAP-F-tpcX-hdVtM/edit?usp=sharing

it is similar to the twitter DM

**Comment by ccerv1** [comment]
Plan for the week:

- [ ] Finalize blog post and messaging to projects (Monday)
- [ ] Blog post and messages go out to projects (Tuesday)
- [ ] Twitter space (Wednesday)
- [ ] Office hours (Wed-Fri) - as needed
- [ ] Claiming outreach (Thurs-Fri -- Monday at latest)

**Comment by holkeb** [comment]
@ccerv1 have you reviewed the email from Gitcoin to the projects? (see above). The only link that is missing now is the one to the blogpost

Additionally, we need to create:

- [ ] a tweet/series of tweets from the hypercerts foundation account
- [ ] an announcement on the website with a link to the gitcoin blogpost

Let's work on those here: https://docs.google.com/document/d/11qhhtlE6J3pFjn1dwN9rC__9ZZS547JI/edit?usp=sharing&ouid=105716333971299182227&rtpof=true&sd=true

**Comment by holkeb** [comment]
- Added a banner on a duplicate landing page for now:


![Image](https://user-images.githubusercontent.com/103380539/228257618-c160adbf-9be4-441b-868b-ba6cae15d7c0.png)
