### ISSUE TITLE
add styling support to MuiTooltips

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#409]
### What is it?

I'd like to improve the tooltip styling at the very least to a large font / different bg color

<img width="690" alt="image" src="https://user-images.githubusercontent.com/42869436/221573197-10a292d7-8125-4509-a33d-e130273862aa.png">

Hopefully this is straightforward as per [this page](https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component)

**Comment by ryscheng** [comment]
Adding here
https://github.com/hypercerts-org/hypercerts/pull/567

**Comment by ryscheng** [comment]
Fixing sentry config to show sourcemaps here
https://github.com/hypercerts-org/hypercerts/pull/568

**Comment by ryscheng** [comment]
Check out the tooltip by Project Name in the create form for an example
