### ISSUE TITLE
[IE] At least one impact evaluation is conducted for all participating projects

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#41]

**Comment by ccerv1** [comment]
- [ ] Evaluate Twitter activity for all Gitcoin projects 
- [ ] Evaluate Github activity for all OSS + ETH Infra projects

**Comment by ccerv1** [comment]
Methodology here: https://mirror.xyz/cerv1.eth/yBtw568KrA9SVvITGq2E6eQb14UdZYeb1lhimFW8qV4

**Comment by marsrobertson** [comment]
Here is an alternative methodology: https://gitcoinreviews.co/

An example project: https://gitcoinreviews.co/grants/4912

<img width="774" alt="image" src="https://user-images.githubusercontent.com/44369284/224505950-8e064c53-6728-4502-87aa-d5009a617955.png">

Self-assessment report: https://bafybeifqhgxolhd4jivaw4gan7brczofjotxpuisxbhcaax5jenme7cy54.ipfs.w3s.link/GR14%20GitcoinReviews.co%20Self-Assessment%20Report.pdf
