### ISSUE TITLE
Mint was successful but nothing to claim on dashboard

### ISSUE THREAD

**Issue by noahyeh** [hypercerts-org/hypercerts#414]
### To Reproduce

https://user-images.githubusercontent.com/877111/221793798-e3ef3646-d801-4858-afa7-2c20f34cd7b8.mp4

Through https://hypercerts.pages.dev/app/create
with Goerli testnet
Mint was successful but nothing to claim on dashboard

### Describe the Bug

Mint was successful but nothing to claim on dashboard

### Expected Behavior

I expected something to show on dashboard for wallets on allowlist to claim

**Comment by noahyeh** [comment]
Hi, yes of course, we tried a couple times, the first allowlist file we submitted was this
https://ipfs.io/ipfs/QmQYMShRRTCbNvMBd9onEgRbxmQB4FqiZiYXXXNM2NN8PR/123.csv

Later we were trying with only a single wallet address

**Comment by noahyeh** [comment]
Wonderful thank you guys

**Comment by ccerv1** [comment]
I'm trying to reproduce the bug with this minting [url](https://testnet.hypercerts.org/app/create?name=Noah%27s%20TEST&description=Replicating%20the%20test%20%5Bhere%5D%28https%3A%2F%2Fgithub.com%2Fhypercerts-org%2Fhypercerts%2Fissues%2F414%29&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafybeig7yx3cm7ljn2jcrufznx2l3qsnguwoveifqv6msa3nec6jp76p6y&bannerUrl=https%3A%2F%2Fbafybeigl5mup4ltahdv3v7x23oe6nrlqdzwmlrcfeawkqhovndwka4mawq.ipfs.w3s.link%2Fimages%2FLighthouse.png&impactScopes%5B0%5D=all&impactTimeEnd=2023-03-02&workScopes=testing&workTimeStart=2023-03-02&workTimeEnd=2023-03-02&rights%5B0%5D=Public%20Display&contributors=test&allowlistUrl=https%3A%2F%2Fbafkreibbrz6rjl2gqhz5pvhjz7qlprhjpj3edb6ztfqm24i4z5l6clr5fu.ipfs.nftstorage.link%2F&agreeContributorsConsent=true&agreeTermsConditions=true)

Here is the allowlist [link](https://bafkreibbrz6rjl2gqhz5pvhjz7qlprhjpj3edb6ztfqm24i4z5l6clr5fu.ipfs.nftstorage.link/):
```
index,address,price,fractions
0,0x20326E144532f17f76AcA759e61E19aF20A58ef3,0.0,100
1,0x15c7281842A45465B4cbb8F89111d99e36e5bab8,0.0,50
2,0x1cca19b823afa773b09708d94d2ee6ff96c60057,0.0,40
3,0xab51ad23d222fd0afb4e29f3244402af9aa3c420,0.0,30
4,0xd1444046e3987e44c8757a2400e9f8b7539f86b6,0.0,20
5,0xC54861e4161E02354957A1a2F95303489CD60833,0.0,1

```

Results:

✅  Minting worked 
<img height="200" alt="image" src="https://user-images.githubusercontent.com/42869436/222505296-4f052381-7a76-4023-87af-83bfa8efcc84.png">

❌  Claiming did not work
<img height="200" alt="image" src="https://user-images.githubusercontent.com/42869436/222505774-77bdf1c9-9068-4028-9f60-0fe55a982412.png">

***

I'm going to add this to one of the tests over here: #421

**Comment by ryscheng** [comment]
I used the exact minting URL that you used, except I changed the allowlist to add myself as one of the line items.
I was able to both mint the allowlist and claim it, see here
https://testnet.hypercerts.org/app/view?claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-30625413022884461711703714668859139031040

I'm not sure what changed, but I might close out since I cannot reproduce. Maybe this PR fixed it inadvertantly?
https://github.com/hypercerts-org/hypercerts/pull/466

Please re-open if you're still having issues? CC @ccerv1 @noahyeh
