### ISSUE TITLE
web3.storage may not retrieve assets on certain types of internet connections

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#416]
### To Reproduce

Try accessing any of our assets stored on web3.storage

You get this error:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/42869436/222010167-537ce5b2-4929-44d5-81e7-fa96fb472830.png">

Here are my internet settings:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/42869436/222010359-9c4b3813-f27a-4dcf-8115-7ff8b791a4ba.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/42869436/222010418-5d6ef442-e185-4115-877a-53fe821a9432.png">

### Describe the Bug

web3.storage fails to retrieve the assets, preventing the hypercert from being created

### Expected Behavior

if the assets can't be retrieved, there should be some kind of redundancy or option given to the user to troubleshoot. See also #415

**Comment by ryscheng** [comment]
Not sure if this is actionable. Can we just close this in favor of 
https://github.com/hypercerts-org/hypercerts/issues/415
?
