### ISSUE TITLE
a creator can use AI to generate their hypercert artwork

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#419]
### Describe the feature you'd like to request

The data provided in the hypercert create fields power a unique AI-generated piece of art

### Describe the solution you'd like

Stable diffusion on Bacalhau:
https://docs.bacalhau.org/examples/model-inference/stable-diffusion-gpu/

### Describe alternatives you've considered

na

**Comment by marsrobertson** [comment]
Bells and whistles / feature creep.

https://en.wiktionary.org/wiki/Zawinski%27s_law

> Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can.

I like the idea but it seems rather excessive... 😇

_(especially that some freeloaders will abuse API credits to generate their images to be used elsewhere)_

**Comment by ccerv1** [comment]
We actually made this yesterday for a hackathon! Closing out now :)
