### ISSUE TITLE
"already claimed" error prevents user from claiming again

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#420]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

1. Create a hypercert that you are allowlisted for
2. Claim the hypercert
3. Then create another version of the same hypercert (that you are allowlisted for)
4. Try to claim the hypercert

### Describe the Bug

the bug displays an "already claimed" error and the contract interaction modal gets stuck on "determining proofs"

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/42869436/222290153-81ac12be-4e67-4ec8-af17-9a14d4b0da88.png">

### Expected Behavior

The invalid hypercert claims should be filtered out of the batch claim, enabling the user to claim everything they are eligible for. 

Ideally the user is never shown a hypercert that will trigger this issue.

Also, after displaying the error, the user should be bounced back to the dashboard, not stuck on the contract interaction screen.

**Comment by ccerv1** [comment]
@ryscheng I managed to reproduce this error [here](https://github.com/hypercerts-org/hypercerts/issues/421#issuecomment-1452146563)

The issue appears to be that it will fail to claim if a wallet address appears more than once on the allowlist. So we need to de-dupe the allowlists.

**Comment by ryscheng** [comment]
this PR should fix the bug with duplicate entries in the allowlist.
https://github.com/hypercerts-org/hypercerts/pull/466
It will combine the total units in the duplicate entries and just make 1 allowlist proof per address
