### ISSUE TITLE
hypercert view should render description in markdown

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#422]
### Describe the feature you'd like to request

The description on the View Hypercert page should be in rendered in markdown

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/42869436/222790272-f878c45f-9472-41d0-a937-abd7bf789750.png">

### Describe the solution you'd like

A description in markdown format, similar to how it appears on OpenSea

<img width="688" alt="image" src="https://user-images.githubusercontent.com/42869436/222790803-f98e7e6c-827f-4050-82b3-e79701c2a860.png">

### Describe alternatives you've considered

Status quo

**Comment by ryscheng** [comment]
https://github.com/hypercerts-org/hypercerts/pull/571

**Comment by ryscheng** [comment]
https://testnet.hypercerts.org/app/view#claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-115355722386198139114083991919369423683584

Looking good
