### ISSUE TITLE
General confusion with list of contributors, allow list, distribution list

### ISSUE THREAD

**Issue by marsrobertson** [hypercerts-org/hypercerts#427]
### What is it?

Please see the annotated screenshot.

A number of issues.

![image](https://user-images.githubusercontent.com/44369284/222993917-6f4d19df-217d-40f3-ba22-b2b743ba9a7c.png)

Fractions from the docs: https://testnet.hypercerts.org/docs/minting-guide/step-by-step
<img width="768" alt="image" src="https://user-images.githubusercontent.com/44369284/222993850-b5fe3068-9899-45ee-aa49-8ed8ee9fff87.png">

Assuming it is possible to have simple `textarea` (no upload required) then `index` and `price` are not necessary, just the `address` and `fractions`

**OPTIONALLY:** ENS support.

**Comment by ccerv1** [comment]
Hi @marsrobertson, I'm revisiting this. 

We made a number of updates to the docs over the last few weeks. You can view them here: https://hypercerts.org/docs/minting-guide/step-by-step/

If you have any additional suggestions for docs improvements, feel free to open a pull request!

You're correct that the `index` and `price` aren't strictly necessary for the current dapp, but these are common with other allow list specs (eg, Zora) so we wanted to keep them in there.

**Comment by marsrobertson** [comment]
Tried to check Zora allow list specs: https://docs.zora.co/docs/intro (did not find)

Search query for "list": https://docs.zora.co/search?q=list

> If you have any additional suggestions for docs improvements...

In my mind, this issue was never about docs, despite being labeled as such

In my mind, it was about:
* General confusion
* Suggestive placehodler text
* Distribution list / allow list / list of contributors
* Tooltip and clickable link
* Textarea instead CSV upload 

Someone said it, I've overheard this phrase, hope you'll still like me _(or at least do not like me too much_):

> whenever you need to use docs to explain product you are doing it wrong

<img width="641" alt="image" src="https://user-images.githubusercontent.com/44369284/230296477-920d392d-294e-4b29-9a4e-322bbd4c1a90.png">
