### ISSUE TITLE
Mysterious "unclaimed" on the display page

### ISSUE THREAD

**Issue by marsrobertson** [hypercerts-org/hypercerts#429]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Initial: https://testnet.hypercerts.org/app/view?claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-25180895152149446296289720949950847647744
<img width="683" alt="image" src="https://user-images.githubusercontent.com/44369284/222994642-5af0f8e1-422f-437f-9315-11d6b84ef08e.png">

Repro: https://testnet.hypercerts.org/app/view?claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-25521177519070384759753095557382615859200

<img width="711" alt="image" src="https://user-images.githubusercontent.com/44369284/222994659-7be2d1cb-9ccc-445d-afc0-045921328cf5.png">

In both examples, I provided **NO** distribution list.

Will try to reproduce with a distribution list to see what happens and update the issue.

### Describe the Bug

`Unclaimed 0.00%`

### Expected Behavior

Do not display confusing information.

**Comment by ryscheng** [comment]
Unclaimed is only really relevant when minting with allowlist.
As of this issue, we now hide this row if the hypercert is fully claimed (fractions total 100%)
https://github.com/hypercerts-org/hypercerts/issues/476

So this shouldn't be an issue anymore. Thanks for reporting!
