### ISSUE TITLE
[FE] When the .CSV is not processed properly do not reset the form fields

### ISSUE THREAD

**Issue by marsrobertson** [hypercerts-org/hypercerts#430]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

<img width="285" alt="image" src="https://user-images.githubusercontent.com/44369284/222995633-52806e19-7c2d-47c9-9ef2-bbf2fe3f5167.png">

I tried to figure out #429 but did not succeed with the upload of .CSV: https://marsrobertson.com/allowlist.csv

After receiving the error, it resets my other fields :(

**BUT**

Check #427 maybe the upload won't be necessary, a simple `textarea` will be sufficient.

### Describe the Bug

Resets the form fields.

### Expected Behavior

Preserve the content on the site.

**Comment by ryscheng** [comment]
My guess for why this is happening is that when we `hideModal`, we are changing `showContractModal` to false here
https://github.com/hypercerts-org/hypercerts/blob/main/frontend/components/contract-interaction-dialog-context.tsx
which triggers a re-render of all children including the form.

If that's the case, it's a big fundamental to how we've implemented the interaction dialog. I don't think it has to work this way. We should be able to isolate the Dialog re-rendering from the children rendering....

Going to experiment a bit more

**Comment by ryscheng** [comment]
I think the right answer is to remove this from DappContext, which is way too high up in the element tree, and move it further down to where you plan to use it.

**Comment by bitbeckers** [comment]
Closing in favor of https://github.com/hypercerts-org/HIPs/discussions/5
