### ISSUE TITLE
Docs: Please provide detailed instrusctions how to get the project up and running

### ISSUE THREAD

**Issue by marsrobertson** [hypercerts-org/hypercerts#434]
### What is the improvement or update you wish to see?

As a developer, I would like to get the codebase up and running on my machine.

I would like to know how to obtain values for [`.env.local`](https://github.com/hypercerts-org/hypercerts/blob/main/frontend/.env.local.example):

```
NEXT_PUBLIC_DEFAULT_CHAIN_ID=
NEXT_PUBLIC_CONTRACT_ADDRESS=
NEXT_PUBLIC_GRAPH_URL=
NEXT_PUBLIC_RPC_URL=

## Storage
NEXT_PUBLIC_NFT_STORAGE_TOKEN=
NEXT_PUBLIC_WEB3_STORAGE_TOKEN=

## Supabase config
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
NEXT_PUBLIC_SUPABASE_TABLE=

## Plasmic config
PLASMIC_PROJECT_ID=
PLASMIC_PROJECT_API_TOKEN=
```

Signed up for Plasmic: https://www.plasmic.app/

<img width="927" alt="image" src="https://user-images.githubusercontent.com/44369284/223426754-f1e675fe-f2ef-4d99-9de0-4a1a34c324c0.png">

_(unsure where to find ID and API token)_

Signed up for Supabase

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/44369284/223427732-9c0500af-a275-4569-a529-6bee19c19fc3.png">

_(pretty sure that default setting would not work, I would need to configure some settings / tables / permissions, unless there are some `yarn` scripts doing that for me)_

For RPC URL I can probably use Infura or Alchemy.

For `NFT_STORAGE_TOKEN` and `WEB3_STORAGE_TOKEN` my guess is https://nft.storage/ ? 

For the contract address maybe I can reuse the public Goerli deployment? In that way, someone working on the front-end does not have to touch the EVM layer. 

# Suggested solution

1. Jump on the call with me: https://calendly.com/marsxr/basex
2. I will record the screen as we go along
3. I will update the readme / docs with detailed instructions
4. Profit. Impact. Both.

### Is there any context that might help us understand?

I guess I'm one of the very first contributors and you didn't have a chance to update the docs 😇

**Comment by marsrobertson** [comment]
Pinging you because this is a high ROI (return on investment) issue to resolve — allowing others to start working on the codebase.

📣 @ryscheng @ccerv1 @holkeb @Jipperism @bitbeckers @jmoggr

**Comment by ryscheng** [comment]
Thanks for the feedback! I've added more instructions here
https://github.com/hypercerts-org/hypercerts/pull/514

I'll close this for now, but feel free to re-open if this doesn't suffice.
