### ISSUE TITLE
feat: the minter should be the creator of the hypercert not the hypercert minter smart contract

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#436]
### Describe the feature you'd like to request

A clearer way of telling who the creator of the hypercert was for users on third party sites like OpenSea

For people looking at OpenSea or other marketplaces, it seems hard to tell if a Hypercerts is actually from the issuer, since all hypercerts are created through the same contract. This makes it easy to copy all the text from an existing hypercerts and mint a new one on Hypercerts front end. Users on sites like OpenSea might not be able to tell the difference if they don’t look deep into the contract.

### Describe the solution you'd like

Instead of Hypercert Minter, it should say the name of the Project or Team who created the hypercert

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/42869436/224418823-81ba3c29-48af-46ee-9d8c-eb823c0f8800.png">

### Describe alternatives you've considered

Creating a property field to identify the name of the team / creator in human-readable form (not a wallet address)

**Comment by marsrobertson** [comment]
Unsure how possible it would be to change `msg.sender` or creator of the contract - in my understanding, it will be always the  hypercert minter smart contract _(please fact check, don't treat me as an oracle)_

With that said, check this out, reasonable workaround: https://docs.opensea.io/docs/metadata-standards

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/44369284/224507403-69947fa3-e88d-4370-abe5-cbee88b3a670.png">

Then all the data related to hypercert (such as creator) could be displayed on OpenSea.

**Comment by ryscheng** [comment]
Ya, thanks for the explanation, Mars.

I don't think we can change what gets shown there, it's determined by the "Collection", which is basically which contract the token is stored under
https://opensea.io/collection/hypercertminter

IMO, we should just have better navigation mechanisms in our DApp. Okay to close for now @ccerv1 ?

**Comment by ryscheng** [comment]
@ccerv1 ping

**Comment by ryscheng** [comment]
@ccerv1 Going to close this for now.

If we want to add new metadata/attributes to show up in OpenSea, let's file a new issue for that
