### ISSUE TITLE
UI/UX: A hypercert owner can sell their fraction on OpenSea

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#440]
The UI/UX is done here: https://github.com/hypercerts-org/hypercerts/issues/758

This issue concerns the proper linking from hypercerts.org to OpenSea.

We link from each fraction that an owner owns to OpenSea, such that it is easy to sell a fraction. This is how it looks in the current mock-up:

![Image](https://user-images.githubusercontent.com/103380539/225331267-3df6a681-9591-42c6-89c5-46357621538e.png)

**Comment by holkeb** [comment]
The UI/UX for Zuzalu hypercerts can look something like this:



![Image](https://github.com/hypercerts-org/hypercerts/assets/103380539/3a0d18d9-a393-4123-92be-794f0aaa9ccb)



![Image](https://github.com/hypercerts-org/hypercerts/assets/103380539/08668808-e225-4e8c-9ed6-c59ab8b30bd0)

**Comment by bitbeckers** [comment]
@holkeb is this still in scope? On OpenSea the current certs can be sold once, and we're moving to our store. 

So it might be easiest to roll it out first in our own marketplace and surface a good notification-update-UI to get claim holders to update the TransferRestrictions

**Comment by holkeb** [comment]
not relevant anymore, I think we want to use the hypercertsTrader
