### ISSUE TITLE
A funder can explore hypercerts in a gallery

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#441]
An operator of a frontend can manually add hypercerts to collections.

A funder can explore these and only these hypercerts in a gallery. This is how the current mock-up looks like:

![Image](https://user-images.githubusercontent.com/103380539/225345678-18a408b9-3d86-4f7a-a6f7-0fd66ad8ab54.png)

In addition some of those hypercerts can be featured (probably just another collection). These hypercerts are displayed on the landing page above the gallery. Current mock-up:

![Image](https://user-images.githubusercontent.com/103380539/225346788-ecadfa77-60be-4f0b-b4a4-94745e60193b.png)

**Comment by holkeb** [comment]
Optionally/later: It would be great to have a searchable table with hypercerts

**Comment by ryscheng** [comment]
What a throwback!!

@holkeb can we close this out for now?
I think you did a good job with the Gitcoin explore page.

**Comment by holkeb** [comment]
ha, yes :)
