### ISSUE TITLE
pagination for hypercerts browse and dashboard pages

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#445]
### Describe the feature you'd like to request

The number of hypercerts per page should be limited (eg, 10,50) and returned as pages

### Describe the solution you'd like

Pages on the browse and dashboard pages (wherever multiple hypercerts can be returned)

### Describe alternatives you've considered

Infinite scroll (current UI)

**Comment by bitbeckers** [comment]
Closing in favor of https://github.com/hypercerts-org/HIPs/discussions/5
