### ISSUE TITLE
[FE] Single claim a hypercert from the view page

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#458]
### Describe the feature you'd like to request

A user is able to claim a hypercert from the view page.

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/42869436/227271948-4647f67d-ffeb-4403-be63-d6f562261201.png">

### Describe the solution you'd like

A button to claim if you are allowlisted. The button is disabled if you have already claimed / aren't eligible to claim.

### Describe alternatives you've considered

A select checkbox from the main dashboard

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
