### ISSUE TITLE
[Outreach] Prepare a custom message including a hypercerts.org/app/create? url for all projects

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#46]
Todo before final:

- [ ] update links

**Comment by holkeb** [comment]
First draft done in the CRM. 

@ccerv1 
- please review 
- if you can, add the data that can trigger the messages msgTruncatedText, msgArtwork, and msgSameScopeName (they are on sheet textBuildingBlocks)

**Comment by holkeb** [comment]
Note that there are two columns: The first "firstMessage" is where the message is generated, but when it is copy and pasted it is shown in quotation marks. For no quotation marks there is an additional column "firstMessageNoQuotationMarks"

**Comment by holkeb** [comment]
@ccerv1 what is the character limit for the description? It says 500, but they seem to be truncated at different points

**Comment by holkeb** [comment]
Links need to be updated, once fully deployed

**Comment by ccerv1** [comment]
> @ccerv1 what is the character limit for the description? It says 500, but they seem to be truncated at different points

Yes, I implemented some logic that finds the last paragraph before reaching the 500 char limit. So many projects will end up a bit over 500 chars after the final paragraph is appended.

**Comment by ccerv1** [comment]
Looks good to me! Closing.
