### ISSUE TITLE
feat: let minters change the fraction they keep

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#470]
We can let minters choose how much they want to keep with a strong default of 50%.

Here is a simple implementation in plasmic (new page create-test):

![Image](https://user-images.githubusercontent.com/103380539/227949379-44a799e4-c01e-4db8-96ec-74878a996a46.png)

We can change the input field to a slider or at least change it, such that the field is checked for an input of a number between 0 and 100.

**Comment by holkeb** [comment]
As discussed: we will add this later, but not for the pilot

**Comment by ryscheng** [comment]
Adding a slider here
https://github.com/hypercerts-org/hypercerts/pull/594

**Comment by ryscheng** [comment]
Should be implemented for the most part here

https://github.com/hypercerts-org/hypercerts/pull/598

**Comment by ryscheng** [comment]
Fixed some disabling behavior in Plasmic v24.2.0
