### ISSUE TITLE
Remove the "unclaimed" entry on the view page if it is equal to 0

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#476]
see test in https://github.com/hypercerts-org/hypercerts/issues/421

**Comment by ryscheng** [comment]
Pretty simple change to make in Plasmic.
Just set the visibility of that row as  a dynamic value with the following:

CC @holkeb for learning reference:
Here's how to show if all the claimToken units don't add up to the total supply
```
Math.round($ctx.hypercertData.claim.totalUnits) !== $ctx.hypercertData.claimTokens.map(t => Math.round(t.units)).reduce((a, c) => a + c,0)
```
