### ISSUE TITLE
feat: display hypercert owners in descending order of shares

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#494]
### Describe the feature you'd like to request

These should be in descending order

<img width="746" alt="image" src="https://user-images.githubusercontent.com/42869436/229014357-b3f52291-5524-43e4-99f2-35b55e91c0ce.png">

### Describe the solution you'd like

The data should be fetched in descending order, not chronological order

### Describe alternatives you've considered

Preserve status quo

**Comment by ryscheng** [comment]
so in the repeat collection for the items, you want to sort with a custom compare function
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by ccerv1** [comment]
just got around to fixing this! so satisfying!
