### ISSUE TITLE
user question: created hypercert can't be claimed

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#498]
User question (as a twitter DM):

> Hi, I do have a question about claiming the hypercert that you creted. I created the WaterDAO cert but it still says unclaimed, yet there is no button to do so.

![Image](https://user-images.githubusercontent.com/103380539/229365580-0b077609-980d-4583-b6c4-9d0d405006c0.png)

![Image](https://user-images.githubusercontent.com/103380539/229365591-d7993ce8-ff6f-4cdf-b1e4-a5dc555e2593.png)

**Comment by holkeb** [comment]
@ccerv1 can you check this and respond to the user via twitter DM (@_WaterDAO)

**Comment by ryscheng** [comment]
There's a timeout attached to the button. Is it still unclaimable?

**Comment by holkeb** [comment]
I'll check with the project

**Comment by ccerv1** [comment]
I'm seeing a 50% fraction in the minter's wallet. I think it's all set!
https://hypercerts.org/app/view?claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-70778732319555200400381918345807787982848
