### ISSUE TITLE
SDK: claimById not working when switching chains

### ISSUE THREAD

**Issue by carlbarrdahl** [hypercerts-org/hypercerts#505]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

SDK

### To Reproduce

The chain config is initialized on loading and is not possible to change during runtime, for example changing network with wagmi.

https://github.com/hypercerts-org/hypercerts/blob/e54f0ccca0803b264ffa9816e89653e60a55ba7f/sdk/src/queries/claims.ts#L4-L18

### Describe the Bug

-

### Expected Behavior

The correct subgraph is called after changing chain / network

**Comment by bitbeckers** [comment]
@carlbarrdahl we've released an new and improved SDK that should handle everything via a client class. Maybe you want to give it a spin and give us some feedback? 

https://www.npmjs.com/package/@hypercerts-org/sdk
