### ISSUE TITLE
Hypercerts merchandise store

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#507]
### What is it?

Hypershirts for Hypercerts!

**Comment by ryscheng** [comment]
Auction limited edition shirts

**Comment by ccerv1** [comment]
Kevin says he uses [Printful](https://www.printful.com/) for dropshipping and orders large batches for events. He also said Octavian might be available for a few days to help with designs.

**Comment by ccerv1** [comment]
Theresa may be able to help manage this. Needs an owner though if we want to make it happen! 

cc @holkeb

**Comment by ccerv1** [comment]
Latest version of designs below. Closing this issue for now.

![Image](https://github.com/hypercerts-org/hypercerts/assets/42869436/f8cfcfc6-4e35-4834-a4b7-656a4a7f5d18)
