### ISSUE TITLE
resolve duplicate hypercerts (ie, collisions) in the database

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#521]

**Comment by ccerv1** [comment]
@ryscheng FYI, I created a script that queries TheGraph and constructs a new table with basic data about each project. I've stored it in a new Supabase table called `claims-metadata-mapping`

@holkeb when you have a chance, it would be great if you could have look at the table and give some thought about collision / de-duping attestations. If you have a view on what this would look like, feel free to start implementing or file an issue and I can return to it in a subsequent sprint.

Here's a preview -- you can see some of the duplicates quite clearly.


id | createdAt | claimId | title | creatorAddress | totalUnits | date
-- | -- | -- | -- | -- | -- | --
0 | 1679331273 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-1361129467683753853853498429727072845824 | The first hypercert minted on Optimism | 0x22e4b9b003cc7b7149cf2135dfce2baddc7a534f | 3 | 2023-03-20 12:54:33
1 | 1680033276 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-1701411834604692317316873037158841057280 | Web3beach | 0xefedaf9c07e6eb56bb8f82f30018e4461b1c5f4c | 8104 | 2023-03-28 15:54:36
2 | 1680040284 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-2041694201525630780780247644590609268736 | Hypercerts x Gitcoin Test | 0x22e4b9b003cc7b7149cf2135dfce2baddc7a534f | 600 | 2023-03-28 17:51:24
3 | 1680055409 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-2381976568446569244243622252022377480192 | LunCo: opensource space engineering | 0xa64f2228ccec96076c82abb903021c33859082f8 | 4940 | 2023-03-28 22:03:29
4 | 1680094750 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-10208471007628153903901238222953046343680 | POAPin | 0x5afc7720b161788f9d833555b7ebc3274fd98da1 | 27002 | 2023-03-29 08:59:10
5 | 1680103688 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-19736377281414430880875727231042556264448 | Optimism DAppNode Package | 0x523d007855b3543797e0d3d462cb44b601274819 | 79532 | 2023-03-29 11:28:08
6 | 1680124080 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-26201742252912261686679844772246152282112 | Kokonut Network 🥥🌴 Gitcoin Alpha Round | 0x0ea26051f7657d59418da186137141cea90d0652 | 14272 | 2023-03-29 17:08:00
7 | 1680155238 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-41854731131275431005995076714107490009088 | Loanshark Gitcoin Alpha | 0x7d658841f8ba93299970f6e765c2ce205f1e70dd | 40440 | 2023-03-30 01:47:18
8 | 1680170495 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-43896425332801061786775324358698099277824 | covoco 🗳 | 0xabb9ac1f97fb9b40a538b41f7f5e3681d4495be5 | 1066 | 2023-03-30 06:01:35
9 | 1680181313 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50361790304298892592579441899901695295488 | DefiLab.xyz | 0xa1c0534ee785a30455fcd45bbdee3a6b6227632d | 7560 | 2023-03-30 09:01:53
10 | 1680181403 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50702072671219831056042816507333463506944 | DefiLab.xyz | 0x9fe6764778db6ad5c5ed86242485d1a868a8c52a | 7560 | 2023-03-30 09:03:23
11 | 1680181631 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-51042355038140769519506191114765231718400 | Barichara Regeneration Fund | 0xfd9f8a0f4bdeac72f08af1c708023cc31dd2e3be | 11374 | 2023-03-30 09:07:11
12 | 1680199347 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-55125743441192031081066686403946450255872 | The Solar Foundation | 0xe3f4f3ad70c1190ec480554bbc3ed30285ae0610 | 25812 | 2023-03-30 14:02:27
13 | 1680206737 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-55466025808112969544530061011378218467328 | The Solar Foundation | 0xe3f4f3ad70c1190ec480554bbc3ed30285ae0610 | 25812 | 2023-03-30 16:05:37

**Comment by ryscheng** [comment]
We probably want to start creating tools to detect overlap in the impact hyperspace and then separately visualization tools to see them. IMO we should work backwards, I'm curious how you imagine the UX would look like?

**Comment by ccerv1** [comment]
Update: I've modified the Supabase database so that it now contains some of the hypercerts fields and has some basic collision detection. As of now, 3/42 Gitcoin projects have a collision. 

Here's an example of what it looks like in the database:

id | claimId | createdAt | title | creatorAddress | totalUnits | date | properties | hypercert | collision
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
46 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-16333553612205046246241981156724874149888 | 1680100223 | poseidon | 0xe8c0fe3699db673486c391a4eefa5a18c7cfd4d6 | 10000 | 2023-03-29 10:30:23 | [] | {'impact_scope': {'name': 'Impact Scope', 'value': ['all'], 'excludes': [], 'display_value': 'all'}, 'work_scope': {'name': 'Work Scope', 'value': ['sisyphus dao is a community dedicated to promoting blockchain information and learning'], 'excludes': [], 'display_value': 'sisyphus dao is a community dedicated to promoting blockchain information and learning'}, 'impact_timeframe': {'name': 'Impact Timeframe', 'value': [1672531200, 0], 'display_value': '2023-01-01 → indefinite'}, 'work_timeframe': {'name': 'Work Timeframe', 'value': [1672531200, 1680048000], 'display_value': '2023-01-01 → 2023-03-29'}, 'rights': {'name': 'Rights', 'value': ['Public Display'], 'excludes': [], 'display_value': 'Public Display'}, 'contributors': {'name': 'Contributors', 'value': ['0xe8c0fe3699db673486c391a4eefa5a18c7cfd4d6'], 'display_value': '0xe8c0fe3699db673486c391a4eefa5a18c7cfd4d6'}} | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-15652988878363169319315231941861337726976
113 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-39132472195907923298288079854653344317440 | 1680149510 | Shamys | 0x889d2641eb38412bdacf010d38635ba132f6d843 | 10000 | 2023-03-30 0:11:50 | [] | {'impact_scope': {'name': 'Impact Scope', 'value': ['all'], 'excludes': [], 'display_value': 'all'}, 'work_scope': {'name': 'Work Scope', 'value': ['your project'], 'excludes': [], 'display_value': 'your project'}, 'impact_timeframe': {'name': 'Impact Timeframe', 'value': [1672531200, 0], 'display_value': '2023-01-01 → indefinite'}, 'work_timeframe': {'name': 'Work Timeframe', 'value': [1672531200, 1680134400], 'display_value': '2023-01-01 → 2023-03-30'}, 'rights': {'name': 'Rights', 'value': ['Public Display'], 'excludes': [], 'display_value': 'Public Display'}, 'contributors': {'name': 'Contributors', 'value': ['0x889d2641eb38412bdacf010d38635ba132f6d843'], 'display_value': '0x889d2641eb38412bdacf010d38635ba132f6d843'}} | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-30965695389805400175167089276290907242496
147 | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50702072671219831056042816507333463506944 | 1680181403 | DefiLab.xyz | 0x9fe6764778db6ad5c5ed86242485d1a868a8c52a | 7560 | 2023-03-30 9:03:23 | [{'trait_type': 'Funding Platform', 'value': 'Gitcoin Grants'}, {'trait_type': 'Funding Round', 'value': 'Alpha Round'}, {'trait_type': 'Matching Pool', 'value': 'Open Source Software'}] | {'impact_scope': {'name': 'Impact Scope', 'value': ['all'], 'excludes': [], 'display_value': 'all'}, 'work_scope': {'name': 'Work Scope', 'value': ['DefiLab.xyz'], 'excludes': [], 'display_value': 'DefiLab.xyz'}, 'impact_timeframe': {'name': 'Impact Timeframe', 'value': [1663804800, 0], 'display_value': '2022-09-22 → indefinite'}, 'work_timeframe': {'name': 'Work Timeframe', 'value': [1663804800, 1673740800], 'display_value': '2022-09-22 → 2023-01-15'}, 'rights': {'name': 'Rights', 'value': ['Public Display'], 'excludes': [], 'display_value': 'Public Display'}, 'contributors': {'name': 'Contributors', 'value': ['0x9fe6764778db6ad5c5ed86242485d1a868a8c52a'], 'display_value': '0x9fe6764778db6ad5c5ed86242485d1a868a8c52a'}} | 0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50361790304298892592579441899901695295488



> We probably want to start creating tools to detect overlap in the impact hyperspace and then separately visualization tools to see them. IMO we should work backwards, I'm curious how you imagine the UX would look like?

@holkeb do you have thoughts on the UX?

**Comment by holkeb** [comment]
Rough thoughts: Generally I imagine a 2D representation of the impact space, where the user can choose what to put on the axes.
e.g. 
- I want to see all hypercerts from contributor X over time --> x-axis: time of work + y-axis: scope of work + filter for contributor X
- I want to see all contributors to work scope X over time --> x-axis: time of work + y-axis: contributors + filter for work scope X

It might actually have some similarity to the github acitivity chart with different axes 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/103380539/232538638-ab52133a-b2e3-4b3e-a30c-268615f43315.png">

**Comment by ccerv1** [comment]
@holkeb I think that would be really cool long-term, when he have more of the protocols for contributor identity and work scope naming in place. Could you provide some more thoughts on what an interim solution might consist of, ie, something to handle the collisions we currently have.

Here's a very quick sketch of what I was thinking. Basically, if you are the creator, you can `hide` a duplicate. If you are not the creator, you can `contest` a duplicate.



![Image](https://user-images.githubusercontent.com/42869436/233166292-3b6ea251-6ea7-45e4-b84f-eca567d4c143.png)

**Comment by holkeb** [comment]
Yes, I think I wouldn't make it as visible. For the reporting I think I would follow examples from social media as users are familiar with that

![image](https://user-images.githubusercontent.com/103380539/233625528-cc332756-5ca2-4aa3-bc57-e0c8f2378735.png)

So we can add three little dots on each hypercert in the dashboard view for additional options. Everyone gets the options
- Mark hypercert as duplicate --> just sends us a message that it was marked as a duplicate (ideally the user would see that she marked it, but that's optional)
- Report hypercert --> opens a small window with a text field "Please explain the reasons for reporting this hypercert", user fill this out and it gets send to us

Additionally creators get the option
- Hide hypercert --> a window opens with the question "Do you really want to hide this hypercert? It won't be shown to any user in their dashboards, but it will still exist on the blockchain."

**Comment by ccerv1** [comment]
I like this and think such a UI makes sense for when there are things that look spam. But what about actual collisions? You actual need more info about the cert than is shown in the dashboard view to decide which one is legitimate.

**Comment by holkeb** [comment]
who do you have in mind that would use this feature? 

I think later we want to create tools for evaluators to be able to compare and frontend operators have ultimately to decide, which they want to show. Currently, i think we would do this as we are the frontend operator. But i would build tools for us at this point

**Comment by holkeb** [comment]
as discussed in the standup, we'll do this in supabase for now. @holkeb takes a first stab at implementing this

**Comment by ccerv1** [comment]
@holkeb can we close this out for now?

**Comment by holkeb** [comment]
I think we should add the option for users to report and mark duplicates soon --> this should be in a future sprint

**Comment by ccerv1** [comment]
Closing this out. I've updated the collision tracking scripts and set all duplicates to have a `hidden` value of TRUE. 

Here's my duplicate report [summary](https://docs.google.com/spreadsheets/d/1Uka-K8nNoHUd5klput_EdsA5FTxrRBx3HTFfzYDxmPw/edit?usp=sharing) and raw below:

```
{
    "duplicate_list": [
        "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50361790304298892592579441899901695295488",
        "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-55125743441192031081066686403946450255872",
        "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-63292520247294554204187676982308887330816",
        "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-90174827234048692817794270969418576035840",
        "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165377230323576093243200059211839350767616",
        "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165036947956655154779736684604407582556160"
    ],
    "cases": [
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50702072671219831056042816507333463506944",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50361790304298892592579441899901695295488",
            "creator": "0x9fe6764778db6ad5c5ed86242485d1a868a8c52a",
            "date": "2023-03-30T09:03:23+00:00",
            "title": "DefiLab.xyz",
            "case": "duplicate claim in hyperspace (by 0x9fe6764778db6ad5c5ed86242485d1a868a8c52a & 0xa1c0534ee785a30455fcd45bbdee3a6b6227632d creator)",
            "duplicate": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-50361790304298892592579441899901695295488",
            "explanation": "the first creator appears to the controller of the Gitcoin project wallet"
        },
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-55466025808112969544530061011378218467328",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-55125743441192031081066686403946450255872",
            "creator": "0xe3f4f3ad70c1190ec480554bbc3ed30285ae0610",
            "date": "2023-03-30T16:05:37+00:00",
            "title": "The Solar Foundation",
            "case": "duplicate title in hypercerts (same creator)",
            "duplicate": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-55125743441192031081066686403946450255872",
            "explanation": "the creator already requested to suppress the duplicate"
        },
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-63292520247294554204187676982308887330816",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-62952237880373615740724302374877119119360",
            "creator": "0x9da5c4c283c2fe334e2a1081a7fdae45475ceb41",
            "date": "2023-03-31T05:15:58+00:00",
            "title": "W3Space",
            "case": "duplicate claim in hyperspace (by 0x9da5c4c283c2fe334e2a1081a7fdae45475ceb41 & 0x70b20209c83ec8d01e3c7f2ec77bde7c40cdf2f6 creator)",
            "duplicate": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-63292520247294554204187676982308887330816",
            "explanation": "the second creator appears to the controller of the Gitcoin project wallet"
        },
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-117057134220802831431400864956528264740864",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-90174827234048692817794270969418576035840",
            "creator": "0xf3ad97364bccc3ea0582ede58c363888f8c4ec85",
            "date": "2023-04-08T19:41:50+00:00",
            "title": "AgroforestDAO",
            "case": "duplicate claim in hyperspace (same creator creator)",
            "duplicate": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-90174827234048692817794270969418576035840",
            "explanation": "the hypercerts are identical"
        },
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165377230323576093243200059211839350767616",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165036947956655154779736684604407582556160",
            "creator": "0x36f322fc85b24ab13263cfe9217b28f8e2b38381",
            "date": "2023-05-21T09:45:03+00:00",
            "title": "Blocktrend\uff08\u5340\u584a\u52e2\uff09",
            "case": "duplicate title in hypercerts (same creator)",
            "duplicate": "both",
            "explanation": "three hypercerts were created. the token ending in 72 is the accepted one"
        },
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165717512690497031706663433819271118979072",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165036947956655154779736684604407582556160",
            "creator": "0x36f322fc85b24ab13263cfe9217b28f8e2b38381",
            "date": "2023-05-21T10:03:06+00:00",
            "title": "Blocktrend\uff08\u5340\u584a\u52e2\uff09",
            "case": "duplicate title in hypercerts (same creator)",
            "duplicate": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165036947956655154779736684604407582556160",
            "explanation": "three hypercerts were created. the token ending in 72 is the accepted one"
        },
        {
            "id": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165717512690497031706663433819271118979072",
            "collision": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165377230323576093243200059211839350767616",
            "creator": "0x36f322fc85b24ab13263cfe9217b28f8e2b38381",
            "date": "2023-05-21T10:03:06+00:00",
            "title": "Blocktrend\uff08\u5340\u584a\u52e2\uff09",
            "case": "duplicate title in hypercerts (same creator)",
            "duplicate": "0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-165377230323576093243200059211839350767616",
            "explanation": "three hypercerts were created. the token ending in 72 is the accepted one"
        }
    ]
}
```
