### ISSUE TITLE
Bug: something went wrong while generating merkle tree from csv file

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#527]
![Image](https://user-images.githubusercontent.com/103380539/230930642-20a65534-aaa0-48f2-8651-679592ceedf8.png)

[Here](https://hypercerts.org/app/create#name=BrightID%20%F0%9F%94%86%20Universal%20Proof%20of%20Uniqueness&description=BrightID%20%E2%80%93%20an%20open%20source%20Sybil-resistant%20identity%20lego.%0A%0AWe%20are%20thrilled%20to%20be%20working%20with%20Gitcoin%20to%20reduce%20the%20impact%20of%20Sybil%20accounts.%20With%20your%20help%2C%20we%20added%20over%2063%2C000%20verified%20BrightID%20users.%20Thank%20you%20for%20the%20amazing%20support%20so%20far%21%20Let%27s%20keep%20the%20momentum%20going%21%0A%0AGet%2050%25%20bonus%20matching%20for%20all%20your%20Gitcoin%20grants%20by%20joining%20BrightID%20and%20connecting%20it%20to%20your%20Gitcoin%20Passport%20.%20After%20completing%20your%20passport%2C%20come%20back%20and%20link%20it%20to%20the%20trust%20bonus%20screen%20in%20your%20Gitcoin%20profile%20page.&externalLink=https%3A%2F%2Fwww.brightid.org&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreiadate4cocvimh422fmc3kcwpcbftawuexl3mnmvs3kwtbrcc4km4&bannerUrl=https%3A%2F%2Fbafybeigh3i6qppywfepzm4mkg2jzrnspaxxal54au5m3cwq4aep45kk3by.ipfs.w3s.link%2Fipfs%2Fbafybeigh3i6qppywfepzm4mkg2jzrnspaxxal54au5m3cwq4aep45kk3by%2FBrightID_Universal_Proof_of_Uniqueness.png&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=BrightID&workTimeStart=2022-09-22&workTimeEnd=2023-01-15&rights%5B0%5D=Public%20Display&contributors=0x4B8810b079eb22ecF2D1f75E08E0AbbD6fD87dbF&allowlistUrl=https%3A%2F%2Fbafybeic4zg2xyuoc3w7f6sq5sidg5dydvpthivl5nflnefqucptw5ie57a.ipfs.w3s.link%2Fipfs%2Fbafybeic4zg2xyuoc3w7f6sq5sidg5dydvpthivl5nflnefqucptw5ie57a%2FBrightID_Universal_Proof_of_Uniqueness.csv&backgroundColor=blue&backgroundVectorArt=contours&metadataProperties=%5B%7B%22trait_type%22%3A%20%22Funding%20Platform%22%2C%20%22value%22%3A%20%22Gitcoin%20Grants%22%7D%2C%20%7B%22trait_type%22%3A%20%22Funding%20Round%22%2C%20%22value%22%3A%20%22Alpha%20Round%22%7D%2C%20%7B%22trait_type%22%3A%20%22Matching%20Pool%22%2C%20%22value%22%3A%20%22Open%20Source%20Software%22%7D%5D&impactTimeStart=2022-09-22
) is the minting link that I provided to the project in the screenshot above.

And this is the alternative banner image: https://ipfs.sea.tube/ipfs/QmUtmJxmMpCamR13hrmCGPjHSXn7V43YAqWmAcbAM14Umk

There was an emoji in the address before, which we thought was the problem, but we changed that in the above minting link already.

The minting link works for me on testnet. The project gets an error on Optimism as shown in the screenshot.

**Comment by ryscheng** [comment]
I was able to walk him through minting his hypercert. Indeed, it was the CSV that was not working. All I did was reupload it to web3.storage and give him a new allowlist link.

He said you gave him a new link previously, but both of us were not able to load that link for some reason.
