### ISSUE TITLE
Bug: Internal JSON-RPC error

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#529]
two people reported this error on twitter: 

![Image](https://user-images.githubusercontent.com/103380539/231400451-b23a3144-2085-4bb2-b48f-3a245e2f2639.png)

I haven't reached out to them yet.

**Comment by ryscheng** [comment]
Thanks! This is quite difficult to debug with the information given. Should we reach out and schedule some time to go into it with them?

I'm hoping some of this gets resolved in the error handling work we're currently doing

**Comment by ryscheng** [comment]
CC @bitbeckers

**Comment by bitbeckers** [comment]
@holkeb can you reach out to get some specifics on how to make it crash? Agree that we'll surface more informative errors in the future and this would be a good validating case

**Comment by bitbeckers** [comment]
@holkeb want to keep this open? Internal RPC error can be a bunch of things and this ticket has been open for a while..

**Comment by bitbeckers** [comment]
@ryscheng this item is stale, can we close it?

**Comment by ryscheng** [comment]
sgtm, let's keep an eye out for user reports and Sentry to see if we need to reopen
