### ISSUE TITLE
SDK Error handling

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#535]
### Describe the feature you'd like to request

Implement consistent error handlers accross the SDK. 

### Describe the solution you'd like

- Catch and log errors and warnings
- Consistent reporting of errors and warnings
- Classifying known possible error to error types

### Describe alternatives you've considered

- Crash and burn. But that's terrible UX.

**Comment by bitbeckers** [comment]
Basic setup in #542 

- Winston Logging
- Result<Ok, Error> pattern on calls, including async
- Exhaustive Error type checking
- Error types declaration

**Comment by ryscheng** [comment]
Just writing down our conclusions from our meeting yesterday.

- Making our own Error subclasses with a _type discriminator field makes sense. Let's keep doing that.
- Going to revert away from Result<Ok, Error> types and go back to throwing errors. Both of us don't like it, but it's closer to what is more typical JS conventions
- We won't have exhaustive error type checking in this case, we'll have to document expected errors thoroughly in our documentation. In the case we miss something, we can leverage our Sentry integration to find unhandled errors.
