### ISSUE TITLE
expose pagination from thegraph client

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#545]
### Describe the feature you'd like to request

a request to thegraph (eg, for claimTokens) should be able return any number of records

### Describe the solution you'd like

pagination, ideally not using offsets

### Describe alternatives you've considered

caching certain metrics or creating a subgraph with metrics about a given hypercert (eg, total # claimed)

**Comment by ryscheng** [comment]
Blocked on https://github.com/hypercerts-org/hypercerts/issues/548

Or is this just a duplicate?

**Comment by ccerv1** [comment]
#548 is a more robust issue descriptor, so will close this one out!
