### ISSUE TITLE
SDK: Open up Graph queries

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#548]
### Describe the feature you'd like to request

Currently Graph queries are minimal and opinitated. 

### Describe the solution you'd like

Set default values and defined input object for Graph queries. 

Example pseudocode:
```javascript
const queryParams = {
    sort: "asc" | "desc",
    skip: 0,
    first: 1000,
    paginate: true | false,
    live: true | false
}

### Describe alternatives you've considered

Direct access to client (already provided)

**Comment by ryscheng** [comment]
Yes! this would be amazing. Would help fix the bug we currently have where the view page is missing some of the top fraction holders.

**Comment by bitbeckers** [comment]
@ryscheng UX wise, which queries are reasonable to have live?

- [ ] fractionsByOwner
- [ ] fractionsByClaim
- [ ] fractionsById
- [ ] claimsByOwner
- [ ] claimById
- [ ] firstClaims
