### ISSUE TITLE
User profiles in the Dapp

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#555]
### Describe the feature you'd like to request

The only place to see a user's hypercerts right now is my own dashboard. Maybe we want to evolve to be a more general purpose profile page, giving users the ability to navigate between profile pages of different users

### Describe the solution you'd like

As an initial step, we could make a new page that accepts an address, similar to what we do with the hypercert view page.
e.g. /app/user#address=0xabc

### Describe alternatives you've considered

N/A

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
