### ISSUE TITLE
Public version of the protocol roadmap

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#575]
Let's build on the doc that @holkeb created [here](https://docs.google.com/document/d/1pPJRs3KPToAXRUEKbHxk5aA4Yse85rds_QJRVFZNyFA/edit?usp=sharing). Ideally we have:

- [ ] A high level version of the roadmap in chart format
- [ ] A more detailed public version (like a PRD for each epic in the roadmap)

**Comment by holkeb** [comment]
https://docs.google.com/document/d/1ax0pHNj_pBGpYsRHIsXfhSImEHOEOyKu-Pmd544R9nk/edit?usp=sharing

**Comment by holkeb** [comment]
let's work in this during team week

**Comment by bitbeckers** [comment]
In https://github.com/orgs/hypercerts-org/projects/7
