### ISSUE TITLE
bug: screen resizes on mobile

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#585]
On the gallery view for the climate solutions, the screen resizes on my iphone (14) as shown in the screenshot below: https://testnet.hypercerts.org/app/gallery-climate

This happens with all browsers (brave, firefox, safari).

It doesn't happen on the other gallery views like https://testnet.hypercerts.org/app/gallery-oss

![Image](https://user-images.githubusercontent.com/103380539/234134573-e96e1684-cbb3-490e-8824-23c684b3f836.png)

**Comment by holkeb** [comment]
@ccerv1 as mentioned in the standup, can you send me where a solution has already been implemented?

**Comment by holkeb** [comment]
Seems like overflow-wrap might be the right solution: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

And here it says you might use word-wrap in addition to overflow-wrap: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by holkeb** [comment]
add via https://docs.plasmic.app/learn/custom-css/

**Comment by ryscheng** [comment]
Fixed
