### ISSUE TITLE
Fixup contracts/ directory build

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#597]
### What is it?

Just noting some followup items from https://github.com/hypercerts-org/hypercerts/pull/595

- [x] Should we remove rollup in contracts/ ? seems unnecessary to be bundling
- [x] Can you help fix the `yarn lint` command in contracts/ I disabled it because it wasn't running properly and I didn't know what you changed.

**Comment by bitbeckers** [comment]
Addition: 
- [ ] Lock down versioning. This bug was introduced in Foundry recently and is now part of our pipeline: https://github.com/foundry-rs/foundry/issues/4835
