### ISSUE TITLE
A Hypercert Owner can browse the hypercert collections of other users

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#6]

**Comment by ccerv1** [comment]
@ryscheng this feature needs prioritization. currently, a user can only see their hypercerts collection. should it be possible to view the collection of others, eg, a link on the contributors list

<img width="774" alt="image" src="https://user-images.githubusercontent.com/42869436/225020100-85614cd8-b7ff-4391-a175-e1adf3d6b317.png">

**Comment by bitbeckers** [comment]
https://github.com/hypercerts-org/HIPs/discussions/5
