### ISSUE TITLE
InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#613]
### To Reproduce

.

### Describe the Bug

High frequency of errors in Sentry: 

```
InvalidStateError

Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

mechanismonunhandledrejection
handledfalse

    app:///assets/injectedScript.f085ea21.js in U.send at line 1:4413
    In App
    Called from:
    webpack://_N_E/../node_modules/@coinbase/wallet-sdk/dist/connection/RxWebSocket.js in exports.RxWebSocket.sendData
    System
```

Seems to be related to: https://github.com/coinbase/coinbase-wallet-sdk/issues/812 since this error can also be found in Sentry: 

```
Error webSocket.onclose(@coinbase/wallet-sdk/dist/connection/RxWebSocket)
websocket error 1006: 
```

### Expected Behavior

No errors

**Comment by bitbeckers** [comment]
Updated Wagmi and Rainbowkit. Monitor Sentry to check if issue persists

**Comment by ryscheng** [comment]
Looks like its still an issue

**Comment by bitbeckers** [comment]
Removed websocket in #897 


![Image](https://github.com/hypercerts-org/hypercerts/assets/19667964/3074becc-e35a-4058-88a7-17185ac5118f)

Let's monitor if errors drop after PR is merged

**Comment by ryscheng** [comment]
Amazing, thanks for noticing that!

**Comment by bitbeckers** [comment]
Errors reduced so we'll keep monitoring Sentry and raise it again as the errors arise
