### ISSUE TITLE
create: users with optimism multisig safes cannot create a hypercert

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#618]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Smart Contracts

### To Reproduce

Try to create a hypercert using an Optimism multisig

### Describe the Bug

Here is a transaction log from a Safe:
-Creating the allowlist: https://optimistic.etherscan.io/tx/0x51437cf41a93ef15d6c362a99ff36830af157db64a1008820031aaadc6dbf382#eventlog
- Claiming the fraction: https://optimistic.etherscan.io/tx/0x6bf94f647d82e79f7431a6ee8c9b2da580d6ea60a5fcc9fc084540a5a3b7fd0a#eventlog

***

from @bitbeckers 
So what you see is that the tx is different because you're using Safe. You could say there's a 'metaTx' build by safe:

0 to address 0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07
1 value uint256 0
2 data bytes 0xb316962f00000000000000000000000084178186a503ef41d30da4cdb2bc27aefa65ed0f00000000000000000000000000000000000000000000000000000000000064d4b947a7718c122cc006e832a1d79b8994feaae1ae39dc37c9e9a0b144ce1d8dd900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000042697066733a2f2f6261666b72656966377866647779357833686668377a70716e6c783779626d36646a62673471336d6535686533327075627a7761726a6469633475000000000000000000000000000000000000000000000000000000000000
3 operation uint8 0
4 safeTxGas uint256 254794
5 baseGas uint256 0
6 gasPrice uint256 0
7 gasToken address 0x0000000000000000000000000000000000000000
8 refundReceiver address 0x0000000000000000000000000000000000000000
9 signatures bytes 0x000000000000000000000000e3f4f3ad70c1190ec480554bbc3ed30285ae0610000000000000000000000000000000000000000000000000000000000000000001

from telegram: @bitbeckers 

As such, the actual tx data is in the data field.

The regular transaction has this input:

# Name Type Data
0 account address 0x22E4b9b003Cc7B7149CF2135dfCe2BaddC7a534f
1 units uint256 3
2 merkleRoot bytes32 0x7b5f262c15d0de0b3c31d60452264a16f6d3a60f679f32cf5511dc36229edcb8
3 _uri string ipfs://bafkreifw2oxd5sv2iujmx53bgt5j5k6v4wpuivjq52svfyc5tksxylabyu
4 restrictions uint8 2

So if you try to map the Safe-tx on the ABI there's no matching function to be found, suggesting that's the cause of the error.

The purpose of the processing by OZ Defender appears to be to get the TX to get the URI in the input. You can bypass this by using the tokenID from the AllowlistCreated event and read it from the contract by calling uri(tokenID).

### Expected Behavior

It should be possible to mint a hypercert from an Optimism multisig

**Comment by ryscheng** [comment]
Here's an issue with more details
https://github.com/hypercerts-org/hypercerts/issues/512

**Comment by bitbeckers** [comment]
in #898

**Comment by bitbeckers** [comment]
Reopened because we cannot test because of WallecConnect V2 + wagmi issues:

Finally found the issue that describes the problem: https://github.com/orgs/WalletConnect/discussions/2733
And some wagmi+rainbowkit specific info here: https://github.com/rainbow-me/rainbowkit/issues/1323

**Comment by bitbeckers** [comment]
Been able to mint with https://github.com/bitbeckers/hypercert-safe-minter
