### ISSUE TITLE
[bug/dapp] users with Rabby wallet are unable to connect to the dapp

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#636]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

A user originally posted this issue [via Twitter](https://twitter.com/TimSmith1337/status/1655654214301786147?s=20). 

I was then able to reproduce the issue by trying to connect via Rabby wallet. 

I think this is an issue with our "connect" widget rather than the dapp. 

Note: I was able to connect using Rabby to other dapps like Uniswap. 

### Describe the Bug

When the user tries to connect with Rabby wallet, the modal does not include an option for Rabby. In this case, normal behavior would be to try connecting to Rabby via MetaMask. However, the browser does not detect that MetaMask is installed.

See below for a screenshot.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/42869436/236924033-47785e3a-ba3d-4277-81d7-fcec3bf73935.png">

### Expected Behavior

A user should be able to connect via Rabby, either directly (eg, Uniswap) or via Metamask (eg, OpenSea). 

Here is a screenshot of the proper behavior of connecting via MetaMask on OpenSea.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/42869436/236925023-0b52e0c3-49fb-4f09-8121-77dbdd16988b.png">

**Comment by bitbeckers** [comment]
This is what I've added now (screenshot). Do we want to expose the full list @ryscheng @ccerv1?

In RainbowKit:
```js
import { argentWallet } from './argentWallet/argentWallet';
import { bitskiWallet } from './bitskiWallet/bitskiWallet';
import { braveWallet } from './braveWallet/braveWallet';
import { coinbaseWallet } from './coinbaseWallet/coinbaseWallet';
import { dawnWallet } from './dawnWallet/dawnWallet';
import { imTokenWallet } from './imTokenWallet/imTokenWallet';
import { injectedWallet } from './injectedWallet/injectedWallet';
import { ledgerWallet } from './ledgerWallet/ledgerWallet';
import { metaMaskWallet } from './metaMaskWallet/metaMaskWallet';
import { mewWallet } from './mewWallet/mewWallet';
import { okxWallet } from './okxWallet/okxWallet';
import { omniWallet } from './omniWallet/omniWallet';
import { phantomWallet } from './phantomWallet/phantomWallet';
import { rabbyWallet } from './rabbyWallet/rabbyWallet';
import { rainbowWallet } from './rainbowWallet/rainbowWallet';
import { safeWallet } from './safeWallet/safeWallet';
import { tahoWallet } from './tahoWallet/tahoWallet';
import { trustWallet } from './trustWallet/trustWallet';
import { walletConnectWallet } from './walletConnectWallet/walletConnectWallet';
import { xdefiWallet } from './xdefiWallet/xdefiWallet';
import { zerionWallet } from './zerionWallet/zerionWallet';
```

<img width="762" alt="Screenshot 2023-06-23 at 16 59 04" src="https://github.com/hypercerts-org/hypercerts/assets/19667964/739c1434-1b3e-4ac5-a7dc-756d35577676">

**Comment by ryscheng** [comment]
I guess it doesn't hurt. Thanks @bitbeckers
