### ISSUE TITLE
Minimum governance for hypercerts first draft

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#637]
https://docs.google.com/document/d/1_UzgF3BKpqYfWB6V-NK9SxDvFMP9epmrU9AXw1Fe57g/edit?usp=sharing

**Comment by ryscheng** [comment]
https://docs.google.com/document/d/1b659qaaK2CxWdXf2BqEE4pQw9INIGFHd8ROOWUngfHk/edit?usp=sharing

**Comment by holkeb** [comment]
@ryscheng @ccerv1 the current doc is ready for review: https://docs.google.com/document/d/1_UzgF3BKpqYfWB6V-NK9SxDvFMP9epmrU9AXw1Fe57g/edit?usp=sharing

**Comment by ryscheng** [comment]
left some comments, but I really like the direction of a protocol fee that goes into a Gitcoin matching pool!
As per our convo today, can we create an epic for this line of thinkig and what work needs to be done to get there?
