### ISSUE TITLE
[os] define v1 schema for projects, events, etc

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#641]

**Comment by ccerv1** [comment]
Current v0 [here](https://github.com/hypercerts-org/hypercerts/blob/main/utils/os-observer/data/schema.sql)

**Comment by ccerv1** [comment]
Closing this out after today's discussion [here](https://miro.com/app/board/uXjVMIJ65QM=/?share_link_id=413971542086). 

@jmoggr feel free to open separate issues for any of the following next steps:
- create a schema and migration framework on prisma
- refactor fetching scripts to achieve idempotence
- create 1-2 precomputed tables (eg, daily events buckets)

**Comment by ryscheng** [comment]
yep, I added some issues here:

https://github.com/hypercerts-org/hypercerts/issues/667
https://github.com/hypercerts-org/hypercerts/issues/666
https://github.com/hypercerts-org/hypercerts/issues/665
