### ISSUE TITLE
Development branch for contracts

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#649]
### Describe the feature you'd like to request

There are community proposals incoming for gas optimisation on the contracts. To keep `main` representative of the production deployment, in theory those optimisations can not be merged into `main`.

### Describe the solution you'd like

`develop` branch that funnels in (contract) changes that cannot be pushed to production.

### Describe alternatives you've considered

Keeping PR branches open but that can become noisy pretty quick

**Comment by ryscheng** [comment]
Makes sense to me, going to backlog this until we start working on the contracts again

**Comment by bitbeckers** [comment]
for #732 this will need to happen

**Comment by bitbeckers** [comment]
@ryscheng can you make the branch `contract/develop` protected? I don't have the rights

**Comment by ryscheng** [comment]
Done. I also upp'ed the permission level for the entire 'dev' team, which you're on
