### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'FromCreatorOnly')  

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#654]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Trying to create [this hypercert](https://testnet.hypercerts.org/app/create#name=Earthist%20-%20Gitcoin%20Alpha&description=%23%23%23%20Some%20accomplishments%20through%20gift%20economy%0A%0A-%20Over%206%20million%20heirloom%20seeds%20have%20been%20planted%20in%20five%20cities%20to%20provide%20support%20for%20hemp%20farmers%20in%20our%20network%2C%20both%20new%20and%20experienced.%0A-%20Established%20a%20physical%20hub%20where%20we%20hosted%20events%20and%20workshops%20to%20accelerate%20progress%20towards%20regenerative%20development%20solutions.%0A-%20Assisted%20disaster%20zone%20victims%20with%20hemp-based%20remedies.%0A-%20Collaborations%20with%20Digital%20Gaia%20and%20RegenForge%0A-%20Onboarded%2017%20new%20community%20members%20and%20established%20seed%20banks%20in%202%20cities.&externalLink=https%3A%2F%2Fearthist.network&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreiboym44w2hqgqhfvsdpfip6cmb2ayt644k3yvvovy5eopjt6k3goa&bannerUrl=https%3A%2F%2Fbafybeifrnuuehyhnky3zwgwkxwjmpuzkmewj3hfvfzmyqjnycfevfom6tq.ipfs.w3s.link%2Fimages%2FEarthist_-_Decentralize_Hemp_Seeds.png&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=Earthist%20Network&workTimeStart=2022-09-22&workTimeEnd=2023-01-15&rights%5B0%5D=Public%20Display&contributors=0xc2d706398A978b8c5Aa4EFCd824b57E978841107%2C%20alienseeker.eth%2C%20earthist.eth%2C%20unquale.eth%2C%20sohto.eth&allowlistUrl=https%3A%2F%2Fbafybeiah37sarihszhoe3mzydrqctinpust2hej2g2k34umqf3i4dwhpoy.ipfs.w3s.link%2Fallowlists%2FEarthist_-_Decentralize_Hemp_Seeds.csv&allowlistPercentage=50&agreeContributorsConsent=true&agreeTermsConditions=true&backgroundColor=green&backgroundVectorArt=circles&metadataProperties=%5B%7B%22trait_type%22%3A%20%22Funding%20Platform%22%2C%20%22value%22%3A%20%22Gitcoin%20Grants%22%7D%2C%20%7B%22trait_type%22%3A%20%22Funding%20Round%22%2C%20%22value%22%3A%20%22Alpha%20Round%22%7D%2C%20%7B%22trait_type%22%3A%20%22Matching%20Pool%22%2C%20%22value%22%3A%20%22Climate%20Solutions%22%7D%5D&impactTimeStart=2022-09-22) on both Goerli and Optimism. 

When a user tries to mint, the following error appears before the contract interaction gets triggered.

> TypeError: Cannot read properties of undefined (reading 'FromCreatorOnly')  

### Describe the Bug

Here is the log:

```
instrument.js:109 HypercertsClient is in readonly mode
instrument.js:109 HypercertsClient signer:  undefined
instrument.js:109 HypercertsClient provider:  A
instrument.js:109 HypercertsClient contract address:  0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07
instrument.js:109 HypercertsClient storage:  lQ
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/_next/data/kPudJJzOEWlawnw4SZNvJ/docs.json?catchall=docs:1     Failed to load resource: the server responded with a status of 404 ()
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.js:109 Submitting form...
instrument.js:109 Form values:  Object
instrument.js:109 Form errors:  Object
instrument.js:109 Metadata(valid=true):  Object
instrument.js:109 true Object
instrument.js:109 Trouble parsing error Object
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'FromCreatorOnly')
    at c (mintClaimAllowlistSDK.ts:100:9)
    at async write (mintClaimAllowlistSDK.ts:138:7)
    at async onSubmit (hypercert-create.tsx:384:15)
(anonymous) @ instrument.js:109
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.js:109 Submitting form...
instrument.js:109 Form values:  Object
instrument.js:109 Form errors:  Object
html2canvas.js:5353 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
A.createCanvasClone @ html2canvas.js:5353
instrument.js:109 Metadata(valid=true):  Object
instrument.js:109 true Object
instrument.js:109 Trouble parsing error Object
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'FromCreatorOnly')
    at c (mintClaimAllowlistSDK.ts:100:9)
    at async write (mintClaimAllowlistSDK.ts:138:7)
    at async onSubmit (hypercert-create.tsx:384:15)
(anonymous) @ instrument.js:109
DevTools failed to load source map: Could not load content for chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content-script/contentScript.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content-script/inpageSol.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
fetch.js:41     POST https://o4504964060807168.ingest.sentry.io/api/4504964062773248/envelope/?sentry_key=4ad08a36e373438b8b96f7dad9881b34&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.47.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.js:41
c @ base.js:52
add @ promisebuffer.js:41
s @ base.js:68
_sendEnvelope @ baseclient.js:583
_flushOutcomes @ client.js:134
(anonymous) @ client.js:45

```

### Expected Behavior

The Hypercert should mint as usual

**Comment by ryscheng** [comment]
Reverting the change here
https://github.com/hypercerts-org/hypercerts/pull/655
