### ISSUE TITLE
numeric values are being returned by the hypercerts fetcher as strings

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#657]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

The Graph integration

### To Reproduce

Go to our graph instance: https://thegraph.com/hosted-service/subgraph/hypercerts-admin/hypercerts-optimism-mainnet

Enter this query:

```
{
  claims(first: 5) {
    id
    creation
    tokenID
    totalUnits
    contract
  }
}
```

### Describe the Bug

Values that should be integers are displayed as strings

<img width="545" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/42869436/2417ed5a-c958-4320-bc0e-2e7e42b64a8c">

### Expected Behavior

The values should be stored as integers

**Comment by ccerv1** [comment]
@ryscheng update: needs to be resolved on the fetcher, not the indexer per telegram convo

**Comment by ravenac95** [comment]
After some exploration of how all of this is mapped (and some setup for my env) I have a couple ways forward. Currently I see this is used like 

```
${($ctx.hypercertData.claimTokens.filter(t => t.owner === $ctx.DappContext.myAddress.toLowerCase()).map(t => Math.round(t.units)).reduce((a, c) => a + c,0)*100.0/Math.round($ctx.hypercertData.claim.totalUnits)).toPrecision(3)}%
```

Unfortunately, if I turned it into a BigInt type (as it should be) then the math functions wouldn't work. I can easily come up with a solution but that'll change how we end up using it in plasmic so here are a couple options I'm leaving out here for input. In either option, I would turn the BigInt values correctly into BigInt javascript types.

### Option 1

I can expose a `utils` object on the `$ctx` object that has some functions to do `BigInt` arithmetic. This feels a bit messy to me. 

### Option 2

Based on the way I'm looking at this, it doesn't seem like we'd do much more than calculate the percentage. It would be simple enough to simply calculate the percentage of every ClaimToken and put it into `$ctx.hypercertData` as either a specific property or (my preference) some kind of method like `claimPercentageByOwner(t.owner)`.

---

I have a personal preference for option 2 and will implement when I get up early tomorrow if no one has any feedback. I think it might be best to have this be a method of `Claim` (e.g. `$ctx.hypercertData.claim.percentageByOwner(t.owner)`). Though the existence of `Claim` and `ClaimTokens` at the same level in the `hypercertsData` object makes that a little less clean.

**Comment by ryscheng** [comment]
Yep that seems pretty clean! Especially since an owner could end up owning multiple fraction tokens.

**Comment by ryscheng** [comment]
@ravenac95 didn't you already do something here? is this done?

**Comment by ravenac95** [comment]
Oh hrm didn't realize this wasn't closed. Yes it's done!
