### ISSUE TITLE
Protocol Transaction Fees design

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#662]
### Describe the feature you'd like to request

We've discussed potentially having fees at the protocol layer for some subset of these reasons:
- Sustain protocol development
- Impact evaluations

And it's an open question what should happen at the protocol layer vs the marketplace app layer

### Describe the solution you'd like

I suppose this is just a placeholder for us to decide what we want to do here as an initial step

### Describe alternatives you've considered

To be discussed

**Comment by bitbeckers** [comment]
Closing this in favor of the HypercertTrader royalty flow refinements
