### ISSUE TITLE
SDK: Live Graph polling

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#674]
@ryscheng UX wise, which queries are reasonable to have live (polling every x-seconds)?

- [x] fractionsByOwner
- [x] fractionsByClaim
- [ ] fractionsById
- [x] claimsByOwner
- [x] claimById
- [ ] firstClaims

_Originally posted by @bitbeckers in https://github.com/hypercerts-org/hypercerts/issues/548#issuecomment-1551644624_

**Comment by ryscheng** [comment]
Oh interesting, are you adding convenience functions to capture this pattern?
https://thegraph.com/docs/en/querying/distributed-systems/#polling-for-updated-data

I guess it doesn't hurt to just do it for most queries?

**Comment by bitbeckers** [comment]
Want to add those functions yes. But the return type is different (`AsyncItterable`). We can discern live-static by prefixing the methods with something like `subscribeTo`

**Comment by bitbeckers** [comment]
@ryscheng had the experience in a differnt project that using ReactQuery on the FE like this is way more efficient than working on the GraphQL level, plus it leaves the GraphClient less opiniated.

```js
const query = useQuery(
  key,
  fn,
  {
    refetchInterval: (data) => !data || data.progress < 100 ? 5000 : undefined
  }
)
```

So my proposal would be to implement this in the FE. Agreed?

**Comment by ryscheng** [comment]
sgtm

**Comment by bitbeckers** [comment]
in #879
