### ISSUE TITLE
Should we rename the npm name for sdk/ and contracts/?

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#676]
### What is it?

Proposing:
- @hypercerts-org/hypercerts-sdk => @hypercerts-org/sdk
- @hypercerts-org/hypercerts-protocol => @hypercerts-org/contracts

**Comment by ryscheng** [comment]
Shortened the package names for `docs`, `frontend`, `graph`, here
https://github.com/hypercerts-org/hypercerts/pull/677

Leaving the 2 mentioned above until we discuss, since it involves moving things in our npm registry

**Comment by bitbeckers** [comment]
Could be a good cutoff point for #681
