### ISSUE TITLE
Burn a hypercert

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#690]
### Describe the feature you'd like to request

Was searching for this, but didn't find an existing issue for it...

### Describe the solution you'd like

On the view hypercert page, I should have an action button if I own a fraction to burn my fraction token.

### Describe alternatives you've considered

Maybe this should be on the dashboard too?

**Comment by ryscheng** [comment]
Ah, I see the hook here
https://github.com/hypercerts-org/hypercerts/pull/658/files

but it's not actually exposed in the Dapp. I wouldn't close this as done until we actually have it working end to end

**Comment by ccerv1** [comment]
@bitbeckers I spoke with a user today who wants to burn a hypercert. we should monitor for activity to see if this happens

**Comment by bitbeckers** [comment]
<img width="1119" alt="Screenshot 2023-05-27 at 15 31 15" src="https://github.com/hypercerts-org/hypercerts/assets/19667964/a06a7cb4-8353-4c58-945c-c73bfc77ee86">

[Transaction](https://goerli.etherscan.io/tx/0x4d7179323ee29333e7b589d9a2854bb5f3086c137c14e17038ebc212ac1dbf74)

Burn is live
