### ISSUE TITLE
claimIDs associated with failed BatchMintClaimsFromAllowlists calls appear as claimable but cannot be claimed

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#697]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp, The Graph integration

### To Reproduce

I believe these steps should reproduce the error:
1. Create a hypercert with an allowlist
2. Attempt to claim the hypercert but fail (eg, not enough gas)
3. Go to your [dashboard](https://hypercerts.org/app/dashboard)

You should see something like this: claimable hypercerts but the claim all fractions button is disabled 
![image](https://github.com/hypercerts-org/hypercerts/assets/42869436/45739723-8d08-4f22-974b-bc11bf51f9ba)

### Describe the Bug

It would appear that `hypercertFetcher` is not able to filter `claimIDs` associated with failed `BatchMintClaimsFromAllowlists` events. This has happened to [at least 30 users](https://optimistic.etherscan.io/txs?a=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07&f=1&fromaddress=0x78c18a8d367D490aA79E38e321FecA0c6552F69C) so far.

### Expected Behavior

A user should see an active "claim all fractions" button on their dashboard after a failed attempt

**Comment by ryscheng** [comment]
Just simulated the user's dashboard and got this:

![Screen Shot 2023-05-22 at 17 16 28](https://github.com/hypercerts-org/hypercerts/assets/566890/aef6e560-545b-47ab-9e5a-f46c74c08397)

my guess is that this has to do with the 5 minute cooldown for the button

**Comment by ryscheng** [comment]
@ccerv1 is it okay to close this? I don't know how to replicate
