### ISSUE TITLE
zuzalu form: adding new input field to form

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#721]
1. I added a field on plasmic with fieldName "textForSponsor". This would need to be added to the form, such that the content will be stored on supabase.
2. We want to add another hypercert, which would need to be added to the form as well, i.e. "percentBuyingZuzalu023"

**Comment by ryscheng** [comment]
@holkeb I added a first draft of code here
https://github.com/hypercerts-org/hypercerts/pull/730

But I'd want to test these with the Plasmic changes before deploying. Where can I find those?

**Comment by holkeb** [comment]
The new textbox is just above the purchase button, but hidden.

And I just added the new hypercert as the last one of the first category, i.e. after the "Zuzalu: Ticketing". It is called "Zuzalu: StreamETH", it's hidden as well.

**Comment by ryscheng** [comment]
@holkeb 
can you do me a favor and unhide the 23'rd hypercert section?
Idk why I can't find it...

Feel free to close this after testing

**Comment by holkeb** [comment]
Done @ryscheng 

<img width="568" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/103380539/685fb517-68f6-447d-a81b-9eccf5e3d6b4">
