### ISSUE TITLE
[os] Rewrite GitHub fetching scripts as idempotent Typescript

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#743]
### Describe the feature you'd like to request

https://github.com/hypercerts-org/hypercerts/blob/main/os-observer/src/events/github_events.py
Thanks Carl for getting this started!

### Describe the solution you'd like

This needs to be rewritten as idempotent Typescript functions that can be plugged into the os-observer CLI and library. See here for how that's set up: https://github.com/hypercerts-org/hypercerts/pull/741

If we write it in TS connected to this harness, it should automatically work in the following environments:
- From the command-line
- From GitHub actions (manually triggered atm)
- Exported as a library (see frontend/ for an example of usage)
- From an API (currently exposed at https://www.opensource.observer/api/*)

### Describe alternatives you've considered

Sticking to Python

**Comment by jmoggr** [comment]
https://github.com/hypercerts-org/hypercerts/pull/761

**Comment by jmoggr** [comment]
Done!
