### ISSUE TITLE
Planning next steps for Zuzalu hypercerts

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#745]
Main question: How do we do sales after we created the hypercerts?

**Comment by holkeb** [comment]
1. enable transferability for Zuzalu hypercerts
2. create hypercerts from zuzalu.eth and distribute to funders
3. allow additional purchases of Zuzalu hypercerts from the contributors

number 3 is non-trivial to implement right now
- Option A: we split the hypercerts into different "packages", e.g. some are 0.1%, some 1%, some 5%, at the time of minting the hypercerts that are all owned by zuzalu.eth. Currently having multiple fractions assigned to the same address in an allowlist combines all these fractions. We would have to turn that feature off, which seems doable (correct me if I'm wrong @ryscheng). Then these pre-split packages could be sold on OpenSea
- Option B: we implement split & merge and sell on OpenSea fully, which allows zuzalu.eth to split and sell hypercerts on OpenSea quite flexibly 
- Option C: we keep the current payment mechanism and add a disclaimer that the distribution of hypercerts is pending availability of them (if they aren't available people can get their money back or get claims on future hypercerts), in this case we would also need to implement the full split functionality as funders can fund it in arbitrary amounts

@ryscheng is Option A something that would be reasonable to implement in the next sprint? (option B and C seem out of scope)

**Comment by ryscheng** [comment]
Can we clarify? Are we talking about subsequent sales or are we talking about the ones where people already sent money to zuzalu.eth?

If the latter, Option A is confusing, didn't the ETH already get transferred? Why not just create an allowlist with all the addresses who contributed?

**Comment by holkeb** [comment]
Yes, this is for subsequent sales @ryscheng 

1) Pre-sale to zuzalu.eth (this is happening right now)
2) zuzalu.eth mints hypercerts with an allowlist from the pre-sale
3) zuzalu.eth still has a significant amount of fractions
4) zuzalu.eth offers those fractions for sale on zuzalu.hypercerts.org with a link to a correctly sized and listed fraction for sale on OpenSea
5) Transaction is done on OpenSea

In order to do this, I think we need to 
- split the hypercert at the point of minting in multiple fractions that zuzualu.eth owns (currently they all would be merged if listed in the allowlist separately)
- find a way to link to the correct fraction on OpenSea that isn't yet sold (= is owned by zuzalu.eth)

**Comment by holkeb** [comment]
ps.: i wrote in the first post: buy from the contributors, it is probably easier if it is managed by zuzalu.eth
