### ISSUE TITLE
[FE] Make hypercerts transferable

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#746]
Enabling transferability on the backend, such that we can create a frontend that creates transferable hypercerts (i.e. all hypercerts from a particular frontend are transferable) or where the minter decides on the transfer restrictions.

**Comment by bitbeckers** [comment]
My proposal would be to have a dropdown in the claim form that allows a hypercert creator to select the transfer restrictions. Thoughts?

**Comment by holkeb** [comment]
Depends on the application. For some we might still want to have no choice for the user on the frontend

**Comment by bitbeckers** [comment]
@holkeb do you want this in the HC frontend? Otherwise we can close this issue since it's not in scope or planned

**Comment by holkeb** [comment]
Not in the frontend for now
