### ISSUE TITLE
UX/UI: List hypercert for sale by owner

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#754]
### Describe the feature you'd like to request

In v0 of the marketplace a minter can set a price and the maximum of how many fractions she wants to sell for this price. The minter can also set for how long the hypercert should be listed.

This should be used by minters for primary sales of hypercerts.

Open question: Should this be available for all owners or just for the minter? Answer for now: I assume we can build it for owners in general and enable it only for minters for now.

### Describe the solution you'd like

On OpenSea this feature looks like this
<img width="592" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/103380539/6c8a79eb-2d3e-478e-b86f-e722f0e9ff24">

### Describe alternatives you've considered

- Selling on OpenSea

**Comment by bitbeckers** [comment]
@holkeb:
1. This implied a deadline on a sellOffer, which I can put in scope in #1081 if you agree
2. Do we need designs from @eirena for the marketplace UI so @Jipperism knows what to implement?

**Comment by holkeb** [comment]
The deadline is a nice-to-have feature. It could also be just there as long as the user doesn't cancel it manually.

**Comment by bitbeckers** [comment]
In marketplace app
