### ISSUE TITLE
UX/UI: funders can directly buy listed hypercerts

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#755]
### Describe the feature you'd like to request

In https://github.com/hypercerts-org/hypercerts/issues/754 we build the UI/UX for owners to list hypercerts for sale. When they are listed, funders need to be able to discover them and be able to directly buy them, specifying how much they want to buy (up to the max. specified by the owner)

### Describe the solution you'd like

On OpenSea this looks like this:
<img width="621" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/103380539/c39bcfa7-3c5e-4f75-a448-65f5878721aa">

### Describe alternatives you've considered

- Buying on OpenSea

**Comment by bitbeckers** [comment]
Closing since this is currently in hyperboards.org
