### ISSUE TITLE
feat: owners can list hypercerts for sale

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#756]
### Describe the feature you'd like to request

In https://github.com/hypercerts-org/hypercerts/issues/754 we build the UI/UX for owners to set a price and amount to directly sell on hypercerts.org.

This issue concerns the backend operations necessary for this feature. 

### Describe the solution you'd like

Owners select
- a price
- a maximum amount of fractions they want to sell for this price (default: all they own)
- (optionally) a expiration date of listing the fractions for this price (default: no expiration date)

This gets stored, such that it can be displayed to funders, and a purchase an be triggered automatically when a funder buys fractions directly.

### Describe alternatives you've considered

- listing on OpenSea

**Comment by bitbeckers** [comment]
@holkeb @ryscheng Is the goal platform only OpenSea for now? Using their SDK is probably the smoothest experience, one step above directly linking to OpenSea and letting users handle them

**Comment by ryscheng** [comment]
sgtm. we can revisit this later after we've done some sales :-)

**Comment by bitbeckers** [comment]
Closing this in favor of hyperboards development
