### ISSUE TITLE
feat: direct sale of listed hypercerts

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#757]
### Describe the feature you'd like to request

We have the UX/UI for listing a hypercert for sale by the owner (https://github.com/hypercerts-org/hypercerts/issues/754) and for buying it directly (https://github.com/hypercerts-org/hypercerts/issues/755). 

https://github.com/hypercerts-org/hypercerts/issues/756 describes that owners can list a hypercert for sale.

This feature concerns the actual transaction. 

### Describe the solution you'd like

- Funder clicks on "buy now" on a hypercert
- Funder enters how many fractions she wants to buy (up to the total amount available for sale)
- Funder confirms transaction
- Funds are transferred to owner
- Fractions are transferred to funder

### Describe alternatives you've considered

- selling on OpenSea

**Comment by bitbeckers** [comment]
Closing this in favor of hyperboards developments
