### ISSUE TITLE
UI/UX: split and merge value on a hypercert they own and link to OpenSea to sell fraction

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#758]
### Describe the feature you'd like to request

hypercerts can be split and merged, see this issue for the backend feature: https://github.com/hypercerts-org/hypercerts/issues/13

This issue concerns updating the UI/UX. It includes the link to sell on OpenSea as this is one of the reasons to split hypercerts.

### Describe the solution you'd like

Simple and intuitive way to split and merge hypercerts

### Describe alternatives you've considered

-

**Comment by bitbeckers** [comment]
Covered in #13
