### ISSUE TITLE
UX/UI: dashboard clusters hypercerts according to the work scope

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#768]
hypercerts are displayed in clusters, such that a project sees how it creates series of hypercerts that represent their full project over time

We can potentially show a 2d impact space with work scope on the y-axis and time of work on the x-axis.

**Comment by bitbeckers** [comment]
Closing in favor of https://github.com/hypercerts-org/HIPs/discussions/5
