### ISSUE TITLE
feat: integrate billboard or leaderboard with hypercert on-chain data

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#771]
Currently the data for the billboard is manually uploaded as a JSON. When we mint the hypercerts and have the data on-chain, the billboard should ideally be connected to the live data from the hypercerts, e.g. if ownership changes, the billboard changes as well.

This requires storing data about which hypercerts are part of the billboard / collection somewhere, e.g. using the defined collections in supabase

If we implement a leaderboard (ranked list of sponsors), it should also be linked to the ownership structure of the hypercerts

**Comment by bitbeckers** [comment]
Closing since this is implicit in hyperboards. We could refine a leaderboard if you want that @holkeb
