### ISSUE TITLE
feat: A minter can assign multiple fractions to the same address in the allowlist that do NOT get merged

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#784]
### Describe the feature you'd like to request

Use case: For the zuzalu hypercerts, the zuzualu.eth as the minter can create multiple fractions that zuzalu.eth will own, such that they can be sold afterwards.

### Describe the solution you'd like

Current behavior: If an allowlist contains multiple rows with the same address, the corresponding fractions will be summed up and the address owns a single fraction.

Desired behavior: If an allowlist contains multiple rows with the same address, the address receives a fraction per row that is as big as specified.

Open question: Do we want this to be a feature that can be turned on and off on the frontend? i.e. for the Gitcoin use case it is useful that the fractions are merged

### Describe alternatives you've considered

The full split and merge feature, such that the hypercert could be split after the minting process. See https://github.com/hypercerts-org/hypercerts/issues/745

**Comment by ryscheng** [comment]
I am not convinced that https://github.com/hypercerts-org/hypercerts/issues/785 and https://github.com/hypercerts-org/hypercerts/issues/784 are worthwhile issues to pursue. 

They involve a lot of one-off work that will mostly be thrown away when we implement
https://github.com/hypercerts-org/hypercerts/issues/756

I'd rather just invest in 756, which would take a comparable amount of work.

**Comment by holkeb** [comment]
We discussed 784 and 785 as the next steps here: https://github.com/hypercerts-org/hypercerts/issues/745

But 756 is what we really want, so happy to go with that (it seems like more work to me, but happy if that's not the case). Let's discuss when we could expect that to work

**Comment by ryscheng** [comment]
Sorry about the confusion, I think I understand the purpose of this now ----

We want to be able to pre-split a hypercert into fractions for the owner at mint time, because that is the only UX where the owner issues a transaction at the moment.

Maybe this is setup as a hidden query string parameter like we do for background art.
We do need to make sure that claim all fractions properly lets us claim multiple fractions for the same hypercert though.

**Comment by bitbeckers** [comment]
>  We do need to make sure that claim all fractions properly lets us claim multiple fractions for the same hypercert though.

There's nothing blocking this in the SDK or the contracts iirc

**Comment by ryscheng** [comment]
Ya just worth testing the flow end to end to double check. But you're probably right

**Comment by bitbeckers** [comment]
Sanity checking: We assume the allowlist creator understands the content of the allowlist and when there are multiple lines with the same address, we won't aggregate the value. 

If not, I think we can add a toggle/checkbox/switch that states "Group identical addresses".

**Comment by holkeb** [comment]
@bitbeckers yes, exactly, that is what we assume. Use case here is that I can assign two (or more) different fractions to myself to sell them on OpenSea.

I like the option to "Group identical addresses" if users don't want this to happen.

**Comment by bitbeckers** [comment]
@ryscheng we probably want a smart way to handle this in supabase. In theory, a user can claim 1 of multiple tokens from the same cert. We currently have a pair of address-claimID but we probably want something like address-claimID-index. Index because we don't know the tokenID before the mint

**Comment by ryscheng** [comment]
@bitbeckers I think Holke needs this to mint the Zuzalu hypercerts this week if possible?
CC @holkeb
