### ISSUE TITLE
feat: a funder can discover hypercerts on hypercerts.org and buy fractions on OpenSea

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#785]
### Describe the feature you'd like to request

Use case: A funder who discovers hypercerts on zuzalu.hypercerts.org is able to buy the fraction.

### Describe the solution you'd like

The UI/UX could look like this:

![image](https://github.com/hypercerts-org/hypercerts/assets/103380539/5cd08f89-297e-459c-a6f5-fe4604223ea9)

![image](https://github.com/hypercerts-org/hypercerts/assets/103380539/8bbb40cc-8455-4413-80bf-90913d335361)

we split the hypercerts into different "packages", e.g. some are 0.1%, some 1%, some 5%, at the time of minting the hypercerts that are all owned by zuzalu.eth. Then these pre-split packages could be sold on OpenSea

In supabase we can have a table with all hypercert fractions and their link to OpenSea. We would only need to add to the table a column that automatically shows if the owner is zuzalu.eth or not. The buy button then links to one hypercert of the size that the user selected that is owned by zuzalu.eth (we ensure that all of these are listed for the set price). If such a hypercert is not available, the dropdown says "sold out".

### Describe alternatives you've considered

full split, merge and sell feature: see https://github.com/hypercerts-org/hypercerts/issues/745

**Comment by ryscheng** [comment]
I would prefer not to continue building these one-off features, unless there is an exceptionally incredible opportunity to get in front of the right audience. Can you estimate how many people you expect to buy hypercerts this way? 

I would be in favor of spending any scarce engineering time on just building the actual quick checkout feature we wanted to build

**Comment by ryscheng** [comment]
I appreciate you're trying to come up with a fast alternative to building the full feature, but from what I can tell, this is not it...

**Comment by holkeb** [comment]
it is what we discussed https://github.com/hypercerts-org/hypercerts/issues/745 and we agreed that we probably should do it this way. Let's discuss it such that I'm not wasting time to think through these issues if they aren't the right direction

**Comment by ryscheng** [comment]
@holkeb can we do a simpler?

Assuming that we've already pre-split the fractions into parts:
If the hypercert is transferrable or TransferRestrictions==FromCreatorOnly and I'm the owner, then give me the ability to mark which fractions are for sale (potentially through OpenSea).

Once we do that, we can see if we have bandwidth to make a nicer UX

**Comment by bitbeckers** [comment]
In https://github.com/hypercerts-org/HIPs/discussions/5
