### ISSUE TITLE
bug: missing provider error popping up for users

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#787]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

multiple users have reported getting this error; we're not sure what's causing it and @bitbeckers was not able to reproduce. we just tried and were unable to reproduce the error on goerli.

### Describe the Bug

the user is unable to mint a pre-populated hypercert from a minting link we've provided. they get a "missing provider" pop up.

### Expected Behavior

they should be able to do batch minting from an allowlist, or receive a more verbose error if there's an issue with their setup

**Comment by bitbeckers** [comment]
Not sure what to do with this right now if we can't reproduce..

**Comment by ccerv1** [comment]
Yeah ... here's another that just had it too. And it went away mysteriously again...

<img width="695" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/42869436/3e545bd8-b438-4bd3-bce3-10b80e7090ce">

**Comment by ccerv1** [comment]
@bitbeckers I've put this in the backlog until we learn more

**Comment by bitbeckers** [comment]
Investigating. 

* Error not logged by SDK or anything in the monorepo

<img width="332" alt="Screenshot 2023-06-13 at 15 24 21" src="https://github.com/hypercerts-org/hypercerts/assets/19667964/499ae207-b1d9-4338-a74a-658b64e5475e">

**Comment by bitbeckers** [comment]
Reproduced the bug by first trying to mint on the wrong network (`mainnet`) and then switching to a supported one (`goerli`)

**Comment by ccerv1** [comment]
Do you think this is the only cause of the bug?
