### ISSUE TITLE
Ensure compatibility and conceptual consistency between hypercerts and IP-NFTs (Molecule)

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#80]
https://www.molecule.to/blog/introducing-ip-nft-v2

**Comment by ryscheng** [comment]
Braindumping some notes here from my last call with Stefan:
- Using an 1155 contract. Main difference from reference implementation is the ability to "reserve" a token ID that is minted later. Important for their legal IP integration.
- Fractionalization of IP-NFTs is an important early requirement.
