### ISSUE TITLE
bug: if a user's claimAllFractions transaction fails, their fractions should remain in the allowlist cache

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#813]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

- Perform a `claimAllFractions` call without enough to gas to cover the full transaction (ideally there should be enough for it to claim some but not all fractions)
- The fractions should no longer be claimable on the dApp (and removed from the Supabase cache)

[Here](https://optimistic.etherscan.io/tx/0x0ecbb80fdf467f600c68d8f4cf2b97795ba30d6b7e7333b114a2fa1f4f96ec49) is an example.

### Describe the Bug

When a transaction reverts, Supabase still thinks it has gone through and removes the user's claims from the allowlist cache. 

### Expected Behavior

If the user does not own their hypercert fraction yet, and it hasn't been marked as "hidden", then it should be claimable through the dapp regardless of whether a previous transaction failed or not.

**Comment by ryscheng** [comment]
Feel free to make a PR and tag me for review. 
The CD only deploys on pushes/merges to main.

The CD will blow away all Defender Autotasks and re-create them for both goerli and optimism. Quite destructive, esp if we need logs. 

Is there anyway to neuter update the autotasks in place so we can preserve logs?

**Comment by ryscheng** [comment]
ya we probably want both. I think the first item is what we meant in issue #400 
I don't think we have an issue for the second item, but a good idea nonetheless!

**Comment by bitbeckers** [comment]
Tested with this tx: https://goerli.etherscan.io/tx/0xed53394faf7cd9c8892e4cfc4e1b3442004e33c4ade805a30b42a0518889056f

Cert remained visible as claimable and the Defender task aborted
