### ISSUE TITLE
If the allow list is invalid, after the error the progress indicator doesn't close

### ISSUE THREAD

**Issue by dysbulic** [hypercerts-org/hypercerts#836]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Create a Hypercert with an invalid allowlist. After being told to check the console for errors *(where there weren't any)*, the progress indicator remains even though the process has been aborted.

![Screenshot from 2023-06-13 15-03-24](https://github.com/hypercerts-org/hypercerts/assets/181523/fdf4bcda-68a1-4e7c-969a-0ae01f46b349)
![Screenshot from 2023-06-13 14-56-14](https://github.com/hypercerts-org/hypercerts/assets/181523/09a59d98-6fa8-46a2-b673-9d44275b1286)

### Describe the Bug

The progress indicator doesn't close when an invalid allow list causes the process to abort.

### Expected Behavior

When an invalid allow list causes the process to abort, the progress indicator should close.

**Comment by bitbeckers** [comment]
@dysbulic thanks for reporting this and sorry for the late response :)

It should be fixed in the current deployment, I tried with a few faulty allowlists. If you want to, could you verify it also works with the file you have?

**Comment by dysbulic** [comment]
> [C]ould you verify it also works with the file you have?

I didn't keep my bad allowlist once I figured out it was bad. 😸 I don't even remember anymore how I'd screwed it up.

I'm sure your fix handles my problem.
