### ISSUE TITLE
[os] enumerate all the metrics we want to analyze for each project : data source

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#842]
### What is it?

For now, just a list of KPIs that would power `Lists ✨`

**Comment by ryscheng** [comment]
I'm not sure what the difference is with this issue
https://github.com/hypercerts-org/hypercerts/issues/841

Can you help clarify?

**Comment by ccerv1** [comment]
@ryscheng metrics like this:
<img width="1354" alt="image" src="https://github.com/hypercerts-org/hypercerts/assets/42869436/f2fe2dfe-716d-4af0-b956-5c7cf1ab9ecd">
