### ISSUE TITLE
[Outreach] Update pilot step-by-step instructions

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#86]
Open questions: 
- Will this go through Gitcoin or can we do it independently?
- via Email / Telgram / Twitter?

**Comment by ccerv1** [comment]
Draft comms for projects: https://docs.google.com/document/d/1Qi6nNFV-_cqExI04e9mYgXCJkoaAYFPEm7TmBQ3U8TU/edit?usp=sharing

**Comment by holkeb** [comment]
holke to check for a simple CRM for the outreach

**Comment by holkeb** [comment]
fyis 
- reg streak, we are currently not allowed to install the streak importer: sent an email to help@pl to check for that
- I checked nethunt as well, which could work alternatively

**Comment by holkeb** [comment]
@ccerv1 we'll be able to use streak for this project

**Comment by holkeb** [comment]
Instead of the separate CTA I think we should update the Gitcoin Pilot instructions in the docs. We can use some of the information from the CTA

**Comment by ccerv1** [comment]
I've made my edits and pushed the updates. If we change the allowlisting to give creators a share of the tokens, then we can create a new issue for documentation.

**Comment by holkeb** [comment]
I added some explanation for the 50%, but it didn't merge correctly: https://github.com/hypercerts-org/hypercerts/pull/469
