### ISSUE TITLE
create Notion page for tracking data sources, projects, and metrics

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#860]
Basically, a landing page that tracks:
- Projects
- Data sources and event streams
- Metrics

**Comment by ryscheng** [comment]
Presumably this is the notion page?
https://www.notion.so/network-goods/Open-Source-Observer-7ac0843ed89b42549f8f29a0f9687448?pvs=4

Can you help me understand the difference between this and #841 and #842?

**Comment by ccerv1** [comment]
Yep, this ended up being three tasks:
- overall Notion page (for sharing with Optimism) - this one
- data sources (841)
- metrics ideas (842)
