### ISSUE TITLE
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#862]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Requires some digging

### Describe the Bug

https://hypercerts.sentry.io/issues/4195186405/?project=4504964062773248&query=is%3Aunresolved&referrer=issue-stream&stream_index=9

### Expected Behavior

Not quite sure what this is. We're just seeing a lot of it.

Is this something we can ignore (and stop reporting to Sentry?) Or is this an error we need to handle in some way?

**Comment by bitbeckers** [comment]
Duplicate #613

**Comment by ryscheng** [comment]
Whoops! my bad. Feel free to close next time.
