### ISSUE TITLE
[SDK] Announce launch

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#869]
### What is it?

After we feel comfortable with: https://github.com/hypercerts-org/hypercerts/issues/868

We should announce the SDK to:

- [ ] Discord community
- [ ] Telegram community
- [ ] Twitter

CC @ccerv1 @holkeb would it make sense to cross-post to adjacent communities?

**Comment by ccerv1** [comment]
Agree. Love it!

**Comment by holkeb** [comment]
Yes, I think we should cross-post it as much as possible

Do we also want to set a date for a community call on the sdk? I imagine an introduction to it with Q&A

**Comment by ryscheng** [comment]
ya check out the meeting notes with the Filecoin Green team on Slack.

It made it very apparent we cannot make any announcements until we have at least some technical documentation on how to use it. Filed issue here:
https://github.com/hypercerts-org/hypercerts/issues/886

**Comment by bitbeckers** [comment]
We want to have the demo apps functional before launch: https://github.com/hypercerts-org/demo-apps

This should be as simple as updating the SDK 🙏

**Comment by bitbeckers** [comment]
https://hypercerts.org/docs/1.4.1/announcements/an-impactful-year.md/
