### ISSUE TITLE
[Ops] Track project funnel health metrics

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#87]
Basic idea:

> Eligible projects
> Projects that received CTA
> Projects that responded to CTA
> Projects that proceed to create.hypercerts.xyz
> Projects that create a hypercert
> 

... etc

**Comment by holkeb** [comment]
implemented in the stages here: https://docs.google.com/spreadsheets/d/1Ps2eTw-FwJdN1he0OkwKep9AgN2C9J6KrH20rGwFESI/edit?usp=sharing

closing this for now
