### ISSUE TITLE
Explore existing OP smart contract analytics on Dune & Github

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#891]
See: https://dune.com/oplabspbc and https://dune.com/optimismfnd
https://github.com/ethereum-optimism/op-analytics

**Comment by ccerv1** [comment]
# Dune

Note: these all rely heavily on the contract mapping spells contained in [this repo](https://github.com/duneanalytics/spellbook/blob/main/models/contracts/optimism/README.md)

## Project Monitoring
- [Optimism - Monthly Usage by Project [All]](https://dune.com/queries/2674216/4446280) -- needs to be migrated; original dashboard [here](https://dune.com/queries/503899)
- [Optimism - Aggregate Projects Contract Stats](https://dune.com/queries/2674439)
- [Optimism - Project Usage Trends (30 vs 90 days)](https://dune.com/queries/502565/950820)
- [Optimism - Project Deepdives](https://dune.com/optimismfnd/optimism-project-deep-dive)

## Other KPIs
- [Developer Metrics Sploring [WIP]](https://dune.com/oplabspbc/developer-metrics-sploring)
- [Optimism - CEX & On/Off-Ramp Usage](https://dune.com/oplabspbc/optimism-onoff-ramp-usage)

## Other Models
- [RPGF2 distributions and voting](https://github.com/duneanalytics/spellbook/tree/main/models/op/retropgf/optimism)

**Comment by ccerv1** [comment]
@ryscheng closing out this issue, but here are the dashboards I'm tracking

**Comment by ryscheng** [comment]
CC @ravenac95
