### ISSUE TITLE
Remove `DappContext` from Plasmic

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#908]
### What is it?

As of this PR
https://github.com/hypercerts-org/hypercerts/pull/897/files#diff-ec7d5d027945189321eda43c3216b8612863d12da4e9c3816cb206086f5bbb47R98

we now wrap the entire application in a DappContext. 

Once we do that, we can remove Plasmic registrations and remove instances in Plasmic. It's a bit of a big refactor, so will save for later.

**Comment by ryscheng** [comment]
One thing we will have to look out for is whether the plasmic-host needs any wrapping

**Comment by bitbeckers** [comment]
It was needed :) Your comment was a lifesaver. My 'quick' solution was to split context (wagmi config) from state (waitToClaim)

Want to to this later this week: https://docs.plasmic.app/learn/global-contexts/

**Comment by bitbeckers** [comment]
Done and running in production. Global context is a nice to have so closing this issue for now
