### ISSUE TITLE
feat: display images for each individual hypercert owner in the treemap

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#915]
Example of current treemap: https://hypercerts.org/app/zuzalu/billboard

Instead of the text images are displayed in the spaces that are allocated to the hypercert owners. This issue includes only the change of the treemap itself. Issue https://github.com/hypercerts-org/hypercerts/issues/917 describes where the image comes from.

Alternative: Instead of having an image for each hypercert owner, we could just have a background image to improve the aesthetics

**Comment by bitbeckers** [comment]
Currently in hyperboard. If you want to reopen, let me know what's missing @holkexyz
