### ISSUE TITLE
[dApp] Cannot mint Zuzalu claims

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#928]
### To Reproduce

Try and hit "Purchase" on zuzalu.hypercerts.org

### Describe the Bug

The check uses the client, but the Zuzalu page doesn't (you use wagmi directly). 

### Expected Behavior

Checks are executed for mainnet and user can mint

**Comment by bitbeckers** [comment]
@holkeb can you confirm it's fixed?

**Comment by holkeb** [comment]
Yes, thank you @bitbeckers, I just tried it and it worked :)
