### ISSUE TITLE
feat: enable web2 users to reserve hypercerts

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#934]
### Describe the feature you'd like to request

A project may want to issue hypercerts to its contributors who do not have a web3 / ETH address yet

### Describe the solution you'd like

A way of formally identifying contributors by email address at the time they create the hypercerts (eg, via a magic link

### Describe alternatives you've considered

Keep the email as plaintext in the contributor field with no verification mechanism

**Comment by bitbeckers** [comment]
Wagmi + Magic provider: https://github.com/magiclabs/wagmi-magic-connector

This got recently incorporated by magic.link. So the tech is available :)

**Comment by bitbeckers** [comment]
Closing in favor of https://github.com/hypercerts-org/HIPs/discussions/5
