### ISSUE TITLE
new purchase form for FtC

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#937]
Adapting the zuzalu purchase form to FtC. Potentially also needed for CryptoEconDay.

Can we just copy and adapt frontend/components/zuzalu-purchase.tsx?

**Comment by holkeb** [comment]
@ryscheng if this is something that you can show me, that would be great

**Comment by holkeb** [comment]
Needed change in from zuzalu-purchase.tsx to ftc-purchase.tsx
1. Line 24: `const DESTINATION_ADDRESS = "zuzalu.eth";`
2. Lines 32, 58, 250, 251, 351: name change of ZuzaluPurchaseFormData
3. Lines 33-55, 59-81, 86-108, 139-161: change names of hypercert and price
4. Line 168 and 173: name change of ZuzaluPurchaseFormProps
5. Line 287: name change percentBuyingZuzalu `(k.startsWith("percentBuyingZuzalu"),`
6. Line 322: create new supabase table and change here `.from("zuzalu-purchase")`
7. Line 348: change path to confirm page

These are the changes that I see are necessary @ryscheng

**Comment by holkeb** [comment]
@ryscheng implemented the changes that I saw necessary: https://github.com/hypercerts-org/hypercerts/pull/938

Can you check that and add if additional things are necessary?

**Comment by bitbeckers** [comment]
@holkeb this can be closed? It's either done, functional or in the hyperboard?
