### ISSUE TITLE
[SDK]: Utility function for fetching my allowlist proof

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#948]
### Describe the feature you'd like to request

Right now I have to understand how to use the OpenZeppelin Merkle tree library to traverse it and find my proof.
We can probably easily abstract it out so that there's less boiler plate.

### Describe the solution you'd like

Right now we have the user do all this:
https://hypercerts.org/docs/next/developer/allowlists#claiming-a-fraction-token

Why not something simple like this:

```
const tx = await hypercerts.mintClaimFractionsFromAllowlist({
  claimIds: [...]
});
```

Under the hood, we can get the user's address, pull the metadata, pull the allowlists, traverse it, get all the proofs, and construct the transaction. Is there value in making the user do that manually?

### Describe alternatives you've considered

1. Leaving it as is.
2. Create a utility function for constructing the args, like `getProofs(claimId, address)`, but still leave it to the user to call `mintClaimFractionFromAllowlist`

**Comment by bitbeckers** [comment]
Added a utility function because I think you want to be able to identify if a minter is part of an allowlist before kicking of the minting flow. 

https://github.com/hypercerts-org/hypercerts/blob/d850154c390c47a99bbb62cfc1eb75a58a411f8a/sdk/src/utils/allowlist.ts#L35
