### ISSUE TITLE
[E2E] Integration test failing in pipeline

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#957]
### To Reproduce

This happens during PRs and on the release to `main`

### Describe the Bug

See: 
* https://github.com/hypercerts-org/hypercerts/actions/runs/5819584340/job/15778270584 => install failed
* https://github.com/hypercerts-org/hypercerts/actions/runs/5799011378/job/15718032832 => `service "after_localchain" didn't complete successfully: exit 1`

### Expected Behavior

E2E passes

**Comment by Jipperism** [comment]
Spent a bunch of time on this today to get everything working again, with our new pnpm setup etc. The tests are running, but failing with a timeout. Had a look at the tests and it seems there are only 2 tests in there, so for now I'm not sure whether these are worth the maintenance cost for now. Maybe we should consider disabling them for now, until we have a bit more time to set it up properly, and add a couple more tests. What's being tested now basically comes down to 1 happy path test, and 1 form validation test ('hypercert does not get minted when not agreeing to the terms and conditions').

@ryscheng @bitbeckers any thoughts?

**Comment by bitbeckers** [comment]
Fine with me to disable it for now. I do a manual mint on almost every PR

**Comment by ryscheng** [comment]
I'd say whoever is responsible for fixing user-reported errors should be the one to make the call.

The intention of the tests is to save you time, so if you're finding that it doesn't serve that purpose, then feel free to re-configure.

Some background:
It was a pretty common occurrence for me that some PR would break end-to-end functionality, even though the project builds and CI/CD passes just fine. So the number of hours I spent chasing user-reported errors, was painful enough for me that I felt building and maintaining integration tests was worth it.
