### ISSUE TITLE
TASK: Define constant number of fraction

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#969]

**Comment by bitbeckers** [comment]
@benedictvscriticus what does this mean exactly? For context in the current FE we have 10000 units in a claim which maps to 100.00.

**Comment by bitbeckers** [comment]
Assuming this means we'll be minting with the amount of fractions as 1 ether, or 10 ^ 18. @holkeb this is what we discussed before and I also made it the default in the starter app. Closing for now
