### ISSUE TITLE
TASK: Define business process for image review

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#973]
Define an image review process for assessing appropriateness
- Establish criteria
- Map approval process to technical workflow
- Allocate system actors and user interface functionality to the review feature

**Comment by benedictvscriticus** [comment]
This should be done on a conceptual level and then translated into a business process following an activity diagram for technical implementation. Reviews should occur pre-implementation and post frontend integration.

**Comment by Jipperism** [comment]
Closing as won't do for now. @holkexyz
