### ISSUE TITLE
TASK: Define requirements for Hyperboard ownership structure

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#978]
Define requirements for the ownership structure of Hyperboards
- Is the data required available in the Graph?
- Do we require React components in the SDK?

- [ ] item 1
- [ ] item 2

**Comment by bitbeckers** [comment]
I think we can read Hypercerts data from the Graph and that components in the SDK are side-effects not features. Basically, we first itterate and refined the flow and components we need (even though a lot has probably has been surfaced in the previous itterations).

For now, to stay web 2.5, my proposal would be to:
- Let an hyperboard admin sign in with their wallet for auth (Sign in with Ethereum, potentially connected to Magic.Link)
- Only let that signed in admin mutate they hyperboard.

Web3 auth, web2 DB. That way, we auth flow can remain as we decentralize in the future.

@Jipperism what do you think?

**Comment by Jipperism** [comment]
Completed.
