### ISSUE TITLE
task: Demo how to hide fractions of a duplicate hypercert

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#981]
# Step 1

- Go into Supabase
- Select the `claims-metadata-mapping` table
- Find the appropriate hypercerts (filter on claimId)
- Set `hidden` to TRUE

# Step 2

- Go to the SQL editor
- Select the "Hide duplicate hypercerts on allowlist" query
- Run the query

![Image](https://github.com/hypercerts-org/hypercerts/assets/42869436/790edce4-c79c-4cc8-8c0c-1545a4b5c872)

# Step 3

- Confirm it's remove from the `allowlistCache-optimism` table

**Comment by ccerv1** [comment]
@holkeb this should be the process. However, I'm noticing that the [Idriss hypercert](https://hypercerts.org/app/view/#claimId=0x822f17a9a5eecfd66dbaff7946a8071c265d1d07-11304180229113575756253304458883339984568320) is no longer in the claims-metadata-mapping table. Did you delete it?

**Comment by holkeb** [comment]
nope, I didn't delete it in claims-metadata-mapping (I only changed the field `hidden` from `false` to `true` for it in the Allowlist-optimism table)
