### ISSUE TITLE
Tweaks and cleanup

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#99]
Issue for cataloging tweaks, cleanup, and verynicetohaves to balance between storing points of attention and managing the amount of issues.

### 1. Contract optimisations
See:
#50

    For loop unchecks
    For loop starts at 1

✅  Not an issue. We need to start at one because that loop splits token values and we leave the original value [0] untouched untill the other changes are complete.

### 2. Next build of SDK
```
./node_modules/@graphql-mesh/graphql/node_modules/@graphql-tools/url-loader/esm/index.js
Critical dependency: the request of a dependency is an expression
```
Known issue: https://github.com/graphprotocol/graph-client/issues/303

### 3. SDK dependencies

Following issue https://github.com/graphprotocol/graph-client/issues/306

We dumped the dependencies is an now also need to remove what isn't needed

✅ https://github.com/Network-Goods/hypercerts-sdk/pull/26

### 4. TODOs in Protocol and SDK

There are a bunch of TODOs in the protocol and SDK repo
The Protocol TODOs sometimes are breaking changes like removing unused storage vars
The SDK TODOs sometimes are very nice to haves like proper error handling

### 5. Harmonise Foundry tests

Test were rapidly set up with specific helper per suite, but a lot of helpers overlap. It's cleaner, more consistent and more efficient to build a common Helpers file

**Comment by bitbeckers** [comment]
See:
#50 

- For loop unchecks
- For loop starts at 1

**Comment by bitbeckers** [comment]
@ryscheng some of these items here should be resolved before releasing to main, assuming that deployment will stay there for a while. What would be a proper deadline for resolving these?

**Comment by ryscheng** [comment]
I might need some more context on the issues, let's discuss at our next meeting?

**Comment by ccerv1** [comment]
@ryscheng can we close this out and/or split into more specific issues?

**Comment by ryscheng** [comment]
@bitbeckers can you share a status update on this issue?

**Comment by ccerv1** [comment]
@ryscheng can we close this out ? :)

**Comment by bitbeckers** [comment]
I think we can close this. Contract work is done and the SDK has been developed a lot since then. No breaking issues here, just nice to haves.
