### ISSUE TITLE
FEAT: Hyperboards with non-financial contributors should display placeholders for non-claimed blueprints.

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#997]

**Comment by benedictvscriticus** [comment]
@holkeb is this still an expected feature?

**Comment by benedictvscriticus** [comment]
@holkeb what do you want to display as a placeholder?

**Comment by benedictvscriticus** [comment]
@holkeb:

- What would you like to display inside placeholders for unclaimed blueprints?
- Would you like to display placeholders for empty speaker slots?

**Comment by holkeb** [comment]
The goal is that the board should look complete even if not all speakers have claimed their hypercerts. In addition it should be visible if a hypercert is claimed or if it is a blueprint. It could only be a small difference.

**Comment by Jipperism** [comment]
@holkeb showing placeholder (or greyed out tiles, possibly with a question mark for the profile picture) should solve the problem of the board looking incomplete when not all hypercerts are claimed.

Adding "empty speaker slot" tiles might be useful if we want to make the board more interactive in the future, for example clicking one of those could open a form to apply as a speaker for the event. We've never spoken about interactivity for now so I think it would make sense to push that forward. That form is also likely to change a lot between different organisations using a hyperboard, as they would probably want different info from their speakers.

**Comment by Jipperism** [comment]
@holkeb we never really converged on a design for the 'placeholder' tiles. Do we stick with grayed out text, and some opacity: 0.8 or similar on the image? Apart from applying that styling, this issue should be done.
