### ISSUE TITLE
QUEST: Are mutations subject to an owner signature?

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#999]

**Comment by bitbeckers** [comment]
@benedictvscriticus @holkeb I'm assuming this is on mutations of the metadata of hypercerts or hyperboards? 

**For hyperboards:**
We have different answers depending on the moment in time.

Before FTC: Holke controls the metadata
After FTC: We can set up a two-step flow where Holke/HF approves changes
After sufficient decentralisation: The entity controlling the board controls the metadata (user, DAO, multisig, ...)

**For hypercerts:**
It's currently completely locked. We discussed making the metadata editable if the owner of the hypercert is the creator and owns 100%.

Is my understanding correct? If it is, these are 4 different user stories and we can create those as such. The last one, changing hypercert metadata, should be relatively easy.

**Comment by benedictvscriticus** [comment]
@bitbeckers correct, lets refine it
